In [1]:
import datetime
## track delay graph
import pandas as pd
from pandas import DataFrame
import numpy as np
import networkx as nx
import peartree as pear
import partridge as ptg
import matplotlib.pyplot as plt
from itertools import tee, product
import warnings
import matplotlib.colors
import re
from functools import reduce
import json
from typing import Literal
from datetime import datetime, date
warnings.filterwarnings('ignore')
matplotlib.style.use('default')
import xarray as xr
np.set_printoptions(suppress=True)

def iterator(L):
	a, b = tee(L)
	next(b, None)
	return list(zip(a,b))

In [2]:
def do_all():

	def from_mta_time(t):
		return(t/100)*60
	lines = sorted(['A','C','E','B','D','F','FX','M','G','J','Z','L','N','Q','R','W','FS','GS','H','1','2','3','4','5','6','6X','7','7X'])
	def midday_deltas(month, day):
		mtatime = [9.5*60*100, 15.5*60*100]
		expected_trips = pd.read_csv('gtfs_subway/trips.txt')
		actual_trips = pd.read_csv(f"sept27data/subwaydatanyc_2025-{month}-{day}_trips.csv")

		expected_times = pd.read_csv('gtfs_subway/stop_times.txt')
		actual_times = pd.read_csv(f"sept27data/subwaydatanyc_2025-{month}-{day}_stop_times.csv")


		def format_time(t, month):
			'''Helper to format MTA timestamps that go over 24 hours due to delays'''
			rd = [int(n) for n in t.split(':')]
			d = 0
			if rd[0] >= 24:
				rd[0] = rd[0] % 24
				d = 1 
			s = ':'.join([str(k) for k in rd])
			datestr = datetime.strptime(f"{month}/{day+d}/2025 {s}", "%m/%d/%Y %H:%M:%S")
			return datestr


		actual_trips['init_time'] = actual_trips.trip_id.map(lambda s: int(s.split('_')[0]))
		actual_trips = actual_trips[actual_trips.init_time.between(mtatime[0],mtatime[1])]
		actual_trips = actual_trips[actual_trips.route_id != 'SI']
		actual_trips.sort_values('init_time', inplace=True)
		actual_trips['short_id'] = actual_trips.trip_id.map(lambda s: ''.join(re.split(r"(\.{1,2}[SN])",s)[:-1]))
		expected_trips = expected_trips[~expected_trips.route_id.isin(['SI','SS'])]
		expected_trips = expected_trips[expected_trips.service_id == 'Weekday']
		expected_trips['short_id'] = expected_trips.trip_id.map(lambda s: '_'.join(s.split('_')[-2:]))
		expected_trips['init_time'] = expected_trips.trip_id.map(lambda s: int(s.split('_')[-2]))
		expected_trips = expected_trips[expected_trips.init_time.between(mtatime[0],mtatime[1])]
		expected_trips.short_id = expected_trips.short_id.map(lambda s: s[:-3])
		expected_trips = expected_trips.astype(str)
		expected_trips = expected_trips[['route_id','short_id', 'trip_id']]
		expected_trips.columns = ['route_id', 'short_id', 'full_trip_id']
		actual_trips = actual_trips[['trip_uid','route_id','trip_id','direction_id','start_time','short_id','init_time']]
		merged = pd.merge(actual_trips, expected_trips, on='short_id')
		merged['unique'] = merged.trip_id.map(lambda s: merged.trip_id.value_counts(sort=False).to_dict()[s])
		merged['route_id'] = list(zip(merged['route_id_x'], merged['route_id_y']))
		merged.route_id = merged.route_id.map(lambda x: x[0] if len(np.unique_values(list(x)))==1 else x)
		idkey = {v: k for k,v in zip(merged.trip_uid, merged.full_trip_id)}
		expected_times = expected_times[~expected_times.trip_id.str.startswith('SIR-')]
		expected_times['id_key'] =expected_times.trip_id.map(lambda s: '_'.join(s.split('-')[-1].split('_')[1:]))
		expected_times['key'] = expected_times.trip_id.map(lambda k: idkey.get(k))+expected_times.stop_id.astype(str)
		expected_times = expected_times[~expected_times.key.isna()]
		expected_times.sort_values('key')
		expected_times.columns = ['full_trip_id', 'stop_id','expected_arrival','departure','seq','short_id','key']
		real_time = actual_times.copy()
		real_time = real_time[real_time['trip_uid'].isin(merged.trip_uid)]
		real_time.stop_id = real_time.stop_id.map(lambda a: str(a[:-1]))
		real_time = real_time[~(real_time.arrival_time.isna() & real_time.departure_time.isna())]
		real_time['key'] = [a+b for a,b in zip(real_time.trip_uid, real_time.stop_id)]
		real_time.arrival_time = [int(a[np.nanargmax(a)]) for a in zip(real_time.arrival_time, real_time.departure_time)]
		real_time['init_time'] = real_time.trip_uid.map(lambda s: int(s.split('_')[0]))
		real_time.arrival_time = real_time.arrival_time.map(lambda t: datetime.fromtimestamp(t).time())
		real_time.sort_values('key')
		ddict = dict(zip(expected_trips.full_trip_id.values,expected_trips.short_id.map(lambda n: n[-1])))
		iddict = dict(zip(expected_trips.full_trip_id, expected_trips.route_id))
		expected_times['route'] = expected_times.full_trip_id.map(lambda x: iddict.get(x))
		expected_times['direction'] = expected_times.full_trip_id.map(lambda x: ddict.get(x))
		full_merge =pd.merge(real_time, expected_times, on='key')
		full_merge = full_merge[full_merge.expected_arrival.notna()]
		full_merge = full_merge[['stop_id_x','arrival_time','expected_arrival','seq', 'route','direction']]
		full_merge.drop('seq', axis=1,inplace=True)
		full_merge['delta']=[(format_time(a)-format_time(b)).total_seconds() for a,b in zip(full_merge.arrival_time.astype(str), full_merge.expected_arrival.astype(str))]
		deltas = full_merge[['stop_id_x','route','direction','delta']]
		return deltas

In [3]:
def midday_deltas(day):
	mtatime = [9.5*60*100, 15.5*60*100]
	expected_trips = pd.read_csv('gtfs_subway/trips.txt')
	actual_trips = pd.read_csv(f"sept27data/subwaydatanyc_2025-09-{day}_trips.csv")

	expected_times = pd.read_csv('gtfs_subway/stop_times.txt')
	actual_times = pd.read_csv(f"sept27data/subwaydatanyc_2025-09-{day}_stop_times.csv")


	def format_time(t):
		'''Helper to format MTA timestamps that go over 24 hours due to delays'''
		rd = [int(n) for n in t.split(':')]
		d = 0
		if rd[0] >= 24:
			rd[0] = rd[0] % 24
			d = 1 
		s = ':'.join([str(k) for k in rd])
		datestr = datetime.strptime(f"9/{day+d}/2025 {s}", "%m/%d/%Y %H:%M:%S")
		return datestr


	actual_trips['init_time'] = actual_trips.trip_id.map(lambda s: int(s.split('_')[0]))
	actual_trips = actual_trips[actual_trips.init_time.between(mtatime[0],mtatime[1])]
	actual_trips = actual_trips[actual_trips.route_id != 'SI']
	actual_trips.sort_values('init_time', inplace=True)
	actual_trips['short_id'] = actual_trips.trip_id.map(lambda s: ''.join(re.split(r"(\.{1,2}[SN])",s)[:-1]))
	expected_trips = expected_trips[~expected_trips.route_id.isin(['SI','SS'])]
	expected_trips = expected_trips[expected_trips.service_id == 'Weekday']
	expected_trips['short_id'] = expected_trips.trip_id.map(lambda s: '_'.join(s.split('_')[-2:]))
	expected_trips['init_time'] = expected_trips.trip_id.map(lambda s: int(s.split('_')[-2]))
	expected_trips = expected_trips[expected_trips.init_time.between(mtatime[0],mtatime[1])]
	expected_trips.short_id = expected_trips.short_id.map(lambda s: s[:-3])
	expected_trips = expected_trips.astype(str)
	expected_trips = expected_trips[['route_id','short_id', 'trip_id']]
	expected_trips.columns = ['route_id', 'short_id', 'full_trip_id']
	actual_trips = actual_trips[['trip_uid','route_id','trip_id','direction_id','start_time','short_id','init_time']]
	merged = pd.merge(actual_trips, expected_trips, on='short_id')
	merged['unique'] = merged.trip_id.map(lambda s: merged.trip_id.value_counts(sort=False).to_dict()[s])
	merged['route_id'] = list(zip(merged['route_id_x'], merged['route_id_y']))
	merged.route_id = merged.route_id.map(lambda x: x[0] if len(np.unique_values(list(x)))==1 else x)
	idkey = {v: k for k,v in zip(merged.trip_uid, merged.full_trip_id)}
	expected_times = expected_times[~expected_times.trip_id.str.startswith('SIR-')]
	expected_times['id_key'] =expected_times.trip_id.map(lambda s: '_'.join(s.split('-')[-1].split('_')[1:]))
	expected_times['key'] = expected_times.trip_id.map(lambda k: idkey.get(k))+expected_times.stop_id.astype(str)
	expected_times = expected_times[~expected_times.key.isna()]
	expected_times.sort_values('key')
	expected_times.columns = ['full_trip_id', 'stop_id','expected_arrival','departure','seq','short_id','key']
	real_time = actual_times.copy()
	real_time = real_time[real_time['trip_uid'].isin(merged.trip_uid)]
	real_time.stop_id = real_time.stop_id.map(lambda a: str(a[:-1]))
	real_time = real_time[~(real_time.arrival_time.isna() & real_time.departure_time.isna())]
	real_time['key'] = [a+b for a,b in zip(real_time.trip_uid, real_time.stop_id)]
	real_time.arrival_time = [int(a[np.nanargmax(a)]) for a in zip(real_time.arrival_time, real_time.departure_time)]
	real_time['init_time'] = real_time.trip_uid.map(lambda s: int(s.split('_')[0]))
	real_time.arrival_time = real_time.arrival_time.map(lambda t: datetime.fromtimestamp(t).time())
	real_time.sort_values('key')
	ddict = dict(zip(expected_trips.full_trip_id.values,expected_trips.short_id.map(lambda n: n[-1])))
	iddict = dict(zip(expected_trips.full_trip_id, expected_trips.route_id))
	expected_times['route'] = expected_times.full_trip_id.map(lambda x: iddict.get(x))
	expected_times['direction'] = expected_times.full_trip_id.map(lambda x: ddict.get(x))
	full_merge =pd.merge(real_time, expected_times, on='key')
	full_merge = full_merge[full_merge.expected_arrival.notna()]
	full_merge = full_merge[['stop_id_x','arrival_time','expected_arrival','seq', 'route','direction']]
	full_merge.drop('seq', axis=1,inplace=True)
	full_merge['delta']=[(format_time(a)-format_time(b)).total_seconds() for a,b in zip(full_merge.arrival_time.astype(str), full_merge.expected_arrival.astype(str))]
	deltas = full_merge[['stop_id_x','route','direction','delta']]
	return deltas

In [4]:
sep22 = midday_deltas(22)
sep23 = midday_deltas(23)
sep24 = midday_deltas(24)
sep25 = midday_deltas(25)
sep26 = midday_deltas(26)
sep27week = pd.concat([sep22,sep23,sep24,sep25,sep26]).reset_index(drop=True)
sep27week.columns = ['stop','line','dir','delta']
sep27avg = sep27week.groupby(["stop",'dir','line']).agg({'delta':'mean'})
deltadict=dict(zip(sep27avg.index.values, sep27avg.delta))
mtidx = pd.MultiIndex.from_tuples(list(product(all_stops, ['N','S'])), names=['stop','dir'])
full_grid = pd.DataFrame(index=mtidx, columns=lines)
for k,v in deltadict.items():
	full_grid.at[(k[0],k[1]),k[2]] = v

NameError: name 'all_stops' is not defined

In [ ]:
full_grid[full_grid.isna().all(1)]

,,1,2,3,4,5,6,6X,7,7X,A,...,GS,H,J,L,M,N,Q,R,W,Z
stop,dir,,,,,,,,,,,,,,,,,,,,,
711,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
713,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H01,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## we can extrapolate 711 and 713 Southbound since they dont share tracks and only use the 7, so the average delay from previous and following stops will work here
full_grid.at[('711','S'),'7'] = (full_grid.loc['710','S']['7']+full_grid.loc['712','S']['7'])/2
full_grid.at[('713','S'),'7'] = (full_grid.loc['712','S']['7']+full_grid.loc['714','S']['7'])/2

## aqueduct racetrack is a oneway stop so we can just assume the delay would be the same
full_grid.at[('H01','S'),'A'] = full_grid.at[('H01','N'),'A']
full_grid[full_grid.isna().all(1)]
full_grid_md = full_grid.copy()
aggstops = {k: lambda x: np.nanmean(x, axis=0, dtype=np.float64) for k in lines}
aggstops['stop'] = 'first'
full_grid_md_avg = full_grid_md.reset_index().drop('dir', axis=1).groupby('stop').agg(aggstops)
delay_times = full_grid_md_avg.drop('stop',axis=1).apply(lambda x: np.nanmean(x),axis=1)
np.round(delay_times.values.clip(0)/60).clip(0,5)
daymindf = pd.DataFrame(delay_times, columns=['seconds'])
daymindf['mins'] = np.round(delay_times.values.clip(0)/60).clip(0,5)
daymindf.mins.to_csv('data/delay_minutes_midday.csv')

In [ ]:
#raise RuntimeError('i forgot variable names in notebooks are cringe')

### get tph

In [ ]:
import time

In [ ]:
expected_trips = pd.read_csv('gtfs_subway/trips.txt')
expected_times = pd.read_csv('gtfs_subway/stop_times.txt')
expected_trips = expected_trips[expected_trips.service_id == 'Weekday']
expected_trips = expected_trips[expected_trips.route_id != 'SI']
expected_times = expected_times[expected_times.trip_id.isin(expected_trips.trip_id)]
routedict = dict(zip(expected_trips.trip_id, expected_trips.route_id))
dirdict = dict(zip(expected_trips.trip_id, expected_trips.direction_id))
expected_times['dir'] = expected_times.trip_id.map(lambda id: dirdict.get(id))
expected_times['route_id'] = expected_times.trip_id.map(lambda id: routedict.get(id))
expected_times['hour'] = expected_times.arrival_time.map(lambda h: float(h[:4].replace(':','.')))
expected_times = expected_times[expected_times.hour.between(11,14,'both')]
tph = expected_times.copy()[['stop_id','dir','route_id']]
tph.dir = tph.dir.map(lambda d: "NS"[d])
tph = tph.groupby(['stop_id','dir']).agg({'route_id':lambda w: w.to_list()})

tph['tph'] = tph.route_id.map(lambda w: (pd.value_counts(w)/3).to_dict()).values
tphavg = tph.drop('route_id', axis=1)
tphavg['route'] = tph.tph.map(lambda w: list(w.keys()))
tphavg['tphs'] = tph.tph.map(lambda w: list(w.values()))
tphavg.drop('tph',axis=1,inplace=True)
tphavg = tphavg.reset_index().explode(['route','tphs'])
tphavg.tphs = tphavg.tphs.astype(float)
tphavg = tphavg.groupby(['stop_id','route']).agg({'tphs':'mean'})
tphavg.reset_index(inplace=True)
tphavg.stop_id = tphavg.stop_id.astype(str)
tphavg = tphavg.sort_values('stop_id').groupby('stop_id').agg(lambda x: x.to_list())
tphavg.reset_index(inplace=True)
tphdict = dict(zip(tphavg.stop_id, [dict(zip(a,b)) for a,b in zip(tphavg.route, tphavg.tphs)]))

In [ ]:
tphdict

{'101': {'1': 11.166666666666666},
 '103': {'1': 11.0},
 '104': {'1': 11.0},
 '106': {'1': 10.833333333333334},
 '107': {'1': 11.166666666666666},
 '108': {'1': 11.0},
 '109': {'1': 11.0},
 '110': {'1': 11.0},
 '111': {'1': 11.0},
 '112': {'1': 11.0},
 '113': {'1': 11.0},
 '114': {'1': 11.0},
 '115': {'1': 11.0},
 '116': {'1': 11.0},
 '117': {'1': 10.833333333333332},
 '118': {'1': 11.0},
 '119': {'1': 10.833333333333334},
 '120': {'1': 11.0, '2': 8.0, '3': 7.833333333333334},
 '121': {'1': 10.833333333333332},
 '122': {'1': 11.0},
 '123': {'2': 8.0, '3': 8.166666666666668, '1': 11.0},
 '124': {'1': 11.0},
 '125': {'1': 10.833333333333332},
 '126': {'1': 11.166666666666668},
 '127': {'1': 10.833333333333332, '2': 8.166666666666668, '3': 8.0},
 '128': {'1': 10.833333333333332,
  '2': 8.166666666666668,
  '3': 7.833333333333334},
 '129': {'1': 11.0},
 '130': {'1': 11.166666666666668},
 '131': {'1': 10.833333333333332},
 '132': {'1': 10.833333333333332, '2': 8.0, '3': 8.0},
 '133': {'1': 10.833333333333332},
 '134': {'1': 11.166666666666668},
 '135': {'1': 11.0},
 '136': {'1': 10.833333333333332},
 '137': {'1': 10.833333333333332, '2': 8.0, '3': 7.833333333333334},
 '138': {'1': 11.0},
 '139': {'1': 11.0},
 '142': {'1': 11.0},
 '201': {'2': 8.0},
 '204': {'2': 8.0},
 '205': {'2': 8.0},
 '206': {'2': 8.0},
 '207': {'2': 7.833333333333334},
 '208': {'2': 8.0},
 '209': {'2': 8.0},
 '210': {'2': 8.0},
 '211': {'2': 7.833333333333334},
 '212': {'2': 7.833333333333334},
 '213': {'5': 8.166666666666668, '2': 8.0},
 '214': {'2': 8.0, '5': 7.833333333333334},
 '215': {'5': 8.166666666666668, '2': 7.833333333333334},
 '216': {'2': 8.0, '5': 8.0},
 '217': {'5': 8.0, '2': 8.0},
 '218': {'2': 8.0, '5': 7.833333333333334},
 '219': {'2': 7.833333333333334, '5': 8.0},
 '220': {'2': 7.666666666666667, '5': 8.166666666666668},
 '221': {'2': 8.0, '5': 8.166666666666668},
 '222': {'5': 8.0, '2': 8.0},
 '224': {'3': 8.0, '2': 7.833333333333334},
 '225': {'2': 8.0, '3': 7.666666666666667},
 '226': {'2': 8.0, '3': 7.833333333333334},
 '227': {'2': 8.0, '3': 8.0},
 '228': {'3': 7.833333333333334, '2': 8.0},
 '229': {'2': 8.0, '3': 7.833333333333334},
 '230': {'3': 8.0, '2': 7.833333333333334},
 '231': {'3': 7.833333333333334, '2': 8.0},
 '232': {'3': 8.0, '2': 8.0},
 '233': {'2': 7.833333333333334, '3': 8.0},
 '234': {'5': 8.0, '4': 4.333333333333333, '2': 7.666666666666667, '3': 8.0},
 '235': {'5': 7.833333333333334,
  '4': 4.333333333333333,
  '2': 7.666666666666667,
  '3': 8.0},
 '236': {'2': 8.0, '3': 7.833333333333334},
 '237': {'2': 8.0, '3': 7.833333333333334},
 '238': {'2': 8.0, '3': 7.833333333333334},
 '239': {'3': 8.0, '2': 7.833333333333334, '4': 4.333333333333333, '5': 8.0},
 '241': {'2': 8.0, '5': 7.833333333333334},
 '242': {'2': 8.0, '5': 7.833333333333334},
 '243': {'5': 7.833333333333334, '2': 8.0},
 '244': {'2': 8.0, '5': 8.0},
 '245': {'2': 8.0, '5': 7.833333333333334},
 '246': {'5': 8.0, '2': 7.833333333333334},
 '247': {'5': 8.0, '2': 8.0},
 '248': {'3': 8.0},
 '249': {'3': 7.833333333333334},
 '250': {'4': 4.333333333333334, '3': 7.833333333333334},
 '251': {'3': 8.0},
 '252': {'3': 8.0},
 '253': {'3': 8.0},
 '254': {'3': 7.833333333333334},
 '255': {'3': 7.833333333333334},
 '256': {'3': 7.833333333333334},
 '257': {'3': 8.0},
 '301': {'3': 8.0},
 '302': {'3': 8.0},
 '401': {'4': 3.666666666666667},
 '402': {'4': 4.333333333333334},
 '405': {'4': 4.166666666666666},
 '406': {'4': 3.666666666666667},
 '407': {'4': 4.166666666666666},
 '408': {'4': 3.833333333333333},
 '409': {'4': 4.0},
 '410': {'4': 4.0},
 '411': {'4': 4.166666666666667},
 '412': {'4': 3.8333333333333335},
 '413': {'4': 4.333333333333333},
 '414': {'4': 4.333333333333333},
 '415': {'4': 4.166666666666667},
 '416': {'4': 4.166666666666667, '5': 8.333333333333332},
 '418': {'5': 8.0, '4': 3.5},
 '419': {'5': 8.0, '4': 4.333333333333333},
 '420': {'4': 3.5, '5': 7.666666666666667},
 '423': {'5': 8.0, '4': 4.333333333333333},
 '501': {'5': 8.166666666666668},
 '502': {'5': 8.166666666666668},
 '503': {'5': 8.0},
 '504': {'5': 8.166666666666668},
 '505': {'5': 8.166666666666668},
 '601': {'6X': 2.3333333333333335, '6': 5.666666666666666},
 '602': {'6': 5.666666666666666, '6X': 2.666666666666667},
 '603': {'6X': 2.666666666666667, '6': 5.333333333333334},
 '604': {'6': 5.333333333333334, '6X': 2.666666666666667},
 '606': {'6': 5.333333333333334, '6X': 2.666666666666667},
 '607': {'6': 5.333333333333334, '6X': 2.666666666666667},
 '608': {'6': 13.166666666666666, '6X': 2.8333333333333335},
 '609': {'6': 13.166666666666666},
 '610': {'6': 12.833333333333334},
 '611': {'6': 12.833333333333334},
 '612': {'6': 13.0},
 '613': {'6': 12.666666666666668, '6X': 3.1666666666666665},
 '614': {'6': 12.666666666666668},
 '615': {'6': 12.666666666666668},
 '616': {'6': 12.5},
 '617': {'6': 12.333333333333332},
 '618': {'6': 12.333333333333332},
 '619': {'6': 12.333333333333332, '6X': 3.5},
 '621': {'5': 8.166666666666666,
  '4': 3.666666666666667,
  '6': 12.166666666666666,
  '6X': 3.6666666666666665},
 '622': {'6X': 3.6666666666666665, '6': 12.0},
 '623': {'6': 12.0, '6X': 3.833333333333333},
 '624': {'6': 12.0, '6X': 3.833333333333333},
 '625': {'6': 11.833333333333334, '6X': 3.833333333333333},
 '626': {'4': 3.6666666666666665,
  '6X': 4.0,
  '5': 8.333333333333332,
  '6': 12.0},
 '627': {'6X': 4.0, '6': 11.666666666666668},
 '628': {'6X': 4.166666666666667, '6': 11.666666666666668},
 '629': {'4': 3.833333333333333,
  '5': 8.0,
  '6': 11.666666666666668,
  '6X': 4.166666666666667},
 '630': {'6': 11.666666666666668, '6X': 4.166666666666667},
 '631': {'4': 3.6666666666666665,
  '5': 8.166666666666668,
  '6': 11.5,
  '6X': 4.333333333333333},
 '632': {'6X': 4.5, '6': 11.333333333333332},
 '633': {'6X': 4.5, '6': 11.5},
 '634': {'6X': 4.5, '6': 11.333333333333332},
 '635': {'6X': 4.5, '6': 11.333333333333332, '5': 8.166666666666668, '4': 3.5},
 '636': {'6': 11.333333333333332, '6X': 4.666666666666666},
 '637': {'6': 11.0, '6X': 4.666666666666666},
 '638': {'6': 11.0, '6X': 4.833333333333333},
 '639': {'6': 11.166666666666666, '6X': 4.833333333333333},
 '640': {'4': 3.666666666666667,
  '5': 7.833333333333334,
  '6': 10.666666666666668,
  '6X': 5.0},
 '701': {'7': 12.666666666666666},
 '702': {'7': 12.666666666666666},
 '705': {'7': 12.666666666666666},
 '706': {'7': 12.666666666666666},
 '707': {'7': 12.666666666666666},
 '708': {'7': 12.666666666666666},
 '709': {'7': 12.666666666666666},
 '710': {'7': 12.666666666666666},
 '711': {'7': 12.666666666666666},
 '712': {'7': 12.666666666666666},
 '713': {'7': 12.666666666666666},
 '714': {'7': 12.666666666666666},
 '715': {'7': 12.666666666666666},
 '716': {'7': 12.666666666666666},
 '718': {'7': 12.666666666666666},
 '719': {'7': 12.666666666666666},
 '720': {'7': 12.666666666666666},
 '721': {'7': 12.666666666666666},
 '723': {'7': 12.666666666666666},
 '724': {'7': 12.666666666666666},
 '725': {'7': 12.666666666666666},
 '726': {'7': 12.666666666666666},
 '901': {'GS': 12.666666666666666},
 '902': {'GS': 12.666666666666666},
 'A02': {'A': 7.333333333333333},
 'A03': {'A': 7.166666666666666},
 'A05': {'A': 7.5},
 'A06': {'A': 7.333333333333333},
 'A07': {'A': 7.333333333333333},
 'A09': {'A': 7.5, 'C': 8.0},
 'A10': {'C': 7.833333333333334},
 'A11': {'C': 7.833333333333334},
 'A12': {'A': 7.166666666666666, 'C': 7.833333333333334},
 'A14': {'B': 8.0, 'C': 7.833333333333334},
 'A15': {'D': 8.333333333333332, 'C': 8.0, 'B': 8.0, 'A': 7.166666666666666},
 'A16': {'B': 7.833333333333334, 'C': 8.0},
 'A17': {'B': 8.0, 'C': 7.833333333333334},
 'A18': {'B': 8.0, 'C': 8.0},
 'A19': {'B': 8.0, 'C': 7.833333333333334},
 'A20': {'B': 8.0, 'C': 8.0},
 'A21': {'C': 8.0, 'B': 8.0},
 'A22': {'B': 7.666666666666667, 'C': 8.0},
 'A24': {'A': 7.333333333333334,
  'B': 8.0,
  'C': 8.166666666666668,
  'D': 8.166666666666668},
 'A25': {'C': 7.833333333333334, 'E': 9.666666666666668},
 'A27': {'C': 8.0, 'E': 9.5, 'A': 7.166666666666666},
 'A28': {'A': 7.166666666666666, 'C': 8.0, 'E': 9.333333333333332},
 'A30': {'C': 7.666666666666667, 'E': 9.5},
 'A31': {'A': 7.166666666666666,
  'C': 7.666666666666667,
  'E': 9.833333333333332},
 'A32': {'E': 9.666666666666666, 'A': 7.166666666666666, 'C': 8.0},
 'A33': {'E': 9.666666666666668, 'C': 8.0},
 'A34': {'A': 7.333333333333333,
  'C': 7.833333333333334,
  'E': 9.666666666666668},
 'A36': {'A': 7.333333333333333, 'C': 7.666666666666667},
 'A38': {'A': 7.333333333333334, 'C': 7.666666666666667},
 'A40': {'A': 7.333333333333333, 'C': 7.833333333333334},
 'A41': {'C': 7.833333333333334, 'F': 9.5, 'A': 7.166666666666666},
 'A42': {'A': 7.166666666666666, 'C': 8.0, 'G': 8.0},
 'A43': {'C': 7.833333333333334},
 'A44': {'C': 7.833333333333334},
 'A45': {'C': 8.0},
 'A46': {'A': 7.333333333333334, 'C': 7.833333333333334},
 'A47': {'C': 8.0},
 'A48': {'A': 7.5, 'C': 8.0},
 'A49': {'C': 8.0},
 'A50': {'C': 8.0},
 'A51': {'C': 7.833333333333334, 'A': 7.166666666666666},
 'A52': {'C': 7.833333333333334},
 'A53': {'C': 7.833333333333334},
 'A54': {'C': 8.0},
 'A55': {'A': 7.5, 'C': 7.833333333333334},
 'A57': {'A': 7.166666666666666},
 'A59': {'A': 7.333333333333333},
 'A60': {'A': 7.333333333333333},
 'A61': {'A': 7.333333333333334},
 'A63': {'A': 3.5},
 'A64': {'A': 3.6666666666666665},
 'A65': {'A': 3.6666666666666665},
 'B04': {'F': 9.166666666666668},
 'B06': {'F': 9.166666666666668},
 'B08': {'F': 9.333333333333332, 'Q': 7.833333333333334},
 'B10': {'F': 9.166666666666668},
 'B12': {'D': 8.0},
 'B13': {'D': 8.0},
 'B14': {'D': 8.166666666666668},
 'B15': {'D': 8.166666666666668},
 'B16': {'D': 7.833333333333334},
 'B17': {'D': 8.0},
 'B18': {'D': 8.0},
 'B19': {'D': 8.166666666666668},
 'B20': {'D': 8.0},
 'B21': {'D': 8.0},
 'B22': {'D': 7.833333333333334},
 'B23': {'D': 8.0},
 'D01': {'D': 8.166666666666666},
 'D03': {'B': 4.0, 'D': 8.333333333333332},
 'D04': {'D': 8.166666666666666, 'B': 4.0},
 'D05': {'B': 4.0, 'D': 8.333333333333332},
 'D06': {'B': 4.0, 'D': 8.333333333333332},
 'D07': {'B': 3.833333333333333, 'D': 8.333333333333332},
 'D08': {'B': 4.0, 'D': 8.333333333333332},
 'D09': {'B': 4.0, 'D': 8.0},
 'D10': {'D': 8.333333333333332, 'B': 4.0},
 'D11': {'B': 4.0, 'D': 8.333333333333332},
 'D12': {'B': 3.833333333333333, 'D': 8.166666666666668},
 'D13': {'B': 8.0, 'D': 8.166666666666668},
 'D14': {'B': 8.0, 'D': 8.166666666666668, 'E': 9.5},
 'D15': {'M': 7.833333333333334, 'F': 9.0, 'D': 8.166666666666666, 'B': 8.0},
 'D16': {'B': 7.666666666666667,
  'D': 8.333333333333332,
  'F': 9.166666666666668,
  'M': 7.666666666666667},
 'D17': {'B': 7.666666666666667,
  'D': 8.166666666666668,
  'F': 9.166666666666668,
  'M': 7.833333333333334},
 'D18': {'M': 8.0, 'F': 9.166666666666668},
 'D19': {'F': 9.333333333333334, 'M': 7.833333333333334},
 'D20': {'B': 8.0,
  'D': 8.166666666666668,
  'F': 9.166666666666668,
  'M': 7.833333333333334},
 'D21': {'B': 8.0, 'D': 8.0, 'F': 9.166666666666668, 'M': 8.0},
 'D22': {'D': 8.166666666666668, 'B': 7.666666666666667},
 'D24': {'B': 8.0, 'Q': 8.0},
 'D25': {'B': 8.0, 'Q': 7.833333333333334},
 'D26': {'B': 7.833333333333334,
  'FS': 6.333333333333333,
  'Q': 8.166666666666668},
 'D27': {'Q': 8.0},
 'D28': {'B': 8.0, 'Q': 8.0},
 'D29': {'Q': 7.666666666666667},
 'D30': {'Q': 7.666666666666667},
 'D31': {'Q': 7.833333333333334, 'B': 8.0},
 'D32': {'Q': 8.0},
 'D33': {'Q': 8.0},
 'D34': {'Q': 8.166666666666668},
 'D35': {'B': 7.833333333333334, 'Q': 7.833333333333334},
 'D37': {'Q': 8.0},
 'D38': {'Q': 7.833333333333334},
 'D39': {'B': 7.666666666666667, 'Q': 8.0},
 'D40': {'Q': 8.0, 'B': 7.833333333333334},
 'D41': {'Q': 8.0},
 'D42': {'F': 9.666666666666666, 'Q': 8.0},
 'D43': {'D': 8.0, 'F': 9.5, 'N': 7.666666666666666, 'Q': 8.0},
 'E01': {'E': 9.666666666666666},
 'F01': {'F': 9.166666666666668},
 'F02': {'F': 9.166666666666668},
 'F03': {'F': 9.166666666666668},
 'F04': {'F': 9.166666666666668},
 'F05': {'F': 9.166666666666668},
 'F06': {'E': 9.666666666666668, 'F': 9.333333333333332},
 'F07': {'F': 9.166666666666668},
 'F09': {'E': 9.833333333333332, 'M': 7.666666666666667},
 'F11': {'E': 9.666666666666668, 'M': 8.0},
 'F12': {'E': 9.666666666666668, 'M': 8.0},
 'F14': {'F': 9.333333333333334},
 'F15': {'F': 9.5},
 'F16': {'F': 9.166666666666668},
 'F18': {'F': 9.333333333333334},
 'F20': {'F': 9.166666666666668, 'G': 8.0},
 'F21': {'F': 9.333333333333334, 'G': 8.0},
 'F22': {'F': 9.333333333333334, 'G': 8.0},
 'F23': {'F': 9.5, 'G': 8.0},
 'F24': {'G': 8.0, 'F': 9.333333333333334},
 'F25': {'F': 9.333333333333334, 'G': 8.0},
 'F26': {'F': 9.5, 'G': 8.0},
 'F27': {'F': 9.5, 'G': 8.0},
 'F29': {'F': 9.333333333333334},
 'F30': {'F': 9.333333333333332},
 'F31': {'F': 9.166666666666668},
 'F32': {'F': 9.5},
 'F33': {'F': 9.5},
 'F34': {'F': 9.5},
 'F35': {'F': 9.333333333333332},
 'F36': {'F': 9.333333333333334},
 'F38': {'F': 9.5},
 'F39': {'F': 9.333333333333334},
 'G05': {'E': 9.833333333333334, 'J': 7.833333333333334},
 'G06': {'E': 9.833333333333334, 'J': 7.666666666666667},
 'G07': {'E': 9.833333333333332},
 'G08': {'R': 7.833333333333334,
  'M': 7.666666666666667,
  'F': 9.166666666666668,
  'E': 10.0},
 'G09': {'M': 7.833333333333334, 'R': 8.0},
 'G10': {'M': 8.0, 'R': 8.0},
 'G11': {'M': 8.0, 'R': 8.0},
 'G12': {'M': 7.666666666666667, 'R': 7.833333333333334},
 'G13': {'R': 7.833333333333334, 'M': 7.666666666666667},
 'G14': {'E': 9.833333333333334, 'F': 9.166666666666668, 'M': 8.0, 'R': 8.0},
 'G15': {'M': 7.833333333333334, 'R': 7.833333333333334},
 'G16': {'M': 7.833333333333334, 'R': 7.833333333333334},
 'G18': {'M': 7.666666666666667, 'R': 7.833333333333334},
 'G19': {'R': 7.833333333333334, 'M': 7.833333333333334},
 'G20': {'R': 7.833333333333334, 'M': 8.0},
 'G21': {'E': 9.666666666666668,
  'M': 7.833333333333334,
  'R': 7.833333333333334},
 'G22': {'G': 8.0},
 'G24': {'G': 8.0},
 'G26': {'G': 8.0},
 'G28': {'G': 8.0},
 'G29': {'G': 8.0},
 'G30': {'G': 7.833333333333334},
 'G31': {'G': 7.833333333333334},
 'G32': {'G': 8.0},
 'G33': {'G': 8.0},
 'G34': {'G': 8.0},
 'G35': {'G': 8.166666666666668},
 'G36': {'G': 7.833333333333334},
 'H01': {'A': 3.6666666666666665},
 'H02': {'A': 3.6666666666666665},
 'H03': {'A': 3.6666666666666665},
 'H04': {'A': 3.666666666666667, 'H': 4.166666666666666},
 'H06': {'A': 3.833333333333333},
 'H07': {'A': 4.0},
 'H08': {'A': 3.833333333333333},
 'H09': {'A': 4.0},
 'H10': {'A': 3.833333333333333},
 'H11': {'A': 3.833333333333333},
 'H12': {'H': 4.166666666666666},
 'H13': {'H': 4.333333333333333},
 'H14': {'H': 4.333333333333333},
 'H15': {'H': 4.333333333333333},
 'J12': {'J': 8.0},
 'J13': {'J': 8.0},
 'J14': {'J': 7.833333333333334},
 'J15': {'J': 8.0},
 'J16': {'J': 8.0},
 'J17': {'J': 8.0},
 'J19': {'J': 8.0},
 'J20': {'J': 7.833333333333334},
 'J21': {'J': 8.0},
 'J22': {'J': 8.0},
 'J23': {'J': 8.0},
 'J24': {'J': 8.0},
 'J27': {'J': 7.833333333333334},
 'J28': {'J': 8.0},
 'J29': {'J': 8.0},
 'J30': {'J': 7.833333333333334},
 'J31': {'J': 7.666666666666667},
 'L01': {'L': 13.833333333333332},
 'L02': {'L': 13.833333333333332},
 'L03': {'L': 13.666666666666666},
 'L05': {'L': 13.666666666666666},
 'L06': {'L': 13.666666666666666},
 'L08': {'L': 13.666666666666666},
 'L10': {'L': 13.666666666666668},
 'L11': {'L': 13.833333333333332},
 'L12': {'L': 13.666666666666666},
 'L13': {'L': 13.666666666666668},
 'L14': {'L': 13.666666666666668},
 'L15': {'L': 13.833333333333332},
 'L16': {'L': 13.666666666666668},
 'L17': {'L': 13.666666666666668},
 'L19': {'L': 13.833333333333334},
 'L20': {'L': 13.666666666666668},
 'L21': {'L': 13.833333333333334},
 'L22': {'L': 13.833333333333334},
 'L24': {'L': 13.833333333333334},
 'L25': {'L': 13.666666666666668},
 'L26': {'L': 13.833333333333334},
 'L27': {'L': 13.833333333333334},
 'L28': {'L': 13.666666666666668},
 'L29': {'L': 13.833333333333334},
 'M01': {'M': 7.833333333333334},
 'M04': {'M': 7.833333333333334},
 'M05': {'M': 7.833333333333334},
 'M06': {'M': 8.0},
 'M08': {'M': 7.833333333333334},
 'M09': {'M': 8.0},
 'M10': {'M': 7.833333333333334},
 'M11': {'J': 8.0, 'M': 8.0},
 'M12': {'J': 4.5, 'M': 8.0},
 'M13': {'M': 7.666666666666667, 'J': 4.5},
 'M14': {'J': 4.5, 'M': 7.833333333333334},
 'M16': {'J': 7.833333333333334, 'M': 7.833333333333334},
 'M18': {'J': 8.0, 'M': 7.833333333333334},
 'M19': {'J': 7.666666666666667},
 'M20': {'J': 8.0},
 'M21': {'J': 8.0},
 'M22': {'J': 8.0},
 'M23': {'J': 8.0},
 'N02': {'N': 7.833333333333334},
 'N03': {'N': 7.666666666666666},
 'N04': {'N': 7.833333333333334},
 'N05': {'N': 7.833333333333334},
 'N06': {'N': 7.833333333333334},
 'N07': {'N': 7.666666666666667},
 'N08': {'N': 7.666666666666666},
 'N09': {'N': 7.666666666666666},
 'N10': {'N': 7.5},
 'Q01': {'N': 7.666666666666666, 'Q': 7.833333333333334},
 'Q03': {'Q': 7.833333333333334},
 'Q04': {'Q': 8.0},
 'Q05': {'Q': 8.0},
 'R01': {'N': 7.666666666666667, 'W': 6.333333333333333},
 'R03': {'N': 7.666666666666667, 'W': 6.333333333333333},
 'R04': {'N': 7.666666666666667, 'W': 6.333333333333333},
 'R05': {'N': 8.0, 'W': 6.166666666666666},
 'R06': {'W': 6.166666666666666, 'N': 8.0},
 'R08': {'N': 7.666666666666667, 'W': 6.333333333333333},
 'R09': {'N': 7.666666666666667, 'W': 6.333333333333333},
 'R11': {'N': 7.833333333333334, 'R': 8.0, 'W': 6.333333333333333},
 'R13': {'N': 7.833333333333334,
  'R': 7.833333333333334,
  'W': 6.333333333333333},
 'R14': {'W': 6.5,
  'R': 7.833333333333334,
  'N': 7.833333333333334,
  'Q': 8.166666666666668},
 'R15': {'N': 7.833333333333334, 'R': 8.0, 'W': 6.333333333333333},
 'R16': {'W': 6.333333333333333,
  'N': 7.833333333333334,
  'Q': 8.166666666666668,
  'R': 8.0},
 'R17': {'W': 6.333333333333333, 'R': 8.0, 'Q': 8.0, 'N': 7.833333333333334},
 'R18': {'R': 7.666666666666667, 'W': 6.333333333333333},
 'R19': {'R': 7.833333333333334, 'W': 6.333333333333333},
 'R20': {'N': 8.0, 'Q': 7.833333333333334, 'R': 8.0, 'W': 6.166666666666666},
 'R21': {'W': 6.333333333333333, 'R': 8.0},
 'R22': {'R': 8.0, 'W': 6.333333333333333},
 'R23': {'R': 8.0, 'W': 6.333333333333333},
 'R24': {'R': 8.0, 'W': 6.333333333333333},
 'R25': {'R': 8.0, 'W': 6.333333333333333},
 'R26': {'W': 6.333333333333333, 'R': 8.0},
 'R27': {'W': 6.333333333333333, 'R': 7.833333333333334},
 'R28': {'R': 8.0},
 'R29': {'R': 7.833333333333334},
 'R30': {'B': 7.666666666666667, 'Q': 8.166666666666668, 'R': 8.0},
 'R31': {'D': 8.0, 'N': 7.666666666666666, 'R': 8.0},
 'R32': {'R': 7.833333333333334},
 'R33': {'R': 7.833333333333334},
 'R34': {'R': 7.833333333333334},
 'R35': {'R': 7.833333333333334},
 'R36': {'D': 8.0, 'N': 7.666666666666666, 'R': 8.0},
 'R39': {'R': 8.0},
 'R40': {'R': 7.833333333333334},
 'R41': {'N': 7.833333333333334, 'R': 7.833333333333334},
 'R42': {'R': 8.0},
 'R43': {'R': 8.0},
 'R44': {'R': 8.0},
 'R45': {'R': 7.833333333333334},
 'S01': {'FS': 6.333333333333333},
 'S03': {'FS': 6.333333333333333},
 'S04': {'FS': 6.333333333333333}}

In [ ]:
aggdict = {l: lambda n: np.nanmean(n) for l in lines}

In [ ]:
full_grid = full_grid.reset_index().drop('dir',axis=1).groupby('stop').agg(aggdict)
full_grid.to_csv('full_grid_node_delays.csv')

In [ ]:
tph_grid = full_grid.copy()
tph_grid = tph_grid.map(lambda a: 0.0)

In [ ]:
tph_grid = full_grid.copy()
tph_grid = tph_grid.map(lambda a: 0.0)
for stop,tphdata in tphdict.items():
	for line, tph in tphdata.items():
		tph_grid.loc[stop, line] = tph

In [ ]:
tph_grid.to_csv('data/tph_grid.csv')

## get rush hour

In [ ]:
def rush_tph():
	expected_trips = pd.read_csv('gtfs_subway/trips.txt')
	expected_times = pd.read_csv('gtfs_subway/stop_times.txt')
	expected_trips = expected_trips[expected_trips.service_id == 'Weekday']
	expected_trips = expected_trips[expected_trips.route_id != 'SI']
	expected_times = expected_times[expected_times.trip_id.isin(expected_trips.trip_id)]
	routedict = dict(zip(expected_trips.trip_id, expected_trips.route_id))
	dirdict = dict(zip(expected_trips.trip_id, expected_trips.direction_id))
	expected_times['dir'] = expected_times.trip_id.map(lambda id: dirdict.get(id))
	expected_times['route_id'] = expected_times.trip_id.map(lambda id: routedict.get(id))
	expected_times['hour'] = expected_times.arrival_time.map(lambda h: float(h[:4].replace(':','.')))
	expected_times_morning = expected_times[expected_times.hour.between(6,7,'both')]
	expected_times_evening = expected_times[expected_times.hour.between(17,18,'both')]
	expected_times = pd.concat([expected_times_morning, expected_times_evening])
	tph = expected_times.copy()[['stop_id','dir','route_id']]
	tph.dir = tph.dir.map(lambda d: "NS"[d])
	tph = tph.groupby(['stop_id','dir']).agg({'route_id':lambda w: w.to_list()})

	tph['tph'] = tph.route_id.map(lambda w: (pd.value_counts(w)/2).to_dict()).values
	tphavg = tph.drop('route_id', axis=1)
	tphavg['route'] = tph.tph.map(lambda w: list(w.keys()))
	tphavg['tphs'] = tph.tph.map(lambda w: list(w.values()))
	tphavg.drop('tph',axis=1,inplace=True)
	tphavg = tphavg.reset_index().explode(['route','tphs'])
	tphavg.tphs = tphavg.tphs.astype(float)
	tphavg = tphavg.groupby(['stop_id','route']).agg({'tphs':'mean'})
	tphavg.reset_index(inplace=True)
	tphavg.stop_id = tphavg.stop_id.astype(str)
	tphavg = tphavg.sort_values('stop_id').groupby('stop_id').agg(lambda x: x.to_list())
	tphavg.reset_index(inplace=True)
	tphdict = dict(zip(tphavg.stop_id, [dict(zip(a,b)) for a,b in zip(tphavg.route, tphavg.tphs)]))
	return tphdict

In [ ]:
rush_tph()

{'101': {'1': 11.5},
 '103': {'1': 12.0},
 '104': {'1': 12.5},
 '106': {'1': 12.0},
 '107': {'1': 12.5},
 '108': {'1': 12.75},
 '109': {'1': 12.0},
 '110': {'1': 12.0},
 '111': {'1': 12.5},
 '112': {'1': 12.0},
 '113': {'1': 12.5},
 '114': {'1': 12.0},
 '115': {'1': 12.75},
 '116': {'1': 12.5},
 '117': {'1': 12.5},
 '118': {'1': 12.75},
 '119': {'1': 12.25},
 '120': {'1': 13.0, '2': 9.5, '3': 7.5},
 '121': {'1': 12.5, '2': 0.5},
 '122': {'1': 12.25, '2': 0.5},
 '123': {'2': 9.5, '3': 7.5, '1': 12.5},
 '124': {'1': 12.25},
 '125': {'1': 12.5},
 '126': {'1': 12.75},
 '127': {'1': 12.5, '2': 9.0, '3': 7.5},
 '128': {'1': 12.75, '2': 9.25, '3': 7.25},
 '129': {'1': 13.0},
 '130': {'1': 13.0},
 '131': {'1': 12.5},
 '132': {'3': 7.5, '1': 12.75, '2': 9.25},
 '133': {'1': 12.75},
 '134': {'1': 12.5},
 '135': {'1': 13.0},
 '136': {'1': 13.0},
 '137': {'1': 12.5, '2': 9.25, '3': 7.25},
 '138': {'1': 12.75},
 '139': {'1': 13.25},
 '142': {'1': 12.75},
 '201': {'2': 8.5},
 '204': {'5': 2.5, '2': 9.0},
 '205': {'5': 2.75, '2': 9.25},
 '206': {'2': 9.25, '5': 2.5},
 '207': {'5': 2.5, '2': 9.25},
 '208': {'5': 2.5, '2': 9.0},
 '209': {'5': 2.5, '2': 8.75},
 '210': {'5': 2.5, '2': 8.75},
 '211': {'5': 2.5, '2': 9.25},
 '212': {'5': 2.5, '2': 9.75},
 '213': {'5': 9.0, '2': 9.0},
 '214': {'5': 2.5, '2': 9.0},
 '215': {'2': 9.5, '5': 2.5},
 '216': {'5': 2.75, '2': 9.0},
 '217': {'2': 9.25, '5': 3.25},
 '218': {'5': 3.0, '2': 9.0},
 '219': {'2': 9.0, '5': 3.0},
 '220': {'2': 9.5, '5': 3.0},
 '221': {'2': 9.25, '5': 9.0},
 '222': {'5': 9.0, '2': 9.75},
 '224': {'3': 8.0, '2': 9.0},
 '225': {'3': 7.75, '2': 9.25},
 '226': {'2': 9.25, '3': 7.75},
 '227': {'3': 7.5, '2': 9.25},
 '228': {'3': 7.5, '2': 9.25},
 '229': {'2': 9.0, '3': 7.75},
 '230': {'3': 7.5, '2': 9.0},
 '231': {'3': 7.75, '2': 9.0},
 '232': {'2': 9.0, '3': 7.5},
 '233': {'3': 7.25, '2': 9.0},
 '234': {'4': 3.75, '5': 9.25, '2': 9.0, '3': 7.5},
 '235': {'3': 7.25, '2': 9.0, '4': 3.75, '5': 9.25},
 '236': {'4': 0.5, '2': 9.0, '3': 7.75},
 '237': {'2': 8.75, '3': 7.5, '4': 0.5},
 '238': {'2': 8.75, '3': 7.75, '4': 0.5},
 '239': {'5': 9.5, '4': 3.75, '2': 8.75, '3': 7.25},
 '241': {'5': 7.5, '2': 8.25},
 '242': {'2': 8.25, '5': 7.75},
 '243': {'2': 8.5, '5': 7.75},
 '244': {'2': 9.0, '5': 7.5},
 '245': {'2': 8.5, '5': 7.75},
 '246': {'2': 8.5, '5': 7.5},
 '247': {'5': 7.5, '2': 8.5},
 '248': {'4': 0.5, '3': 7.5, '2': 1.0, '5': 0.5},
 '249': {'4': 0.5, '2': 1.0, '5': 0.5, '3': 7.75},
 '250': {'4': 3.75, '5': 1.25, '2': 0.5, '3': 7.25},
 '251': {'3': 7.25, '4': 0.5, '2': 0.5},
 '252': {'4': 0.5, '3': 7.25, '2': 0.5},
 '253': {'2': 0.5, '3': 7.75, '4': 0.5},
 '254': {'4': 0.75, '2': 0.5, '3': 7.75},
 '255': {'2': 0.5, '4': 0.75, '3': 7.5},
 '256': {'2': 0.5, '4': 0.75, '3': 7.5},
 '257': {'2': 0.5, '3': 7.25, '4': 0.75},
 '301': {'3': 7.0},
 '302': {'3': 7.25},
 '401': {'4': 5.0},
 '402': {'4': 4.75},
 '405': {'4': 5.0},
 '406': {'4': 5.5},
 '407': {'4': 5.75},
 '408': {'4': 5.5},
 '409': {'4': 5.75},
 '410': {'4': 6.0},
 '411': {'4': 6.0},
 '412': {'4': 5.25},
 '413': {'4': 5.5},
 '414': {'4': 6.0},
 '415': {'4': 6.25},
 '416': {'4': 6.5, '5': 8.75},
 '418': {'5': 10.25, '4': 7.0},
 '419': {'4': 4.25, '5': 10.5},
 '420': {'4': 7.0, '5': 10.5},
 '423': {'4': 7.5, '5': 9.75},
 '501': {'5': 6.75},
 '502': {'5': 6.5},
 '503': {'5': 6.75},
 '504': {'5': 6.75},
 '505': {'5': 6.75},
 '601': {'6X': 5.0, '6': 3.75},
 '602': {'6X': 4.75, '6': 4.0},
 '603': {'6X': 4.75, '6': 4.0},
 '604': {'6': 4.0, '6X': 4.75},
 '606': {'6': 4.25, '6X': 4.75},
 '607': {'6': 4.5, '6X': 4.5},
 '608': {'6X': 4.5, '6': 10.75},
 '609': {'6': 10.75},
 '610': {'6': 10.5},
 '611': {'6': 10.75},
 '612': {'6': 11.0},
 '613': {'6': 11.0, '6X': 4.5},
 '614': {'6': 11.0},
 '615': {'6': 11.0},
 '616': {'6': 11.25},
 '617': {'6': 11.5},
 '618': {'6': 11.25},
 '619': {'6': 11.0, '6X': 4.25},
 '621': {'5': 9.0, '6': 11.25, '6X': 4.25, '4': 4.75},
 '622': {'6X': 4.25, '6': 11.25},
 '623': {'6': 11.5, '6X': 4.0},
 '624': {'6': 11.25, '6X': 4.0},
 '625': {'6': 11.5, '6X': 4.25},
 '626': {'6': 11.0, '4': 6.25, '5': 9.75, '6X': 4.0},
 '627': {'6': 11.5, '6X': 4.0},
 '628': {'6': 11.25, '6X': 3.75},
 '629': {'6X': 4.0, '4': 6.75, '6': 11.75, '5': 9.75},
 '630': {'6': 11.5, '6X': 3.75},
 '631': {'4': 6.75, '5': 10.0, '6': 12.0, '6X': 3.75},
 '632': {'6': 11.5, '6X': 3.75},
 '633': {'6': 12.0, '6X': 3.75},
 '634': {'6': 11.75, '6X': 3.5},
 '635': {'6X': 3.5, '6': 11.75, '5': 9.5, '4': 7.25},
 '636': {'6': 11.5, '6X': 3.5},
 '637': {'6': 11.75, '6X': 3.75},
 '638': {'6': 11.75, '6X': 3.5},
 '639': {'6': 12.0, '6X': 3.5},
 '640': {'6X': 3.5, '5': 10.25, '4': 7.25, '6': 12.25},
 '701': {'7': 13.75, '7X': 6.0},
 '702': {'7': 14.75, '7X': 5.75},
 '705': {'7': 17.0},
 '706': {'7': 16.75},
 '707': {'7': 17.5, '7X': 6.0},
 '708': {'7': 17.5},
 '709': {'7': 17.5},
 '710': {'7X': 6.5, '7': 18.0},
 '711': {'7': 14.5, '7X': 7.0},
 '712': {'7': 18.5, '7X': 5.5},
 '713': {'7': 15.0, '7X': 7.5},
 '714': {'7': 18.5, '7X': 5.25},
 '715': {'7': 19.0, '7X': 5.25},
 '716': {'7X': 5.25, '7': 18.75},
 '718': {'7': 19.25, '7X': 5.25},
 '719': {'7': 19.5, '7X': 5.0},
 '720': {'7': 19.5, '7X': 5.25},
 '721': {'7': 19.25, '7X': 5.25},
 '723': {'7': 19.5, '7X': 5.0},
 '724': {'7X': 4.75, '7': 19.75},
 '725': {'7': 20.0, '7X': 4.5},
 '726': {'7': 19.75, '7X': 4.5},
 '901': {'GS': 17.75},
 '902': {'GS': 17.75},
 'A02': {'A': 9.5},
 'A03': {'A': 10.25},
 'A05': {'A': 10.0},
 'A06': {'A': 10.0},
 'A07': {'A': 10.25},
 'A09': {'A': 10.5, 'C': 5.5},
 'A10': {'C': 5.75, 'A': 1.5},
 'A11': {'A': 1.5, 'C': 6.0},
 'A12': {'A': 10.25, 'C': 6.0},
 'A14': {'A': 1.25, 'B': 6.5, 'C': 5.5},
 'A15': {'A': 10.5, 'B': 6.75, 'C': 5.25, 'D': 8.0},
 'A16': {'C': 5.5, 'A': 1.5, 'B': 6.75},
 'A17': {'C': 5.75, 'B': 6.75, 'A': 1.5},
 'A18': {'A': 1.5, 'B': 6.75, 'C': 5.75},
 'A19': {'A': 1.0, 'B': 7.25, 'C': 6.0},
 'A20': {'A': 1.0, 'B': 6.75, 'C': 6.0},
 'A21': {'A': 1.0, 'B': 7.0, 'C': 5.75},
 'A22': {'C': 6.0, 'B': 7.0, 'A': 1.0},
 'A24': {'A': 10.5, 'B': 6.75, 'C': 6.0, 'D': 8.0},
 'A25': {'A': 1.0, 'C': 6.25, 'E': 11.75},
 'A27': {'A': 10.75, 'C': 6.25, 'E': 12.0},
 'A28': {'A': 10.75, 'C': 6.0, 'E': 12.0},
 'A30': {'E': 12.0, 'A': 1.0, 'C': 6.25},
 'A31': {'A': 10.75, 'C': 6.25, 'E': 12.0},
 'A32': {'A': 10.5, 'C': 6.25, 'E': 12.25},
 'A33': {'A': 0.5, 'C': 6.5, 'E': 12.0},
 'A34': {'A': 10.5, 'C': 6.5, 'E': 11.75},
 'A36': {'C': 6.5, 'A': 10.5},
 'A38': {'A': 10.75, 'C': 6.5},
 'A40': {'A': 10.5, 'C': 6.5},
 'A41': {'A': 10.5, 'C': 6.75, 'F': 11.0, 'FX': 1.0},
 'A42': {'A': 10.5, 'C': 6.5, 'G': 8.0},
 'A43': {'C': 6.75},
 'A44': {'C': 6.5},
 'A45': {'C': 6.25, 'A': 0.5},
 'A46': {'A': 10.25, 'C': 6.5},
 'A47': {'A': 0.5, 'C': 6.75},
 'A48': {'A': 10.75, 'C': 7.0},
 'A49': {'A': 0.5, 'C': 6.75},
 'A50': {'A': 0.5, 'C': 6.5},
 'A51': {'A': 10.25, 'C': 6.5},
 'A52': {'C': 6.5, 'A': 0.5},
 'A53': {'A': 1.0, 'C': 6.5},
 'A54': {'A': 1.0, 'C': 6.5},
 'A55': {'A': 11.25, 'C': 6.5},
 'A57': {'A': 11.5},
 'A59': {'A': 11.25},
 'A60': {'A': 11.0},
 'A61': {'A': 11.0},
 'A63': {'A': 4.75},
 'A64': {'A': 5.0},
 'A65': {'A': 5.0},
 'B04': {'F': 11.75, 'FX': 0.5},
 'B06': {'FX': 0.5, 'F': 11.5},
 'B08': {'F': 11.5, 'FX': 0.5, 'N': 0.75, 'Q': 8.5},
 'B10': {'F': 11.25, 'FX': 0.5},
 'B12': {'D': 7.75},
 'B13': {'D': 7.75},
 'B14': {'D': 8.25},
 'B15': {'D': 8.25},
 'B16': {'D': 7.75},
 'B17': {'D': 8.25},
 'B18': {'D': 8.0},
 'B19': {'D': 7.75},
 'B20': {'D': 7.75},
 'B21': {'D': 7.75},
 'B22': {'D': 7.75},
 'B23': {'D': 7.75},
 'D01': {'D': 7.0},
 'D03': {'B': 5.75, 'D': 7.75},
 'D04': {'B': 5.75, 'D': 7.25},
 'D05': {'B': 6.0, 'D': 7.25},
 'D06': {'B': 6.0, 'D': 3.75},
 'D07': {'B': 6.25, 'D': 7.5},
 'D08': {'D': 3.25, 'B': 6.25},
 'D09': {'B': 6.5, 'D': 3.75},
 'D10': {'B': 6.0, 'D': 4.0},
 'D11': {'B': 6.75, 'D': 4.0},
 'D12': {'B': 6.5, 'D': 3.75},
 'D13': {'B': 6.75, 'D': 7.5},
 'D14': {'B': 6.5, 'D': 7.75, 'E': 12.25},
 'D15': {'M': 7.25, 'FX': 1.0, 'D': 8.0, 'B': 7.0, 'F': 11.5},
 'D16': {'B': 7.0, 'D': 8.25, 'F': 11.5, 'FX': 1.0, 'M': 7.5},
 'D17': {'M': 7.5, 'B': 7.0, 'D': 8.0, 'F': 11.0, 'FX': 1.0},
 'D18': {'M': 7.5, 'F': 11.25, 'FX': 1.0},
 'D19': {'F': 11.0, 'FX': 1.0, 'M': 7.25},
 'D20': {'B': 7.0, 'D': 8.5, 'F': 11.25, 'FX': 1.0, 'M': 7.25},
 'D21': {'FX': 1.0, 'F': 11.25, 'M': 7.5, 'B': 7.0, 'D': 7.75},
 'D22': {'B': 7.25, 'D': 7.75},
 'D24': {'B': 7.0, 'Q': 8.5},
 'D25': {'B': 7.25, 'Q': 8.5},
 'D26': {'B': 7.25, 'FS': 6.5, 'Q': 8.5},
 'D27': {'Q': 9.0},
 'D28': {'B': 7.25, 'Q': 8.75},
 'D29': {'Q': 8.5},
 'D30': {'Q': 8.75},
 'D31': {'Q': 8.5, 'B': 7.0},
 'D32': {'Q': 8.5},
 'D33': {'Q': 8.5},
 'D34': {'Q': 8.75},
 'D35': {'B': 7.0, 'Q': 8.25},
 'D37': {'Q': 8.25},
 'D38': {'Q': 8.25},
 'D39': {'B': 6.5, 'Q': 8.5},
 'D40': {'Q': 8.25, 'B': 6.5},
 'D41': {'Q': 8.5},
 'D42': {'Q': 8.75, 'F': 6.25, 'FX': 0.5},
 'D43': {'D': 7.75, 'F': 6.25, 'FX': 0.5, 'N': 6.5, 'Q': 8.5},
 'E01': {'E': 11.75},
 'F01': {'E': 0.5, 'F': 12.5},
 'F02': {'FX': 0.5, 'F': 12.0},
 'F03': {'F': 12.0, 'FX': 0.5, 'E': 1.0},
 'F04': {'FX': 0.5, 'F': 11.75},
 'F05': {'E': 2.0, 'F': 12.25, 'FX': 0.5},
 'F06': {'E': 12.5, 'F': 11.75, 'FX': 0.5},
 'F07': {'E': 2.0, 'F': 12.25, 'FX': 0.5},
 'F09': {'E': 12.0, 'M': 7.75},
 'F11': {'E': 12.0, 'M': 7.25},
 'F12': {'M': 7.25, 'E': 11.75},
 'F14': {'F': 11.25, 'FX': 1.0},
 'F15': {'F': 11.0, 'FX': 1.0},
 'F16': {'F': 10.75, 'FX': 1.0},
 'F18': {'F': 11.0, 'FX': 1.0},
 'F20': {'F': 10.75, 'G': 8.25},
 'F21': {'F': 11.0, 'G': 8.0},
 'F22': {'G': 7.75, 'F': 11.0},
 'F23': {'G': 8.5, 'F': 10.5},
 'F24': {'F': 10.75, 'FX': 1.0, 'G': 8.25},
 'F25': {'F': 10.5, 'G': 8.0},
 'F26': {'F': 10.5, 'G': 8.0},
 'F27': {'F': 10.5, 'FX': 1.0, 'G': 7.75},
 'F29': {'F': 10.25, 'FX': 1.0},
 'F30': {'F': 11.0, 'FX': 1.0},
 'F31': {'FX': 0.5, 'F': 10.75},
 'F32': {'F': 10.5, 'FX': 0.5},
 'F33': {'F': 10.75, 'FX': 0.5},
 'F34': {'F': 10.75, 'FX': 0.5},
 'F35': {'F': 10.75, 'FX': 0.5},
 'F36': {'F': 7.25, 'FX': 0.5},
 'F38': {'F': 7.5, 'FX': 0.5},
 'F39': {'FX': 0.5, 'F': 6.0},
 'G05': {'E': 11.75, 'J': 7.25, 'Z': 1.5},
 'G06': {'E': 12.25, 'J': 7.25, 'Z': 1.5},
 'G07': {'E': 11.75},
 'G08': {'E': 12.25, 'F': 12.0, 'FX': 0.5, 'M': 7.25, 'R': 8.0},
 'G09': {'R': 8.25, 'M': 7.0, 'E': 1.0, 'F': 1.0},
 'G10': {'E': 1.0, 'F': 1.0, 'M': 7.5, 'R': 8.0},
 'G11': {'E': 1.0, 'F': 0.5, 'M': 7.5, 'R': 8.0},
 'G12': {'E': 1.0, 'F': 0.5, 'M': 7.25, 'R': 8.0},
 'G13': {'R': 8.0, 'M': 7.25, 'E': 0.5, 'F': 0.5},
 'G14': {'E': 12.25, 'F': 12.0, 'FX': 0.5, 'M': 7.5, 'R': 8.0},
 'G15': {'E': 0.5, 'F': 0.5, 'M': 7.5, 'R': 8.0},
 'G16': {'R': 8.0, 'M': 7.5, 'F': 0.5, 'E': 0.5},
 'G18': {'E': 0.5, 'F': 0.5, 'M': 7.25, 'R': 8.25},
 'G19': {'E': 0.5, 'F': 0.5, 'M': 7.75, 'R': 8.25},
 'G20': {'M': 7.75, 'R': 8.25, 'E': 0.5, 'F': 0.5},
 'G21': {'R': 8.5, 'E': 11.75, 'M': 7.75},
 'G22': {'G': 8.25},
 'G24': {'G': 8.5},
 'G26': {'G': 8.0},
 'G28': {'G': 8.25},
 'G29': {'G': 8.0},
 'G30': {'G': 7.75},
 'G31': {'G': 8.0},
 'G32': {'G': 8.25},
 'G33': {'G': 8.5},
 'G34': {'G': 8.25},
 'G35': {'G': 7.75},
 'G36': {'G': 7.75},
 'H01': {'A': 4.5},
 'H02': {'A': 6.0},
 'H03': {'A': 6.0},
 'H04': {'A': 6.25, 'H': 3.75},
 'H06': {'A': 5.0},
 'H07': {'A': 4.75},
 'H08': {'A': 4.75},
 'H09': {'A': 4.5},
 'H10': {'A': 4.5},
 'H11': {'A': 4.75},
 'H12': {'A': 1.25, 'H': 3.25},
 'H13': {'A': 1.25, 'H': 3.25},
 'H14': {'H': 3.5, 'A': 1.25},
 'H15': {'A': 1.25, 'H': 3.5},
 'J12': {'J': 6.25, 'Z': 1.5},
 'J13': {'J': 7.25},
 'J14': {'J': 6.5, 'Z': 2.0},
 'J15': {'J': 7.25, 'Z': 2.0},
 'J16': {'J': 7.5},
 'J17': {'J': 6.25, 'Z': 2.0},
 'J19': {'J': 7.25},
 'J20': {'Z': 2.0, 'J': 7.25},
 'J21': {'J': 6.5, 'Z': 2.5},
 'J22': {'J': 7.25},
 'J23': {'J': 6.5, 'Z': 2.5},
 'J24': {'J': 7.5, 'Z': 2.5},
 'J27': {'J': 7.75, 'Z': 2.5},
 'J28': {'J': 6.0, 'Z': 2.5},
 'J29': {'J': 7.0},
 'J30': {'Z': 2.5, 'J': 5.5},
 'J31': {'J': 6.75},
 'L01': {'L': 15.25},
 'L02': {'L': 15.25},
 'L03': {'L': 15.25},
 'L05': {'L': 15.0},
 'L06': {'L': 15.5},
 'L08': {'L': 15.5},
 'L10': {'L': 15.25},
 'L11': {'L': 15.0},
 'L12': {'L': 15.5},
 'L13': {'L': 15.25},
 'L14': {'L': 14.75},
 'L15': {'L': 15.5},
 'L16': {'L': 15.0},
 'L17': {'L': 15.0},
 'L19': {'L': 15.0},
 'L20': {'L': 15.25},
 'L21': {'L': 15.0},
 'L22': {'L': 15.0},
 'L24': {'L': 15.0},
 'L25': {'L': 15.5},
 'L26': {'L': 15.25},
 'L27': {'L': 15.25},
 'L28': {'L': 15.0},
 'L29': {'L': 13.0},
 'M01': {'M': 7.25},
 'M04': {'M': 7.25},
 'M05': {'M': 7.75},
 'M06': {'M': 7.75},
 'M08': {'M': 7.25},
 'M09': {'M': 7.25},
 'M10': {'M': 7.25},
 'M11': {'J': 6.75, 'M': 7.75, 'Z': 3.0},
 'M12': {'J': 4.75, 'M': 7.75},
 'M13': {'J': 5.0, 'M': 7.25},
 'M14': {'J': 5.0, 'M': 7.25},
 'M16': {'Z': 3.0, 'M': 7.5, 'J': 7.25},
 'M18': {'J': 7.0, 'M': 7.25, 'Z': 3.0},
 'M19': {'J': 7.25, 'Z': 3.0},
 'M20': {'J': 7.5, 'Z': 3.0},
 'M21': {'J': 7.0, 'Z': 2.5},
 'M22': {'J': 7.25, 'Z': 2.5},
 'M23': {'J': 7.5, 'Z': 2.5},
 'N02': {'N': 7.75},
 'N03': {'N': 7.75},
 'N04': {'N': 8.25},
 'N05': {'N': 8.0, 'W': 0.5},
 'N06': {'N': 8.0, 'W': 0.5},
 'N07': {'N': 8.0, 'W': 0.5},
 'N08': {'N': 7.5, 'W': 0.5},
 'N09': {'N': 8.25, 'W': 0.5},
 'N10': {'N': 7.75, 'W': 0.5},
 'Q01': {'Q': 8.5, 'N': 8.25},
 'Q03': {'N': 0.5, 'Q': 8.75},
 'Q04': {'N': 0.5, 'Q': 8.75},
 'Q05': {'N': 0.5, 'Q': 8.75},
 'R01': {'N': 7.25, 'W': 5.0},
 'R03': {'N': 7.75, 'W': 5.0},
 'R04': {'N': 7.25, 'W': 5.0},
 'R05': {'N': 7.5, 'W': 5.0},
 'R06': {'W': 4.75, 'N': 7.5},
 'R08': {'N': 7.5, 'W': 4.75},
 'R09': {'N': 7.75, 'W': 4.5},
 'R11': {'N': 7.5, 'R': 8.5, 'W': 4.75},
 'R13': {'N': 7.5, 'R': 8.75, 'W': 4.75},
 'R14': {'W': 4.75, 'R': 8.5, 'N': 8.25, 'Q': 8.5},
 'R15': {'N': 7.5, 'Q': 0.5, 'R': 9.25, 'W': 4.25},
 'R16': {'N': 8.25, 'Q': 8.25, 'R': 9.0, 'W': 4.5},
 'R17': {'R': 9.0, 'N': 8.25, 'Q': 8.5, 'W': 4.5},
 'R18': {'W': 4.5, 'R': 9.0},
 'R19': {'W': 4.5, 'R': 8.75},
 'R20': {'N': 8.0, 'Q': 8.75, 'R': 8.75, 'W': 4.25},
 'R21': {'R': 9.0, 'W': 4.5},
 'R22': {'R': 8.5, 'W': 4.25},
 'R23': {'R': 8.5, 'W': 4.25},
 'R24': {'R': 8.5, 'W': 4.25},
 'R25': {'R': 8.0, 'W': 4.5},
 'R26': {'W': 4.5, 'R': 8.5},
 'R27': {'R': 8.75, 'W': 4.25},
 'R28': {'R': 8.25, 'W': 0.5},
 'R29': {'R': 8.25, 'W': 0.5},
 'R30': {'B': 7.0, 'D': 1.5, 'N': 1.5, 'Q': 8.75, 'R': 8.5, 'W': 0.5},
 'R31': {'W': 0.5, 'R': 8.25, 'D': 8.0, 'N': 7.75},
 'R32': {'D': 1.5, 'N': 1.75, 'R': 8.25, 'W': 0.5},
 'R33': {'D': 1.5, 'N': 1.75, 'R': 8.25},
 'R34': {'D': 1.5, 'N': 1.75, 'R': 8.5},
 'R35': {'N': 1.75, 'R': 8.25, 'D': 1.5},
 'R36': {'D': 8.25, 'N': 8.0, 'R': 8.5},
 'R39': {'N': 3.0, 'R': 8.25},
 'R40': {'N': 2.5, 'R': 8.25},
 'R41': {'N': 8.0, 'R': 8.75},
 'R42': {'R': 9.0},
 'R43': {'R': 8.75},
 'R44': {'R': 8.25},
 'R45': {'R': 8.5},
 'S01': {'FS': 6.5},
 'S03': {'FS': 6.5},
 'S04': {'FS': 6.5}}

In [ ]:
rush_tph_grid = full_grid.copy().map(lambda a: 0.0)
for stop,tphdata in rush_tph().items():
	for line, tph in tphdata.items():
		rush_tph_grid.loc[stop, line] = tph

In [ ]:
rush_tph_grid.to_csv('data/rush_tph.csv')

In [ ]:
def rush_deltas_morning(day):
	mtatime = [6*60*100, 7*60*100]
	expected_trips = pd.read_csv('gtfs_subway/trips.txt')
	actual_trips = pd.read_csv(f"sept27data/subwaydatanyc_2025-09-{day}_trips.csv")

	expected_times = pd.read_csv('gtfs_subway/stop_times.txt')
	actual_times = pd.read_csv(f"sept27data/subwaydatanyc_2025-09-{day}_stop_times.csv")

	def format_time(t):
		'''Helper to format MTA timestamps that go over 24 hours due to delays'''
		rd = [int(n) for n in t.split(':')]
		d = 0
		if rd[0] >= 24:
			rd[0] = rd[0] % 24
			d = 1
		s = ':'.join([str(k) for k in rd])
		datestr = datetime.strptime(f"9/{day+d}/2025 {s}", "%m/%d/%Y %H:%M:%S")
		return datestr


	actual_trips['init_time'] = actual_trips.trip_id.map(lambda s: int(s.split('_')[0]))
	actual_trips = actual_trips[actual_trips.init_time.between(mtatime[0],mtatime[1])]
	actual_trips = actual_trips[actual_trips.route_id != 'SI']
	actual_trips.sort_values('init_time', inplace=True)
	actual_trips['short_id'] = actual_trips.trip_id.map(lambda s: ''.join(re.split(r"(\.{1,2}[SN])",s)[:-1]))
	expected_trips = expected_trips[~expected_trips.route_id.isin(['SI','SS'])]
	expected_trips = expected_trips[expected_trips.service_id == 'Weekday']
	expected_trips['short_id'] = expected_trips.trip_id.map(lambda s: '_'.join(s.split('_')[-2:]))
	expected_trips['init_time'] = expected_trips.trip_id.map(lambda s: int(s.split('_')[-2]))
	expected_trips = expected_trips[expected_trips.init_time.between(mtatime[0],mtatime[1])]
	expected_trips.short_id = expected_trips.short_id.map(lambda s: s[:-3])
	expected_trips = expected_trips.astype(str)
	expected_trips = expected_trips[['route_id','short_id', 'trip_id']]
	expected_trips.columns = ['route_id', 'short_id', 'full_trip_id']
	actual_trips = actual_trips[['trip_uid','route_id','trip_id','direction_id','start_time','short_id','init_time']]
	merged = pd.merge(actual_trips, expected_trips, on='short_id')
	merged['unique'] = merged.trip_id.map(lambda s: merged.trip_id.value_counts(sort=False).to_dict()[s])
	merged['route_id'] = list(zip(merged['route_id_x'], merged['route_id_y']))
	merged.route_id = merged.route_id.map(lambda x: x[0] if len(np.unique_values(list(x)))==1 else x)
	idkey = {v: k for k,v in zip(merged.trip_uid, merged.full_trip_id)}
	expected_times = expected_times[~expected_times.trip_id.str.startswith('SIR-')]
	expected_times['id_key'] =expected_times.trip_id.map(lambda s: '_'.join(s.split('-')[-1].split('_')[1:]))
	expected_times['key'] = expected_times.trip_id.map(lambda k: idkey.get(k))+expected_times.stop_id.astype(str)
	expected_times = expected_times[~expected_times.key.isna()]
	expected_times.sort_values('key')
	expected_times.columns = ['full_trip_id', 'stop_id','expected_arrival','departure','seq','short_id','key']
	real_time = actual_times.copy()
	real_time = real_time[real_time['trip_uid'].isin(merged.trip_uid)]
	real_time.stop_id = real_time.stop_id.map(lambda a: str(a[:-1]))
	real_time = real_time[~(real_time.arrival_time.isna() & real_time.departure_time.isna())]
	real_time['key'] = [a+b for a,b in zip(real_time.trip_uid, real_time.stop_id)]
	real_time.arrival_time = [int(a[np.nanargmax(a)]) for a in zip(real_time.arrival_time, real_time.departure_time)]
	real_time['init_time'] = real_time.trip_uid.map(lambda s: int(s.split('_')[0]))
	real_time.arrival_time = real_time.arrival_time.map(lambda t: datetime.fromtimestamp(t).time())
	real_time.sort_values('key')
	ddict = dict(zip(expected_trips.full_trip_id.values,expected_trips.short_id.map(lambda n: n[-1])))
	iddict = dict(zip(expected_trips.full_trip_id, expected_trips.route_id))
	expected_times['route'] = expected_times.full_trip_id.map(lambda x: iddict.get(x))
	expected_times['direction'] = expected_times.full_trip_id.map(lambda x: ddict.get(x))
	full_merge =pd.merge(real_time, expected_times, on='key')
	full_merge = full_merge[full_merge.expected_arrival.notna()]
	full_merge = full_merge[['stop_id_x','arrival_time','expected_arrival','seq', 'route','direction']]
	full_merge.drop('seq', axis=1,inplace=True)
	full_merge['delta']=[(format_time(a)-format_time(b)).total_seconds() for a,b in zip(full_merge.arrival_time.astype(str), full_merge.expected_arrival.astype(str))]
	deltas = full_merge[['stop_id_x','route','direction','delta']]
	return deltas

In [ ]:
def rush_deltas_evening(day):
	mtatime = [17*60*100, 18*60*100]
	expected_trips = pd.read_csv('gtfs_subway/trips.txt')
	actual_trips = pd.read_csv(f"sept27data/subwaydatanyc_2025-09-{day}_trips.csv")

	expected_times = pd.read_csv('gtfs_subway/stop_times.txt')
	actual_times = pd.read_csv(f"sept27data/subwaydatanyc_2025-09-{day}_stop_times.csv")

	def format_time(t):
		'''Helper to format MTA timestamps that go over 24 hours due to delays'''
		rd = [int(n) for n in t.split(':')]
		d = 0
		if rd[0] >= 24:
			rd[0] = rd[0] % 24
			d = 1
		s = ':'.join([str(k) for k in rd])
		datestr = datetime.strptime(f"9/{day+d}/2025 {s}", "%m/%d/%Y %H:%M:%S")
		return datestr


	actual_trips['init_time'] = actual_trips.trip_id.map(lambda s: int(s.split('_')[0]))
	actual_trips = actual_trips[actual_trips.init_time.between(mtatime[0],mtatime[1])]
	actual_trips = actual_trips[actual_trips.route_id != 'SI']
	actual_trips.sort_values('init_time', inplace=True)
	actual_trips['short_id'] = actual_trips.trip_id.map(lambda s: ''.join(re.split(r"(\.{1,2}[SN])",s)[:-1]))
	expected_trips = expected_trips[~expected_trips.route_id.isin(['SI','SS'])]
	expected_trips = expected_trips[expected_trips.service_id == 'Weekday']
	expected_trips['short_id'] = expected_trips.trip_id.map(lambda s: '_'.join(s.split('_')[-2:]))
	expected_trips['init_time'] = expected_trips.trip_id.map(lambda s: int(s.split('_')[-2]))
	expected_trips = expected_trips[expected_trips.init_time.between(mtatime[0],mtatime[1])]
	expected_trips.short_id = expected_trips.short_id.map(lambda s: s[:-3])
	expected_trips = expected_trips.astype(str)
	expected_trips = expected_trips[['route_id','short_id', 'trip_id']]
	expected_trips.columns = ['route_id', 'short_id', 'full_trip_id']
	actual_trips = actual_trips[['trip_uid','route_id','trip_id','direction_id','start_time','short_id','init_time']]
	merged = pd.merge(actual_trips, expected_trips, on='short_id')
	merged['unique'] = merged.trip_id.map(lambda s: merged.trip_id.value_counts(sort=False).to_dict()[s])
	merged['route_id'] = list(zip(merged['route_id_x'], merged['route_id_y']))
	merged.route_id = merged.route_id.map(lambda x: x[0] if len(np.unique_values(list(x)))==1 else x)
	idkey = {v: k for k,v in zip(merged.trip_uid, merged.full_trip_id)}
	expected_times = expected_times[~expected_times.trip_id.str.startswith('SIR-')]
	expected_times['id_key'] =expected_times.trip_id.map(lambda s: '_'.join(s.split('-')[-1].split('_')[1:]))
	expected_times['key'] = expected_times.trip_id.map(lambda k: idkey.get(k))+expected_times.stop_id.astype(str)
	expected_times = expected_times[~expected_times.key.isna()]
	expected_times.sort_values('key')
	expected_times.columns = ['full_trip_id', 'stop_id','expected_arrival','departure','seq','short_id','key']
	real_time = actual_times.copy()
	real_time = real_time[real_time['trip_uid'].isin(merged.trip_uid)]
	real_time.stop_id = real_time.stop_id.map(lambda a: str(a[:-1]))
	real_time = real_time[~(real_time.arrival_time.isna() & real_time.departure_time.isna())]
	real_time['key'] = [a+b for a,b in zip(real_time.trip_uid, real_time.stop_id)]
	real_time.arrival_time = [int(a[np.nanargmax(a)]) for a in zip(real_time.arrival_time, real_time.departure_time)]
	real_time['init_time'] = real_time.trip_uid.map(lambda s: int(s.split('_')[0]))
	real_time.arrival_time = real_time.arrival_time.map(lambda t: datetime.fromtimestamp(t).time())
	real_time.sort_values('key')
	ddict = dict(zip(expected_trips.full_trip_id.values,expected_trips.short_id.map(lambda n: n[-1])))
	iddict = dict(zip(expected_trips.full_trip_id, expected_trips.route_id))
	expected_times['route'] = expected_times.full_trip_id.map(lambda x: iddict.get(x))
	expected_times['direction'] = expected_times.full_trip_id.map(lambda x: ddict.get(x))
	full_merge =pd.merge(real_time, expected_times, on='key')
	full_merge = full_merge[full_merge.expected_arrival.notna()]
	full_merge = full_merge[['stop_id_x','arrival_time','expected_arrival','seq', 'route','direction']]
	full_merge.drop('seq', axis=1,inplace=True)
	full_merge['delta']=[(format_time(a)-format_time(b)).total_seconds() for a,b in zip(full_merge.arrival_time.astype(str), full_merge.expected_arrival.astype(str))]
	deltas = full_merge[['stop_id_x','route','direction','delta']]
	return deltas

In [ ]:
r22 = pd.concat([rush_deltas_morning(22), rush_deltas_evening(22)])
r23 = pd.concat([rush_deltas_morning(23), rush_deltas_evening(23)])
r24 = pd.concat([rush_deltas_morning(24), rush_deltas_evening(24)])
r25 = pd.concat([rush_deltas_morning(25), rush_deltas_evening(25)])
r26 = pd.concat([rush_deltas_morning(26), rush_deltas_evening(26)])

In [ ]:
sep27rush = pd.concat([r22,r23,r24,r25,r26]).reset_index(drop=True)
sep27rush.columns = ['stop','line','dir','delta']
sep27ravg = sep27rush.groupby(["stop",'dir','line']).agg({'delta':'mean'})
deltadictr=dict(zip(sep27ravg.index.values, sep27ravg.delta))
deltadictr

{('101', 'N', '1'): 148.66326530612244,
 ('101', 'S', '1'): 0.0,
 ('103', 'N', '1'): 163.80612244897958,
 ('103', 'S', '1'): 1.4259259259259258,
 ('104', 'N', '1'): 146.16326530612244,
 ('104', 'S', '1'): -9.194444444444445,
 ('106', 'N', '1'): 146.1734693877551,
 ('106', 'S', '1'): -14.87037037037037,
 ('107', 'N', '1'): 143.8673469387755,
 ('107', 'S', '1'): -11.481481481481481,
 ('108', 'N', '1'): 152.81632653061226,
 ('108', 'S', '1'): 7.703703703703703,
 ('109', 'N', '1'): 139.87755102040816,
 ('109', 'S', '1'): 6.518518518518518,
 ('110', 'N', '1'): 142.28571428571428,
 ('110', 'S', '1'): 5.953703703703703,
 ('111', 'N', '1'): 140.9795918367347,
 ('111', 'S', '1'): 9.425925925925926,
 ('112', 'N', '1'): 143.69387755102042,
 ('112', 'S', '1'): 16.00925925925926,
 ('113', 'N', '1'): 155.69387755102042,
 ('113', 'S', '1'): 25.37037037037037,
 ('114', 'N', '1'): 158.30612244897958,
 ('114', 'S', '1'): 13.962962962962964,
 ('115', 'N', '1'): 147.57142857142858,
 ('115', 'S', '1'): 7.796296296296297,
 ('116', 'N', '1'): 151.8673469387755,
 ('116', 'S', '1'): 33.28703703703704,
 ('117', 'N', '1'): 164.0612244897959,
 ('117', 'S', '1'): 8.49074074074074,
 ('118', 'N', '1'): 142.57142857142858,
 ('118', 'S', '1'): 25.694444444444443,
 ('119', 'N', '1'): 139.5,
 ('119', 'S', '1'): 47.425925925925924,
 ('120', 'N', '1'): 116.39795918367346,
 ('120', 'N', '2'): 68.91044776119404,
 ('120', 'N', '3'): 124.40625,
 ('120', 'S', '1'): 42.49074074074074,
 ('120', 'S', '2'): -28.875,
 ('120', 'S', '3'): -32.516129032258064,
 ('121', 'N', '1'): 130.1734693877551,
 ('121', 'S', '1'): 30.87962962962963,
 ('122', 'N', '1'): 110.5204081632653,
 ('122', 'S', '1'): 53.72222222222222,
 ('123', 'N', '1'): 116.96938775510205,
 ('123', 'N', '2'): 40.64179104477612,
 ('123', 'N', '3'): 60.5,
 ('123', 'S', '1'): 54.96296296296296,
 ('123', 'S', '2'): -14.829545454545455,
 ('123', 'S', '3'): -23.774193548387096,
 ('124', 'N', '1'): 83.14285714285714,
 ('124', 'S', '1'): 57.111111111111114,
 ('125', 'N', '1'): 77.03061224489795,
 ('125', 'S', '1'): 53.833333333333336,
 ('126', 'N', '1'): 92.0204081632653,
 ('126', 'S', '1'): 40.574074074074076,
 ('127', 'N', '1'): 34.38775510204081,
 ('127', 'N', '2'): 24.492537313432837,
 ('127', 'N', '3'): 47.875,
 ('127', 'S', '1'): 67.75229357798165,
 ('127', 'S', '2'): -10.215909090909092,
 ('127', 'S', '3'): -34.25806451612903,
 ('128', 'N', '1'): 36.744897959183675,
 ('128', 'N', '2'): -50.55223880597015,
 ('128', 'N', '3'): -22.033898305084747,
 ('128', 'S', '1'): 97.37614678899082,
 ('128', 'S', '2'): 60.375,
 ('128', 'S', '3'): 18.967741935483872,
 ('129', 'N', '1'): 22.26530612244898,
 ('129', 'S', '1'): 109.66666666666667,
 ('130', 'N', '1'): 7.887755102040816,
 ('130', 'S', '1'): 119.17592592592592,
 ('131', 'N', '1'): -4.3979591836734695,
 ('131', 'S', '1'): 125.60185185185185,
 ('132', 'N', '1'): -35.826530612244895,
 ('132', 'N', '2'): -72.83582089552239,
 ('132', 'N', '3'): -25.23728813559322,
 ('132', 'S', '1'): 146.1651376146789,
 ('132', 'S', '2'): 44.52272727272727,
 ('132', 'S', '3'): 6.387096774193548,
 ('133', 'N', '1'): -30.0,
 ('133', 'S', '1'): 142.2018348623853,
 ('134', 'N', '1'): -19.948979591836736,
 ('134', 'S', '1'): 133.22935779816513,
 ('135', 'N', '1'): 6.918367346938775,
 ('135', 'S', '1'): 99.89908256880734,
 ('136', 'N', '1'): 0.8061224489795918,
 ('136', 'S', '1'): 105.77981651376147,
 ('137', 'N', '1'): 3.0918367346938775,
 ('137', 'N', '2'): -40.56060606060606,
 ('137', 'N', '3'): 12.779661016949152,
 ('137', 'S', '1'): 189.43243243243242,
 ('137', 'S', '2'): 24.568181818181817,
 ('137', 'S', '3'): -13.919354838709678,
 ('138', 'N', '1'): -17.448979591836736,
 ('138', 'S', '1'): 65.71818181818182,
 ('139', 'N', '1'): -2.2448979591836733,
 ('139', 'S', '1'): 54.6,
 ('142', 'N', '1'): 0.0,
 ('142', 'S', '1'): 54.7027027027027,
 ('201', 'N', '2'): 289.5970149253731,
 ('201', 'S', '2'): 0.0,
 ('204', 'N', '2'): 282.92537313432837,
 ('204', 'N', '5'): 223.89473684210526,
 ('204', 'S', '2'): 26.423529411764704,
 ('204', 'S', '5'): 0.4583333333333333,
 ('205', 'N', '2'): 179.46268656716418,
 ('205', 'N', '5'): 316.8333333333333,
 ('205', 'S', '2'): -6.247058823529412,
 ('205', 'S', '5'): -3.0,
 ('206', 'N', '2'): 136.2537313432836,
 ('206', 'N', '5'): 276.6666666666667,
 ('206', 'S', '2'): -7.823529411764706,
 ('206', 'S', '5'): -6.875,
 ('207', 'N', '2'): 120.35820895522389,
 ('207', 'N', '5'): 220.0,
 ('207', 'S', '2'): 7.705882352941177,
 ('207', 'S', '5'): -14.958333333333334,
 ('208', 'N', '2'): 100.91044776119404,
 ('208', 'N', '5'): 171.77777777777777,
 ('208', 'S', '2'): 17.294117647058822,
 ('208', 'S', '5'): -15.208333333333334,
 ('209', 'N', '2'): 106.88059701492537,
 ('209', 'N', '5'): 158.27777777777777,
 ('209', 'S', '2'): 8.823529411764707,
 ('209', 'S', '5'): -30.166666666666668,
 ('210', 'N', '2'): 103.7910447761194,
 ('210', 'N', '5'): 160.72222222222223,
 ('210', 'S', '2'): 3.8117647058823527,
 ('210', 'S', '5'): -30.333333333333332,
 ('211', 'N', '2'): 108.25373134328358,
 ('211', 'N', '5'): 176.05555555555554,
 ('211', 'S', '2'): -14.658823529411764,
 ('211', 'S', '5'): -48.375,
 ('212', 'N', '2'): 134.59701492537314,
 ('212', 'N', '5'): 190.72222222222223,
 ('212', 'S', '2'): -31.070588235294117,
 ('212', 'S', '5'): -73.20833333333333,
 ('213', 'N', '2'): 94.16417910447761,
 ('213', 'N', '5'): 108.77777777777777,
 ('213', 'S', '2'): 31.870588235294118,
 ('213', 'S', '5'): 9.943181818181818,
 ('214', 'N', '2'): 56.791044776119406,
 ('214', 'N', '5'): -233.94736842105263,
 ('214', 'S', '2'): 23.188235294117646,
 ('214', 'S', '5'): 26.258064516129032,
 ('215', 'N', '2'): 64.77611940298507,
 ('215', 'N', '5'): -225.21052631578948,
 ('215', 'S', '2'): 15.51764705882353,
 ('215', 'S', '5'): 20.580645161290324,
 ('216', 'N', '2'): 101.76119402985074,
 ('216', 'N', '5'): -194.26315789473685,
 ('216', 'S', '2'): -33.04651162790697,
 ('216', 'S', '5'): -22.677419354838708,
 ('217', 'N', '2'): 94.29850746268657,
 ('217', 'N', '5'): -205.42105263157896,
 ('217', 'S', '2'): -6.929411764705883,
 ('217', 'S', '5'): 17.129032258064516,
 ('218', 'N', '2'): 100.53731343283582,
 ('218', 'N', '5'): -214.89473684210526,
 ('218', 'S', '2'): -12.705882352941176,
 ('218', 'S', '5'): 8.612903225806452,
 ('219', 'N', '2'): 104.97014925373135,
 ('219', 'N', '5'): -209.47368421052633,
 ('219', 'S', '2'): -21.75294117647059,
 ('219', 'S', '5'): 0.0967741935483871,
 ('220', 'N', '2'): 112.95522388059702,
 ('220', 'N', '5'): -213.31578947368422,
 ('220', 'S', '2'): -28.2,
 ('220', 'S', '5'): 0.9032258064516129,
 ('221', 'N', '2'): 139.47761194029852,
 ('221', 'N', '5'): 164.97402597402598,
 ('221', 'S', '2'): -24.6046511627907,
 ('221', 'S', '5'): -73.89772727272727,
 ('222', 'N', '2'): 179.38805970149255,
 ('222', 'N', '5'): 208.32467532467533,
 ('222', 'S', '2'): -16.5,
 ('222', 'S', '5'): -45.26136363636363,
 ('224', 'N', '2'): 138.9402985074627,
 ('224', 'N', '3'): 172.625,
 ('224', 'S', '2'): -3.372093023255814,
 ('224', 'S', '3'): -30.580645161290324,
 ('225', 'N', '2'): 136.044776119403,
 ('225', 'N', '3'): 166.921875,
 ('225', 'S', '2'): -32.18604651162791,
 ('225', 'S', '3'): -31.048387096774192,
 ('226', 'N', '2'): 113.94029850746269,
 ('226', 'N', '3'): 151.671875,
 ('226', 'S', '2'): -22.290697674418606,
 ('226', 'S', '3'): -25.016129032258064,
 ('227', 'N', '2'): 81.8955223880597,
 ('227', 'N', '3'): 122.15625,
 ('227', 'S', '2'): -8.848837209302326,
 ('227', 'S', '3'): -12.919354838709678,
 ('228', 'N', '2'): -60.28787878787879,
 ('228', 'N', '3'): 1.1016949152542372,
 ('228', 'S', '2'): 45.97727272727273,
 ('228', 'S', '3'): -0.04838709677419355,
 ('229', 'N', '2'): -37.60606060606061,
 ('229', 'N', '3'): 17.847457627118644,
 ('229', 'S', '2'): 47.45454545454545,
 ('229', 'S', '3'): 2.3548387096774195,
 ('230', 'N', '2'): -41.89393939393939,
 ('230', 'N', '3'): 5.440677966101695,
 ('230', 'S', '2'): 37.44318181818182,
 ('230', 'S', '3'): -8.64516129032258,
 ('231', 'N', '2'): -43.56060606060606,
 ('231', 'N', '3'): 4.237288135593221,
 ('231', 'S', '2'): -21.261363636363637,
 ('231', 'S', '3'): -67.83870967741936,
 ('232', 'N', '2'): -54.27272727272727,
 ('232', 'N', '3'): -4.237288135593221,
 ('232', 'S', '2'): -2.875,
 ('232', 'S', '3'): -54.645161290322584,
 ('233', 'N', '2'): -55.31818181818182,
 ('233', 'N', '3'): -7.9491525423728815,
 ('233', 'S', '2'): -5.1477272727272725,
 ('233', 'S', '3'): -54.596774193548384,
 ('234', 'N', '2'): -57.28787878787879,
 ('234', 'N', '3'): -16.966101694915253,
 ('234', 'N', '4'): -14.43661971830986,
 ('234', 'N', '5'): -46.246153846153845,
 ('234', 'S', '2'): 28.704545454545453,
 ('234', 'S', '3'): -15.53225806451613,
 ('234', 'S', '4'): -30.572916666666668,
 ('234', 'S', '5'): -15.604395604395604,
 ('235', 'N', '2'): -56.95454545454545,
 ('235', 'N', '3'): -11.11864406779661,
 ('235', 'N', '4'): -26.323943661971832,
 ('235', 'N', '5'): -50.215384615384615,
 ('235', 'S', '2'): 27.079545454545453,
 ('235', 'S', '3'): 8.96774193548387,
 ('235', 'S', '4'): -17.645833333333332,
 ('235', 'S', '5'): 5.648351648351649,
 ('236', 'N', '2'): -41.77272727272727,
 ('236', 'N', '3'): 1.9830508474576272,
 ('236', 'S', '2'): 31.068181818181817,
 ('236', 'S', '3'): 23.5,
 ('237', 'N', '2'): -35.86363636363637,
 ('237', 'N', '3'): 10.152542372881356,
 ('237', 'S', '2'): 13.931818181818182,
 ('237', 'S', '3'): 11.258064516129032,
 ('238', 'N', '2'): -54.56060606060606,
 ('238', 'N', '3'): -7.576271186440678,
 ('238', 'S', '2'): 7.5227272727272725,
 ('238', 'S', '3'): 4.532258064516129,
 ('239', 'N', '2'): -56.24242424242424,
 ('239', 'N', '3'): -5.661016949152542,
 ('239', 'N', '4'): 1.380281690140845,
 ('239', 'N', '5'): -14.015384615384615,
 ('239', 'S', '2'): 33.09090909090909,
 ('239', 'S', '3'): 11.774193548387096,
 ('239', 'S', '4'): -28.489583333333332,
 ('239', 'S', '5'): 2.208791208791209,
 ('241', 'N', '2'): -60.714285714285715,
 ('241', 'N', '5'): -45.44642857142857,
 ('241', 'S', '2'): -0.3522727272727273,
 ('241', 'S', '5'): 18.701149425287355,
 ('242', 'N', '2'): -81.65079365079364,
 ('242', 'N', '5'): -48.30357142857143,
 ('242', 'S', '2'): 4.7272727272727275,
 ('242', 'S', '5'): 19.919540229885058,
 ('243', 'N', '2'): -67.3015873015873,
 ('243', 'N', '5'): -36.107142857142854,
 ('243', 'S', '2'): 6.488636363636363,
 ('243', 'S', '5'): 23.39080459770115,
 ('244', 'N', '2'): -7.174603174603175,
 ('244', 'N', '5'): 26.160714285714285,
 ('244', 'S', '2'): 89.2840909090909,
 ('244', 'S', '5'): 99.86206896551724,
 ('245', 'N', '2'): -25.365079365079364,
 ('245', 'N', '5'): 7.75,
 ('245', 'S', '2'): -43.56818181818182,
 ('245', 'S', '5'): -24.632183908045977,
 ('246', 'N', '2'): -21.650793650793652,
 ('246', 'N', '5'): 9.875,
 ('246', 'S', '2'): -21.011363636363637,
 ('246', 'S', '5'): -4.310344827586207,
 ('247', 'N', '2'): 0.0,
 ('247', 'N', '5'): 0.0,
 ('247', 'S', '2'): 83.92045454545455,
 ('247', 'S', '5'): 94.89655172413794,
 ('248', 'N', '2'): -116.66666666666667,
 ('248', 'N', '3'): -65.83050847457628,
 ('248', 'S', '3'): 92.01612903225806,
 ('249', 'N', '2'): -54.0,
 ('249', 'N', '3'): -36.08474576271186,
 ('249', 'S', '3'): 69.37096774193549,
 ('250', 'N', '2'): -6.666666666666667,
 ('250', 'N', '3'): -1.2203389830508475,
 ('250', 'N', '4'): 7.71830985915493,
 ('250', 'N', '5'): 1.3333333333333333,
 ('250', 'S', '3'): 42.74193548387097,
 ('250', 'S', '4'): -40.697916666666664,
 ('250', 'S', '5'): -47.25,
 ('251', 'N', '2'): -41.0,
 ('251', 'N', '3'): -17.847457627118644,
 ('251', 'N', '4'): -28.75,
 ('251', 'S', '3'): 46.693548387096776,
 ('252', 'N', '2'): -27.333333333333332,
 ('252', 'N', '3'): -15.40677966101695,
 ('252', 'N', '4'): -17.0,
 ('252', 'S', '3'): 50.435483870967744,
 ('253', 'N', '2'): -26.0,
 ('253', 'N', '3'): 5.711864406779661,
 ('253', 'N', '4'): -13.25,
 ('253', 'S', '3'): 46.91935483870968,
 ('254', 'N', '2'): -19.333333333333332,
 ('254', 'N', '3'): -0.3220338983050847,
 ('254', 'N', '4'): -5.0,
 ('254', 'S', '3'): 54.54838709677419,
 ('255', 'N', '2'): -34.333333333333336,
 ('255', 'N', '3'): -4.0,
 ('255', 'N', '4'): -17.375,
 ('255', 'S', '3'): 72.83870967741936,
 ('256', 'N', '2'): -52.0,
 ('256', 'N', '3'): -20.627118644067796,
 ('256', 'N', '4'): -37.5,
 ('256', 'S', '3'): 90.87096774193549,
 ('257', 'N', '2'): 0.0,
 ('257', 'N', '3'): 0.0,
 ('257', 'N', '4'): 0.0,
 ('257', 'S', '3'): 112.12903225806451,
 ('301', 'N', '3'): 233.203125,
 ('301', 'S', '3'): 9.105263157894736,
 ('302', 'N', '3'): 210.53125,
 ('302', 'S', '3'): 35.774193548387096,
 ('401', 'N', '4'): 215.55555555555554,
 ('401', 'S', '4'): 0.0,
 ('402', 'N', '4'): 179.0483870967742,
 ('402', 'S', '4'): -1.4090909090909092,
 ('405', 'N', '4'): 203.890243902439,
 ('405', 'S', '4'): -12.386363636363637,
 ('406', 'N', '4'): 196.2875,
 ('406', 'S', '4'): -27.817204301075268,
 ('407', 'N', '4'): 187.1625,
 ('407', 'S', '4'): -31.752688172043012,
 ('408', 'N', '4'): 190.3125,
 ('408', 'S', '4'): -40.784946236559136,
 ('409', 'N', '4'): 201.45679012345678,
 ('409', 'S', '4'): -33.32258064516129,
 ('410', 'N', '4'): 188.8625,
 ('410', 'S', '4'): -35.59139784946237,
 ('411', 'N', '4'): 175.2125,
 ('411', 'S', '4'): -46.924731182795696,
 ('412', 'N', '4'): 168.5875,
 ('412', 'S', '4'): -35.623655913978496,
 ('413', 'N', '4'): 168.55696202531647,
 ('413', 'S', '4'): -36.043010752688176,
 ('414', 'N', '4'): 151.40506329113924,
 ('414', 'S', '4'): -46.11827956989247,
 ('415', 'N', '4'): 147.73333333333332,
 ('415', 'S', '4'): -23.074468085106382,
 ('416', 'N', '4'): 113.61363636363636,
 ('416', 'N', '5'): 171.27272727272728,
 ('416', 'S', '4'): -11.0625,
 ('416', 'S', '5'): -6.386363636363637,
 ('418', 'N', '4'): 22.466666666666665,
 ('418', 'N', '5'): 48.84415584415584,
 ('418', 'S', '4'): -24.583333333333332,
 ('418', 'S', '5'): -7.186813186813187,
 ('419', 'N', '4'): 8.333333333333334,
 ('419', 'N', '5'): 46.15584415584416,
 ('419', 'S', '4'): -24.65625,
 ('419', 'S', '5'): -7.395604395604396,
 ('420', 'N', '4'): 10.666666666666666,
 ('420', 'N', '5'): 43.5974025974026,
 ('420', 'S', '4'): -22.583333333333332,
 ('420', 'S', '5'): -5.714285714285714,
 ('423', 'N', '4'): 18.47887323943662,
 ('423', 'N', '5'): -17.523076923076925,
 ('423', 'S', '4'): -74.76041666666667,
 ('423', 'S', '5'): -57.16483516483517,
 ('501', 'N', '5'): 30.21311475409836,
 ('501', 'S', '5'): 0.0,
 ('502', 'N', '5'): -10.114754098360656,
 ('502', 'S', '5'): -1.859375,
 ('503', 'N', '5'): 6.459016393442623,
 ('503', 'S', '5'): -26.09375,
 ('504', 'N', '5'): 16.131147540983605,
 ('504', 'S', '5'): -41.875,
 ('505', 'N', '5'): -5.19672131147541,
 ('505', 'S', '5'): -15.890625,
 ('601', 'N', '6'): 69.375,
 ('601', 'N', '6X'): 154.0,
 ('601', 'S', '6'): 0.0,
 ('601', 'S', '6X'): 0.0,
 ('602', 'N', '6'): 67.41935483870968,
 ('602', 'N', '6X'): 94.2439024390244,
 ('602', 'S', '6'): -23.57894736842105,
 ('602', 'S', '6X'): -2.911764705882353,
 ('603', 'N', '6'): 83.41935483870968,
 ('603', 'N', '6X'): 107.63414634146342,
 ('603', 'S', '6'): -1.894736842105263,
 ('603', 'S', '6X'): 23.852941176470587,
 ('604', 'N', '6'): 80.71875,
 ('604', 'N', '6X'): 125.8780487804878,
 ('604', 'S', '6'): -13.81578947368421,
 ('604', 'S', '6X'): 17.470588235294116,
 ('606', 'N', '6'): 54.903225806451616,
 ('606', 'N', '6X'): 108.4390243902439,
 ('606', 'S', '6'): 2.1578947368421053,
 ('606', 'S', '6X'): 4.029411764705882,
 ('607', 'N', '6'): 42.45161290322581,
 ('607', 'N', '6X'): 123.88095238095238,
 ('607', 'S', '6'): -16.13157894736842,
 ('607', 'S', '6X'): 18.058823529411764,
 ('608', 'N', '6'): 185.82758620689654,
 ('608', 'N', '6X'): 181.4390243902439,
 ('608', 'S', '6'): -8.576923076923077,
 ('608', 'S', '6X'): 19.735294117647058,
 ('609', 'N', '6'): 186.87719298245614,
 ('609', 'S', '6'): 1.2980769230769231,
 ('610', 'N', '6'): 137.01754385964912,
 ('610', 'S', '6'): -5.375,
 ('611', 'N', '6'): 121.3859649122807,
 ('611', 'S', '6'): 3.2211538461538463,
 ('612', 'N', '6'): 111.7719298245614,
 ('612', 'S', '6'): 16.567307692307693,
 ('613', 'N', '6'): 135.08771929824562,
 ('613', 'N', '6X'): 119.14634146341463,
 ('613', 'S', '6'): 24.676190476190477,
 ('613', 'S', '6X'): 30.529411764705884,
 ('614', 'N', '6'): 102.75438596491227,
 ('614', 'S', '6'): 28.01923076923077,
 ('615', 'N', '6'): 102.64912280701755,
 ('615', 'S', '6'): 29.096153846153847,
 ('616', 'N', '6'): 101.0701754385965,
 ('616', 'S', '6'): 29.682692307692307,
 ('617', 'N', '6'): 91.15789473684211,
 ('617', 'S', '6'): 19.71153846153846,
 ('618', 'N', '6'): 72.40350877192982,
 ('618', 'S', '6'): 31.96153846153846,
 ('619', 'N', '6'): 76.42105263157895,
 ('619', 'N', '6X'): 86.65853658536585,
 ('619', 'S', '6'): 37.285714285714285,
 ('619', 'S', '6X'): 76.41176470588235,
 ('621', 'N', '4'): 141.73333333333332,
 ('621', 'N', '5'): 181.15584415584416,
 ('621', 'N', '6'): 54.12280701754386,
 ('621', 'N', '6X'): 42.8780487804878,
 ('621', 'S', '4'): -51.21875,
 ('621', 'S', '5'): -31.0,
 ('621', 'S', '6'): 29.83809523809524,
 ('621', 'S', '6X'): 62.1764705882353,
 ('622', 'N', '6'): 46.50909090909091,
 ('622', 'N', '6X'): 51.075,
 ('622', 'S', '6'): 52.180952380952384,
 ('622', 'S', '6X'): 70.1470588235294,
 ('623', 'N', '6'): 42.29090909090909,
 ('623', 'N', '6X'): 24.7,
 ('623', 'S', '6'): 75.74285714285715,
 ('623', 'S', '6X'): 80.11764705882354,
 ('624', 'N', '6'): 28.30909090909091,
 ('624', 'N', '6X'): 27.225,
 ('624', 'S', '6'): 71.17142857142858,
 ('624', 'S', '6X'): 84.52941176470588,
 ('625', 'N', '6'): 23.454545454545453,
 ('625', 'N', '6X'): 20.609756097560975,
 ('625', 'S', '6'): 55.97142857142857,
 ('625', 'S', '6X'): 86.1470588235294,
 ('626', 'N', '4'): 134.34666666666666,
 ('626', 'N', '5'): 153.93506493506493,
 ('626', 'N', '6'): 32.6140350877193,
 ('626', 'N', '6X'): 30.675,
 ('626', 'S', '4'): -32.385416666666664,
 ('626', 'S', '5'): -14.055555555555555,
 ('626', 'S', '6'): 55.03809523809524,
 ('626', 'S', '6X'): 75.3529411764706,
 ('627', 'N', '6'): 28.145454545454545,
 ('627', 'N', '6X'): 23.85,
 ('627', 'S', '6'): 51.65714285714286,
 ('627', 'S', '6X'): 83.29411764705883,
 ('628', 'N', '6'): 28.418181818181818,
 ('628', 'N', '6X'): 34.7,
 ('628', 'S', '6'): 40.04761904761905,
 ('628', 'S', '6X'): 59.14705882352941,
 ('629', 'N', '4'): 133.48,
 ('629', 'N', '5'): 155.7922077922078,
 ('629', 'N', '6'): 20.29090909090909,
 ('629', 'N', '6X'): 10.375,
 ('629', 'S', '4'): -56.15625,
 ('629', 'S', '5'): -34.5,
 ('629', 'S', '6'): 37.63809523809524,
 ('629', 'S', '6X'): 57.8235294117647,
 ('630', 'N', '6'): 15.727272727272727,
 ('630', 'N', '6X'): 22.95,
 ('630', 'S', '6'): 44.67619047619048,
 ('630', 'S', '6X'): 69.44117647058823,
 ('631', 'N', '4'): 84.78666666666666,
 ('631', 'N', '5'): 102.97402597402598,
 ('631', 'N', '6'): -9.963636363636363,
 ('631', 'N', '6X'): -3.375,
 ('631', 'S', '4'): -42.458333333333336,
 ('631', 'S', '5'): -21.395604395604394,
 ('631', 'S', '6'): 63.457142857142856,
 ('631', 'S', '6X'): 67.26470588235294,
 ('632', 'N', '6'): -14.381818181818181,
 ('632', 'N', '6X'): -19.45,
 ('632', 'S', '6'): 78.72115384615384,
 ('632', 'S', '6X'): 87.55882352941177,
 ('633', 'N', '6'): -13.472727272727273,
 ('633', 'N', '6X'): -5.2,
 ('633', 'S', '6'): 93.75961538461539,
 ('633', 'S', '6X'): 97.61764705882354,
 ('634', 'N', '6'): -29.236363636363638,
 ('634', 'N', '6X'): -23.95,
 ('634', 'S', '6'): 96.9326923076923,
 ('634', 'S', '6X'): 90.22857142857143,
 ('635', 'N', '4'): 41.666666666666664,
 ('635', 'N', '5'): 47.51948051948052,
 ('635', 'N', '6'): -44.61818181818182,
 ('635', 'N', '6X'): -44.025,
 ('635', 'S', '4'): -29.0,
 ('635', 'S', '5'): -7.175824175824176,
 ('635', 'S', '6'): 89.37735849056604,
 ('635', 'S', '6X'): 99.68571428571428,
 ('636', 'N', '6'): -42.018181818181816,
 ('636', 'N', '6X'): -43.25,
 ('636', 'S', '6'): 129.0,
 ('636', 'S', '6X'): 130.76470588235293,
 ('637', 'N', '6'): -46.58181818181818,
 ('637', 'N', '6X'): -52.475,
 ('637', 'S', '6'): 108.65094339622641,
 ('637', 'S', '6X'): 113.4,
 ('638', 'N', '6'): -43.49090909090909,
 ('638', 'N', '6X'): -36.55,

In [ ]:
all_stops = get_stops()[:-21]
lines = sorted(['A','C','E','B','D','F','FX','M','G','J','Z','L','N','Q','R','W','FS','GS','H','1','2','3','4','5','6','6X','7','7X'])
mtidxr = pd.MultiIndex.from_tuples(list(product(all_stops, ['N','S'])), names=['stop','dir'])
full_gridr = pd.DataFrame(index=mtidxr, columns=lines)
for k,v in deltadictr.items():
	full_gridr.at[(k[0],k[1]),k[2]] = v

In [ ]:
full_gridr

                   1    2    3    4    5    6   6X    7   7X    A  ...   GS  \
stop dir                                                           ...
101  N    148.663265  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
     S           0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
103  N    163.806122  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
     S      1.425926  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
104  N    146.163265  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
...              ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
S01  S           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
S03  N           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
     S           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
S04  N           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN
     S           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN

            H    J    L    M    N    Q    R    W    Z
stop dir
101  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
103  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
104  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...       ...  ...  ...  ...  ...  ...  ...  ...  ...
S01  S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
S03  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
S04  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[950 rows x 28 columns]

In [ ]:
full_gridr[full_gridr.isna().all(1)]

,,1,2,3,4,5,6,6X,7,7X,A,...,GS,H,J,L,M,N,Q,R,W,Z
stop,dir,,,,,,,,,,,,,,,,,,,,,
711,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
713,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H01,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
full_gridr.loc[['710','711','712','713','714']]

            1    2    3    4    5    6   6X          7   7X    A  ...   GS  \
stop dir                                                          ...
710  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  69.061224  NaN  NaN  ...  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  36.918478  NaN  NaN  ...  NaN
711  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  37.435374  NaN  NaN  ...  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN        NaN  NaN  NaN  ...  NaN
712  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  69.877551  NaN  NaN  ...  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN   5.195652  NaN  NaN  ...  NaN
713  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  -0.823129  NaN  NaN  ...  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN        NaN  NaN  NaN  ...  NaN
714  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN -16.054422  NaN  NaN  ...  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN   2.804348  NaN  NaN  ...  NaN

            H    J    L    M    N    Q    R    W    Z
stop dir
710  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
711  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
712  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
713  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
714  N    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
     S    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[10 rows x 28 columns]

In [ ]:
class BreakPoint(Exception):
	pass

In [ ]:
## somehow the 7X is not showing up on this map, no idea why

In [ ]:
## we can extrapolate 711 and 713 Southbound since they dont share tracks and only use the 7, so the average delay from previous and following stops will work here
full_gridr.at[('711','S'),'7'] = (full_gridr.loc['710','S']['7']+full_gridr.loc['712','S']['7'])/2
full_gridr.at[('713','S'),'7'] = (full_gridr.loc['712','S']['7']+full_gridr.loc['714','S']['7'])/2

## aqueduct racetrack is a oneway stop so we can just assume the delay would be the same
full_gridr.at[('H01','S'),'A'] = full_gridr.at[('H01','N'),'A']
full_gridr[full_gridr.isna().all(1)]
full_gridr_md = full_gridr.copy()
aggstops = {k: lambda x: np.nanmean(x, axis=0, dtype=np.float64) for k in lines}
aggstops['stop'] = 'first'
full_gridr_md_avg = full_gridr_md.reset_index().drop('dir', axis=1).groupby('stop').agg(aggstops)
delay_timesr = full_gridr_md_avg.drop('stop',axis=1).apply(lambda x: np.nanmean(x),axis=1)
np.round(delay_timesr.values.clip(0)/60).clip(0,5)
rushmindf = pd.DataFrame(delay_timesr, columns=['seconds'])
rushmindf['mins'] = np.round(delay_timesr.values.clip(0)/60).clip(0,5)
rushmindf.mins.to_csv('data/delay_minutes_rush.csv')