In [263]:
import pandas as pd
from pandas import DataFrame
import numpy as np
import networkx as nx
import peartree as pear
import partridge as ptg
import matplotlib.pyplot as plt
import itertools
import warnings
warnings.filterwarnings('ignore')

In [264]:
feed_all = pear.get_representative_feed("gtfs_subway/")
feed = feed_all

In [265]:
def iterator(L):
	a, b = itertools.tee(L)
	next(b, None)
	return list(zip(a,b))

In [266]:
G = nx.MultiGraph(name="midday")

In [267]:
station_data = pd.read_csv("data/MTA_Subway_Stations.csv")
station_data = station_data[['GTFS Stop ID', 'Complex ID', 'Stop Name', 'Daytime Routes']]

rl = [str(r).split() for r in station_data['Daytime Routes']]
station_data['Daytime Routes'] = rl

# remove Staten Island Railroad

station_data = station_data[station_data['Daytime Routes'].apply(lambda x: "SIR" not in x)]
station_data.set_index('GTFS Stop ID', drop=False, inplace=True)
nodes_list = [(k, v) for k,v in station_data.to_dict('index').items()]

In [268]:
G.add_nodes_from(nodes_list)

In [269]:
line_names = [str(s) for s in [1,2,3,4,5,6,'6X',7,'7X','A','B','C','D','E','F','G','H','J','L','M','N','Q','R','W','Z','FS','GS','Transfer']]

In [270]:
## transfers in complex
transfers = pd.read_csv('gtfs_subway/transfers.txt')
	
transfers.drop("transfer_type", inplace=True, axis=1)

transfers = transfers[transfers['from_stop_id'] != transfers['to_stop_id']]
transfers.reset_index(inplace=True,drop=True)
transfers

    from_stop_id to_stop_id  min_transfer_time
0            112        A09                180
1            125        A24                180
2            127        725                180
3            127        902                180
4            127        A27                300
..           ...        ...                ...
147          R31        235                180
148          R31        D24                300
149          R33        F23                180
150          S01        A45                180
151          S04        239                180

[152 rows x 3 columns]

In [271]:
complexes = pd.read_csv("data/MTA_Subway_Stations_and_Complexes_20250918.csv")
complexes = complexes[complexes['Number Of Stations In Complex'] > 1]
complexes = complexes[['Complex ID','Number Of Stations In Complex', 'GTFS Stop IDs']]
gtfs_ids = [ids.split("; ") for ids in complexes['GTFS Stop IDs']]
complex_pairs = [list(itertools.combinations(sts, 2)) for sts in gtfs_ids]
complexes['complex_transfers'] = complex_pairs
complexes = complexes.explode('complex_transfers', ignore_index=True).drop(['Number Of Stations In Complex','GTFS Stop IDs'], axis= 1)
transfer_edges = list(zip(transfers['from_stop_id'], transfers['to_stop_id']))
transfer_edge_set = set()
for k in transfer_edges:
	transfer_edge_set.add(tuple(sorted(k)))

##print(transfer_edge_set ^ set(complexes['complex_transfers']))
##('254', 'L26'), ('629', 'B08'), ('B08', 'R11')##

## Out of station transfers specified on the official map
## Walk Junius to Livonia
## Walk Lexington-59 NRW to Lexington-63 -- 300s
## walk Lexington-59 456 to Lexington-63 -- 300s
transfers['edges'] = [tuple(sorted(k)) for k in transfer_edges]
unique_transfers = transfers.sort_values('edges').iloc[::2,:]
unique_transfers.reset_index(drop=True,inplace=True)
unique_transfers.drop(['from_stop_id', 'to_stop_id'], axis=1, inplace=True)

In [311]:
unique_transfers.edges.to_csv('transfer_edges.csv')

In [272]:
fstop = [unique_transfers['edges'][k][0] for k in unique_transfers.index]
tstop = [unique_transfers['edges'][k][1] for k in unique_transfers.index]
ttime = unique_transfers['min_transfer_time']
transfer_edge_weights = {(a, b): {"Transfer": t} for a,b,t in list(zip(fstop, tstop, ttime))}

In [273]:
el = list(G.edges(data=True))

for i in range(len(el)):
	q = (el[i][0], el[i][1])
	d = el[i][2]
	el[i] = [q,d]

edf = pd.DataFrame([k[1] for k in el], index= [k[0] for k in el])
ndf = pd.DataFrame.from_dict(dict(G.nodes(data=True))).T

### Fix edge weights so that boarding cost varies by line

In [274]:
## midday 9:30 am to 3:30 pm
start_time = int(9.5 * 60 * 60)
end_time = int(15.5 * 60 * 60)

In [275]:
start_time = int(9.5 * 60 * 60)
end_time = int(15.5 * 60 * 60)
tripline = list(feed.stop_times['trip_id'])
inseq = feed.stop_times.copy()
tripdict = {k: v for k,v in zip(feed.trips['trip_id'], feed.trips['route_id'])}
feed.stop_times['lines'] = [tripdict[s] for s in feed.stop_times['trip_id']]
feed.stop_times['dir'] = [s[-4] if s[-4] != 'X' else s[-7] for s in feed.stop_times['trip_id']]
stoptime = pd.DataFrame(feed.stop_times).copy()
stoptime = stoptime[stoptime['arrival_time'].between(start_time, end_time)]
stoptime = stoptime[stoptime['lines'] != 'SI']
stoptime.sort_values(['stop_id','lines', 'dir', 'arrival_time'], inplace=True)

In [276]:
seq_dict = {}
for n, g in inseq.groupby('trip_id'):
	seq_dict[n] = len(g['stop_sequence'])

In [277]:
G.nodes['713']

{'GTFS Stop ID': '713',
 'Complex ID': 457,
 'Stop Name': '52 St',
 'Daytime Routes': ['7']}

In [278]:
stoptime.sort_values('trip_id', inplace=True)
stoptime['trip_len'] = [seq_dict[n] for n in stoptime['trip_id']]
stops_in_time = dict(stoptime.trip_id.value_counts())
stoptime['count_in_timespan'] = [stops_in_time[n] for n in stoptime.trip_id]
stoptime = stoptime[stoptime['count_in_timespan'] == stoptime['trip_len']]

In [279]:
stgroups = stoptime.groupby(['stop_id', 'lines','dir'], group_keys=True)
st_weights = pd.DataFrame(list(stgroups.groups.keys()),index=list(stgroups.groups.keys()), columns=['stop', 'line', 'dir']).reset_index(drop=False)
st_weights['weight'] = 0
i = 0
for name, group in stgroups:
	waittime = iterator(list(group['arrival_time']))
	dirw = round(np.mean([b-a for a,b in waittime]), 3)
	st_weights.at[i, 'weight'] = dirw
	i += 1


st_weights = st_weights.groupby(['stop','line'], as_index=False).mean('weight')
st_weights.sort_values('stop', inplace=True)

node_weight_dict = {}
for name, group in st_weights.groupby(['stop'],group_keys=True):
	float_w = dict(zip(group['line'], group['weight']))
	float_w = {k: round(v,3) for k,v in float_w.items()}
	node_weight_dict[name[0]] = float_w

In [280]:
st_weights

    stop line    weight
0    101    1  333.8755
1    103    1  334.9665
2    104    1  334.9665
3    106    1  334.9665
4    107    1  334.9665
..   ...  ...       ...
753  R44    R  479.5455
754  R45    R  479.5455
755  S01   FS  600.0000
756  S03   FS  600.0000
757  S04   FS  600.0000

[758 rows x 3 columns]

In [281]:
G.nodes['713']

{'GTFS Stop ID': '713',
 'Complex ID': 457,
 'Stop Name': '52 St',
 'Daytime Routes': ['7']}

In [282]:
for n in G.nodes:
	G.nodes[n]['wait_time'] = node_weight_dict[n]
	G.nodes[n]['lines'] = set(node_weight_dict[n].keys())
	try:
		del G.nodes[n]['Daytime Routes']
	except KeyError:
		continue

In [283]:
dict_7x = {k: v for k,v in node_weight_dict.items() if '7X' in v}
nan7x = {k: v for k,v in dict_7x.items() if np.isnan(v.get('7X'))}

In [284]:
## fix nan for one-off 7X routes in midday
G.nodes['710']['wait_time']['7X'] = 495.0
G.nodes['711']['wait_time']['7X'] = 495.0
G.nodes['713']['wait_time']['7X'] = 465.0

## remove the single 5 train to gun hill rd in non-rushhour

try:
	del G.nodes['208']['wait_time']['5']
except:
	pass

In [285]:
for n in G.nodes:
	G.nodes[n]['lines'] = set(G.nodes[n]['wait_time'].keys())

In [286]:
## do edges

stops_per_line = stoptime.sort_values(['lines','trip_len'])
stops_per_line = stops_per_line.groupby('trip_id', group_keys=False).apply(lambda x: x.sort_values('stop_sequence'))

In [287]:
edge_set = set()

In [288]:
for name, group in stops_per_line.groupby('trip_id'):
	edges = iterator(group.stop_id.to_list())
	for k in edges:
		edge_set.add(tuple(sorted(k)))
edge_set

{('101', '103'),
 ('103', '104'),
 ('104', '106'),
 ('106', '107'),
 ('107', '108'),
 ('108', '109'),
 ('109', '110'),
 ('110', '111'),
 ('111', '112'),
 ('112', '113'),
 ('113', '114'),
 ('114', '115'),
 ('115', '116'),
 ('116', '117'),
 ('117', '118'),
 ('118', '119'),
 ('119', '120'),
 ('120', '121'),
 ('120', '123'),
 ('120', '227'),
 ('121', '122'),
 ('122', '123'),
 ('123', '124'),
 ('123', '127'),
 ('124', '125'),
 ('125', '126'),
 ('126', '127'),
 ('127', '128'),
 ('128', '129'),
 ('128', '132'),
 ('129', '130'),
 ('130', '131'),
 ('131', '132'),
 ('132', '133'),
 ('132', '137'),
 ('133', '134'),
 ('134', '135'),
 ('135', '136'),
 ('136', '137'),
 ('137', '138'),
 ('137', '228'),
 ('138', '139'),
 ('139', '142'),
 ('201', '204'),
 ('204', '205'),
 ('205', '206'),
 ('206', '207'),
 ('207', '208'),
 ('208', '209'),
 ('208', '213'),
 ('209', '210'),
 ('210', '211'),
 ('211', '212'),
 ('212', '213'),
 ('213', '214'),
 ('213', '221'),
 ('213', '505'),
 ('214', '215'),
 ('215', '216'),
 ('216', '217'),
 ('217', '218'),
 ('218', '219'),
 ('219', '220'),
 ('220', '221'),
 ('221', '222'),
 ('222', '224'),
 ('222', '416'),
 ('224', '225'),
 ('224', '302'),
 ('225', '226'),
 ('226', '227'),
 ('228', '229'),
 ('229', '230'),
 ('230', '231'),
 ('231', '232'),
 ('232', '233'),
 ('233', '234'),
 ('234', '235'),
 ('234', '423'),
 ('235', '236'),
 ('235', '239'),
 ('236', '237'),
 ('237', '238'),
 ('238', '239'),
 ('239', '241'),
 ('239', '248'),
 ('239', '250'),
 ('241', '242'),
 ('242', '243'),
 ('243', '244'),
 ('244', '245'),
 ('245', '246'),
 ('246', '247'),
 ('248', '249'),
 ('249', '250'),
 ('250', '251'),
 ('251', '252'),
 ('252', '253'),
 ('253', '254'),
 ('254', '255'),
 ('255', '256'),
 ('256', '257'),
 ('301', '302'),
 ('401', '402'),
 ('402', '405'),
 ('405', '406'),
 ('406', '407'),
 ('407', '408'),
 ('408', '409'),
 ('409', '410'),
 ('409', '413'),
 ('410', '411'),
 ('411', '412'),
 ('412', '413'),
 ('413', '414'),
 ('414', '415'),
 ('415', '416'),
 ('416', '621'),
 ('418', '419'),
 ('418', '640'),
 ('419', '420'),
 ('420', '423'),
 ('501', '502'),
 ('502', '503'),
 ('503', '504'),
 ('504', '505'),
 ('601', '602'),
 ('602', '603'),
 ('603', '604'),
 ('604', '606'),
 ('606', '607'),
 ('607', '608'),
 ('608', '609'),
 ('608', '613'),
 ('609', '610'),
 ('610', '611'),
 ('611', '612'),
 ('612', '613'),
 ('613', '614'),
 ('613', '619'),
 ('614', '615'),
 ('615', '616'),
 ('616', '617'),
 ('617', '618'),
 ('618', '619'),
 ('619', '621'),
 ('621', '622'),
 ('621', '626'),
 ('622', '623'),
 ('623', '624'),
 ('624', '625'),
 ('625', '626'),
 ('626', '627'),
 ('626', '629'),
 ('627', '628'),
 ('628', '629'),
 ('629', '630'),
 ('629', '631'),
 ('630', '631'),
 ('631', '632'),
 ('631', '635'),
 ('632', '633'),
 ('633', '634'),
 ('634', '635'),
 ('635', '636'),
 ('635', '640'),
 ('636', '637'),
 ('637', '638'),
 ('638', '639'),
 ('639', '640'),
 ('701', '702'),
 ('702', '705'),
 ('702', '707'),
 ('705', '706'),
 ('706', '707'),
 ('707', '708'),
 ('707', '710'),
 ('707', '712'),
 ('708', '709'),
 ('709', '710'),
 ('710', '711'),
 ('710', '712'),
 ('711', '712'),
 ('712', '713'),
 ('712', '714'),
 ('713', '714'),
 ('714', '715'),
 ('715', '716'),
 ('716', '718'),
 ('718', '719'),
 ('719', '720'),
 ('720', '721'),
 ('721', '723'),
 ('723', '724'),
 ('724', '725'),
 ('725', '726'),
 ('901', '902'),
 ('A02', 'A03'),
 ('A03', 'A05'),
 ('A05', 'A06'),
 ('A06', 'A07'),
 ('A07', 'A09'),
 ('A09', 'A10'),
 ('A09', 'A12'),
 ('A10', 'A11'),
 ('A11', 'A12'),
 ('A12', 'A14'),
 ('A12', 'A15'),
 ('A14', 'A15'),
 ('A14', 'D13'),
 ('A15', 'A16'),
 ('A15', 'A24'),
 ('A15', 'D13'),
 ('A16', 'A17'),
 ('A17', 'A18'),
 ('A18', 'A19'),
 ('A19', 'A20'),
 ('A20', 'A21'),
 ('A21', 'A22'),
 ('A22', 'A24'),
 ('A24', 'A25'),
 ('A24', 'A27'),
 ('A24', 'D14'),
 ('A25', 'A27'),
 ('A25', 'D14'),
 ('A27', 'A28'),
 ('A28', 'A30'),
 ('A28', 'A31'),
 ('A30', 'A31'),
 ('A31', 'A32'),
 ('A32', 'A33'),
 ('A32', 'A34'),
 ('A33', 'A34'),
 ('A34', 'A36'),
 ('A34', 'E01'),
 ('A36', 'A38'),
 ('A38', 'A40'),
 ('A40', 'A41'),
 ('A41', 'A42'),
 ('A41', 'F18'),
 ('A41', 'F20'),
 ('A42', 'A43'),
 ('A42', 'A46'),
 ('A42', 'F20'),
 ('A42', 'G36'),
 ('A43', 'A44'),
 ('A44', 'A45'),
 ('A45', 'A46'),
 ('A46', 'A47'),
 ('A46', 'A48'),
 ('A47', 'A48'),
 ('A48', 'A49'),
 ('A48', 'A51'),
 ('A49', 'A50'),
 ('A50', 'A51'),
 ('A51', 'A52'),
 ('A51', 'A55'),
 ('A52', 'A53'),
 ('A53', 'A54'),
 ('A54', 'A55'),
 ('A55', 'A57'),
 ('A57', 'A59'),
 ('A59', 'A60'),
 ('A60', 'A61'),
 ('A61', 'A63'),
 ('A61', 'H01'),
 ('A61', 'H02'),
 ('A63', 'A64'),
 ('A64', 'A65'),
 ('B04', 'B06'),
 ('B04', 'G14'),
 ('B06', 'B08'),
 ('B08', 'B10'),
 ('B08', 'Q03'),
 ('B08', 'R14'),
 ('B10', 'D15'),
 ('B12', 'B13'),
 ('B12', 'R36'),
 ('B13', 'B14'),
 ('B14', 'B15'),
 ('B15', 'B16'),
 ('B16', 'B17'),
 ('B17', 'B18'),
 ('B18', 'B19'),
 ('B19', 'B20'),
 ('B20', 'B21'),
 ('B21', 'B22'),
 ('B22', 'B23'),
 ('B23', 'D43'),
 ('D01', 'D03'),
 ('D03', 'D04'),
 ('D04', 'D05'),
 ('D05', 'D06'),
 ('D06', 'D07'),
 ('D07', 'D08'),
 ('D08', 'D09'),
 ('D09', 'D10'),
 ('D10', 'D11'),
 ('D11', 'D12'),
 ('D12', 'D13'),
 ('D14', 'D15'),
 ('D14', 'F12'),
 ('D15', 'D16'),
 ('D15', 'F12'),
 ('D16', 'D17'),
 ('D17', 'D18'),
 ('D17', 'D20'),
 ('D18', 'D19'),
 ('D19', 'D20'),
 ('D20', 'D21'),
 ('D21', 'D22'),
 ('D21', 'F14'),
 ('D21', 'M18'),
 ('D22', 'R30'),
 ('D22', 'R31'),
 ('D24', 'D25'),
 ('D24', 'R30'),
 ('D25', 'D26'),
 ('D26', 'D27'),
 ('D26', 'D28'),
 ('D26', 'S04'),
 ('D27', 'D28'),
 ('D28', 'D29'),
 ('D28', 'D31'),
 ('D29', 'D30'),
 ('D30', 'D31'),
 ('D31', 'D32'),
 ('D31', 'D35'),
 ('D32', 'D33'),
 ('D33', 'D34'),
 ('D34', 'D35'),
 ('D35', 'D37'),
 ('D35', 'D39'),
 ('D37', 'D38'),
 ('D38', 'D39'),
 ('D39', 'D40'),
 ('D40', 'D41'),
 ('D41', 'D42'),
 ('D42', 'D43'),
 ('D42', 'F39'),
 ('D43', 'N10'),
 ('F01', 'F02'),
 ('F02', 'F03'),
 ('F03', 'F04'),
 ('F04', 'F05'),
 ('F05', 'F06'),
 ('F06', 'F07'),
 ('F06', 'G07'),
 ('F06', 'G08'),
 ('F07', 'G08'),
 ('F09', 'F11'),
 ('F09', 'G21'),
 ('F11', 'F12'),
 ('F14', 'F15'),
 ('F15', 'F16'),
 ('F16', 'F18'),
 ('F20', 'F21'),
 ('F21', 'F22'),
 ('F22', 'F23'),
 ('F23', 'F24'),
 ('F24', 'F25'),
 ('F25', 'F26'),
 ('F26', 'F27'),
 ('F27', 'F29'),
 ('F29', 'F30'),
 ('F30', 'F31'),
 ('F31', 'F32'),
 ('F32', 'F33'),
 ('F33', 'F34'),
 ('F34', 'F35'),
 ('F35', 'F36'),
 ('F36', 'F38'),
 ('F38', 'F39'),
 ('G05', 'G06'),
 ('G06', 'G07'),
 ('G06', 'J12'),
 ('G08', 'G09'),
 ('G08', 'G14'),
 ('G09', 'G10'),
 ('G10', 'G11'),
 ('G11', 'G12'),
 ('G12', 'G13'),
 ('G13', 'G14'),
 ('G14', 'G15'),
 ('G14', 'G21'),
 ('G15', 'G16'),
 ('G16', 'G18'),
 ('G18', 'G19'),
 ('G19', 'G20'),
 ('G20', 'G21'),
 ('G21', 'R11'),
 ('G22', 'G24'),
 ('G24', 'G26'),
 ('G26', 'G28'),
 ('G28', 'G29'),
 ('G29', 'G30'),
 ('G30', 'G31'),
 ('G31', 'G32'),
 ('G32', 'G33'),
 ('G33', 'G34'),
 ('G34', 'G35'),
 ('G35', 'G36'),
 ('H01', 'H02'),
 ('H02', 'H03'),
 ('H03', 'H04'),
 ('H04', 'H06'),
 ('H04', 'H12'),
 ('H06', 'H07'),
 ('H07', 'H08'),
 ('H08', 'H09'),
 ('H09', 'H10'),
 ('H10', 'H11'),
 ('H12', 'H13'),
 ('H13', 'H14'),
 ('H14', 'H15'),
 ('J12', 'J13'),
 ('J13', 'J14'),
 ('J14', 'J15'),
 ('J15', 'J16'),
 ('J16', 'J17'),
 ('J17', 'J19'),
 ('J19', 'J20'),
 ('J20', 'J21'),
 ('J21', 'J22'),
 ('J22', 'J23'),
 ('J23', 'J24'),
 ('J24', 'J27'),
 ('J27', 'J28'),
 ('J28', 'J29'),
 ('J29', 'J30'),
 ('J30', 'J31'),
 ('J31', 'M11'),
 ('L01', 'L02'),
 ('L02', 'L03'),
 ('L03', 'L05'),
 ('L05', 'L06'),
 ('L06', 'L08'),
 ('L08', 'L10'),
 ('L10', 'L11'),
 ('L11', 'L12'),
 ('L12', 'L13'),
 ('L13', 'L14'),
 ('L14', 'L15'),
 ('L15', 'L16'),
 ('L16', 'L17'),
 ('L17', 'L19'),
 ('L19', 'L20'),
 ('L20', 'L21'),
 ('L21', 'L22'),
 ('L22', 'L24'),
 ('L24', 'L25'),
 ('L25', 'L26'),
 ('L26', 'L27'),
 ('L27', 'L28'),
 ('L28', 'L29'),
 ('M01', 'M04'),
 ('M04', 'M05'),
 ('M05', 'M06'),
 ('M06', 'M08'),
 ('M08', 'M09'),
 ('M09', 'M10'),
 ('M10', 'M11'),
 ('M11', 'M12'),
 ('M11', 'M16'),
 ('M12', 'M13'),
 ('M13', 'M14'),
 ('M14', 'M16'),
 ('M16', 'M18'),
 ('M18', 'M19'),
 ('M19', 'M20'),
 ('M20', 'M21'),
 ('M21', 'M22'),
 ('M22', 'M23'),
 ('N02', 'N03'),
 ('N02', 'R41'),
 ('N03', 'N04'),
 ('N04', 'N05'),
 ('N05', 'N06'),
 ('N06', 'N07'),
 ('N07', 'N08'),
 ('N08', 'N09'),
 ('N09', 'N10'),
 ('Q01', 'R20'),
 ('Q01', 'R30'),
 ('Q01', 'R31'),
 ('Q03', 'Q04'),
 ('Q04', 'Q05'),
 ('R01', 'R03'),
 ('R03', 'R04'),
 ('R04', 'R05'),
 ('R05', 'R06'),
 ('R06', 'R08'),
 ('R08', 'R09'),
 ('R09', 'R11'),
 ('R11', 'R13'),
 ('R13', 'R14'),
 ('R14', 'R15'),
 ('R14', 'R16'),
 ('R15', 'R16'),
 ('R16', 'R17'),
 ('R17', 'R18'),
 ('R17', 'R20'),
 ('R18', 'R19'),
 ('R19', 'R20'),
 ('R20', 'R21'),
 ('R21', 'R22'),
 ('R22', 'R23'),
 ('R23', 'R24'),
 ('R24', 'R25'),
 ('R25', 'R26'),
 ('R26', 'R27'),
 ('R27', 'R28'),
 ('R28', 'R29'),
 ('R29', 'R30'),
 ('R30', 'R31'),
 ('R31', 'R32'),
 ('R31', 'R36'),
 ('R32', 'R33'),
 ('R33', 'R34'),
 ('R34', 'R35'),
 ('R35', 'R36'),
 ('R36', 'R39'),
 ('R36', 'R41'),
 ('R39', 'R40'),
 ('R40', 'R41'),
 ('R41', 'R42'),
 ('R42', 'R43'),
 ('R43', 'R44'),
 ('R44', 'R45'),
 ('S01', 'S03'),
 ('S03', 'S04')}

In [ ]:
w = {e: {} for e in edge_set}
direction = {e: '' for e in edge_set}
stoptime = stoptime.groupby('trip_id', as_index=False, group_keys=False).apply(lambda x: x.sort_values('stop_sequence', ascending=True))
for name, group in stoptime.groupby('trip_id'):
	line = group.lines.values[0]
	delta = group['arrival_time'].diff()
	stop = list(zip(list(zip(group['stop_id'], group['stop_id'].shift())), delta))[1:]
	for e,t in stop:
		e = tuple(sorted(list(e)))
		try:
			w[e][line]
		except KeyError:
			w[e][line] = []
		finally:
			w[e][line].append(t)

In [291]:
def roundlist(x):
	if type(x) == list: return int(np.ceil(np.mean(x)))
	else: return x

In [292]:
all_edge_times = pd.DataFrame.from_dict(w).T
avg_times = all_edge_times.copy()
meandf = avg_times.map(lambda x: roundlist(x))
edge_weights = meandf.apply(lambda x: x.dropna().to_dict(),axis=1).to_dict()

In [293]:
def enum(x):
	i = range(len(x))
	l = [list(k) for k in zip(x, i)]
	return l

def enumone(x):
	i = range(1, len(x)+1)
	l = [list(k) for k in zip(x, i)]
	return l

In [294]:
def intersect(x,y):
	return(set(x) & set(y))

def set_diff(x,y): return(set(x) - set(y))

In [295]:
edge_weights = edge_weights | transfer_edge_weights

In [296]:
line_order = [str(s) for s in [1,2,3,4,5,6,'6X',7,'7X','A','B','C','D','E','F','G','H','J','L','M','N','Q','R','W','Z','FS','GS','Transfer']]

In [297]:
exp = pd.DataFrame(edge_weights.items(), columns=['stops', 'time'])
exp.set_index("stops", inplace=True)
exp['time'] = [list(k.items()) for k in exp['time']]
exp = exp.explode('time').reset_index()
exp['line'] = [t[0] for t in exp.time]
exp['time'] = [t[1] for t in exp.time]
exp = exp[['stops', 'line', 'time']]
exp['order'] = [line_order.index(x) for x in exp['line']]
exp = exp.sort_values('order').drop('order', axis=1)

In [298]:
exp['edge_direction'] = [direction.get(w, 'T') for w in exp['stops']]

In [299]:
exp

          stops      line   time edge_direction
41   (136, 137)         1   94.0              N
367  (121, 122)         1   76.0              N
680  (119, 120)         1  105.0              N
679  (139, 142)         1  105.0              N
342  (107, 108)         1   76.0              N
..          ...       ...    ...            ...
772  (635, R20)  Transfer  180.0              T
771  (635, L03)  Transfer  180.0              T
770  (631, 901)  Transfer  180.0              T
777  (640, M21)  Transfer  180.0              T
815  (Q01, R23)  Transfer  180.0              T

[816 rows x 4 columns]

In [300]:
exp.to_csv("edges.csv")

In [301]:
zipkey = zip(exp.stops, exp.line)
keyed = [(i[0],i[1],j) for i,j in zipkey]
edge_dict = dict({k: v for k,v in zip(keyed, exp.time)})
edge_dict

{('136', '137', '1'): 94.0,
 ('121', '122', '1'): 76.0,
 ('119', '120', '1'): 105.0,
 ('139', '142', '1'): 105.0,
 ('107', '108', '1'): 76.0,
 ('128', '129', '1'): 90.0,
 ('112', '113', '1'): 111.0,
 ('134', '135', '1'): 90.0,
 ('108', '109', '1'): 90.0,
 ('130', '131', '1'): 60.0,
 ('120', '121', '1'): 120.0,
 ('114', '115', '1'): 90.0,
 ('101', '103', '1'): 206.0,
 ('118', '119', '1'): 60.0,
 ('123', '124', '1'): 90.0,
 ('129', '130', '1'): 60.0,
 ('117', '118', '1'): 60.0,
 ('115', '116', '1'): 111.0,
 ('137', '138', '1'): 67.0,
 ('122', '123', '1'): 90.0,
 ('125', '126', '1'): 120.0,
 ('138', '139', '1'): 90.0,
 ('113', '114', '1'): 120.0,
 ('106', '107', '1'): 90.0,
 ('103', '104', '1'): 90.0,
 ('104', '106', '1'): 90.0,
 ('124', '125', '1'): 90.0,
 ('111', '112', '1'): 120.0,
 ('109', '110', '1'): 112.0,
 ('132', '133', '1'): 90.0,
 ('126', '127', '1'): 106.0,
 ('135', '136', '1'): 60.0,
 ('127', '128', '1'): 90.0,
 ('131', '132', '1'): 60.0,
 ('116', '117', '1'): 150.0,
 ('110', '111', '1'): 90.0,
 ('133', '134', '1'): 90.0,
 ('246', '247', '2'): 120.0,
 ('214', '215', '2'): 120.0,
 ('242', '243', '2'): 92.0,
 ('209', '210', '2'): 90.0,
 ('137', '228', '2'): 75.0,
 ('201', '204', '2'): 181.0,
 ('239', '241', '2'): 175.0,
 ('229', '230', '2'): 75.0,
 ('237', '238', '2'): 90.0,
 ('208', '209', '2'): 96.0,
 ('206', '207', '2'): 66.0,
 ('215', '216', '2'): 150.0,
 ('234', '235', '2'): 90.0,
 ('211', '212', '2'): 150.0,
 ('244', '245', '2'): 162.0,
 ('233', '234', '2'): 75.0,
 ('216', '217', '2'): 90.0,
 ('218', '219', '2'): 90.0,
 ('221', '222', '2'): 147.0,
 ('120', '227', '2'): 285.0,
 ('224', '225', '2'): 120.0,
 ('232', '233', '2'): 90.0,
 ('235', '236', '2'): 90.0,
 ('230', '231', '2'): 240.0,
 ('210', '211', '2'): 120.0,
 ('238', '239', '2'): 122.0,
 ('219', '220', '2'): 110.0,
 ('241', '242', '2'): 90.0,
 ('228', '229', '2'): 135.0,
 ('132', '137', '2'): 270.0,
 ('123', '127', '2'): 240.0,
 ('245', '246', '2'): 84.0,
 ('222', '224', '2'): 285.0,
 ('205', '206', '2'): 90.0,
 ('212', '213', '2'): 120.0,
 ('207', '208', '2'): 115.0,
 ('220', '221', '2'): 130.0,
 ('213', '214', '2'): 116.0,
 ('120', '123', '2'): 180.0,
 ('217', '218', '2'): 70.0,
 ('226', '227', '2'): 60.0,
 ('236', '237', '2'): 120.0,
 ('204', '205', '2'): 90.0,
 ('243', '244', '2'): 115.0,
 ('127', '128', '2'): 60.0,
 ('225', '226', '2'): 90.0,
 ('231', '232', '2'): 90.0,
 ('128', '132', '2'): 165.0,
 ('231', '232', '3'): 90.0,
 ('128', '132', '3'): 165.0,
 ('120', '123', '3'): 180.0,
 ('249', '250', '3'): 145.0,
 ('253', '254', '3'): 75.0,
 ('132', '137', '3'): 271.0,
 ('250', '251', '3'): 212.0,
 ('252', '253', '3'): 105.0,
 ('228', '229', '3'): 135.0,
 ('251', '252', '3'): 105.0,
 ('127', '128', '3'): 60.0,
 ('239', '248', '3'): 105.0,
 ('224', '302', '3'): 217.0,
 ('224', '225', '3'): 120.0,
 ('234', '235', '3'): 90.0,
 ('226', '227', '3'): 60.0,
 ('229', '230', '3'): 75.0,
 ('236', '237', '3'): 120.0,
 ('237', '238', '3'): 90.0,
 ('238', '239', '3'): 125.0,
 ('301', '302', '3'): 158.0,
 ('248', '249', '3'): 120.0,
 ('120', '227', '3'): 286.0,
 ('123', '127', '3'): 241.0,
 ('254', '255', '3'): 90.0,
 ('225', '226', '3'): 90.0,
 ('137', '228', '3'): 75.0,
 ('233', '234', '3'): 75.0,
 ('255', '256', '3'): 60.0,
 ('256', '257', '3'): 90.0,
 ('235', '236', '3'): 90.0,
 ('230', '231', '3'): 240.0,
 ('232', '233', '3'): 90.0,
 ('418', '419', '4'): 75.0,
 ('405', '406', '4'): 131.0,
 ('409', '410', '4'): 90.0,
 ('234', '235', '4'): 90.0,
 ('409', '413', '4'): 300.0,
 ('416', '621', '4'): 166.0,
 ('408', '409', '4'): 205.0,
 ('635', '640', '4'): 272.0,
 ('401', '402', '4'): 124.0,
 ('415', '416', '4'): 121.0,
 ('418', '640', '4'): 120.0,
 ('420', '423', '4'): 300.0,
 ('234', '423', '4'): 110.0,
 ('621', '626', '4'): 286.0,
 ('410', '411', '4'): 89.0,
 ('412', '413', '4'): 90.0,
 ('411', '412', '4'): 78.0,
 ('414', '415', '4'): 175.0,
 ('406', '407', '4'): 90.0,
 ('407', '408', '4'): 90.0,
 ('419', '420', '4'): 90.0,
 ('235', '239', '4'): 274.0,
 ('631', '635', '4'): 226.0,
 ('402', '405', '4'): 124.0,
 ('629', '631', '4'): 150.0,
 ('626', '629', '4'): 225.0,
 ('239', '250', '4'): 272.0,
 ('413', '414', '4'): 119.0,
 ('502', '503', '5'): 133.0,
 ('504', '505', '5'): 89.0,
 ('217', '218', '5'): 70.0,
 ('213', '505', '5'): 195.0,
 ('419', '420', '5'): 90.0,
 ('220', '221', '5'): 130.0,
 ('245', '246', '5'): 84.0,
 ('213', '214', '5'): 116.0,
 ('241', '242', '5'): 90.0,
 ('631', '635', '5'): 225.0,
 ('243', '244', '5'): 112.0,
 ('503', '504', '5'): 164.0,
 ('246', '247', '5'): 120.0,
 ('234', '423', '5'): 109.0,
 ('213', '221', '5'): 600.0,
 ('218', '219', '5'): 90.0,
 ('216', '217', '5'): 90.0,
 ('221', '222', '5'): 150.0,
 ('621', '626', '5'): 286.0,
 ('418', '640', '5'): 120.0,
 ('629', '631', '5'): 150.0,
 ('416', '621', '5'): 166.0,
 ('244', '245', '5'): 161.0,
 ('626', '629', '5'): 225.0,
 ('219', '220', '5'): 111.0,
 ('239', '241', '5'): 174.0,
 ('420', '423', '5'): 300.0,
 ('501', '502', '5'): 220.0,
 ('235', '239', '5'): 273.0,
 ('635', '640', '5'): 270.0,
 ('208', '213', '5'): 510.0,
 ('418', '419', '5'): 75.0,
 ('242', '243', '5'): 91.0,
 ('214', '215', '5'): 120.0,
 ('215', '216', '5'): 150.0,
 ('222', '416', '5'): 238.0,
 ('234', '235', '5'): 90.0,
 ('638', '639', '6'): 90.0,
 ('607', '608', '6'): 170.0,
 ('603', '604', '6'): 103.0,
 ('623', '624', '6'): 75.0,
 ('602', '603', '6'): 78.0,
 ('634', '635', '6'): 106.0,
 ('616', '617', '6'): 120.0,
 ('611', '612', '6'): 106.0,
 ('621', '622', '6'): 105.0,
 ('626', '627', '6'): 105.0,
 ('635', '636', '6'): 90.0,
 ('624', '625', '6'): 90.0,
 ('617', '618', '6'): 60.0,
 ('622', '623', '6'): 76.0,
 ('627', '628', '6'): 106.0,
 ('610', '611', '6'): 60.0,
 ('631', '632', '6'): 120.0,
 ('609', '610', '6'): 75.0,
 ('619', '621', '6'): 195.0,
 ('614', '615', '6'): 105.0,
 ('608', '609', '6'): 90.0,
 ('639', '640', '6'): 204.0,
 ('637', '638', '6'): 60.0,
 ('604', '606', '6'): 60.0,
 ('613', '614', '6'): 106.0,
 ('628', '629', '6'): 105.0,
 ('625', '626', '6'): 120.0,
 ('606', '607', '6'): 73.0,
 ('612', '613', '6'): 194.0,
 ('618', '619', '6'): 90.0,
 ('629', '630', '6'): 90.0,
 ('615', '616', '6'): 76.0,
 ('601', '602', '6'): 150.0,
 ('630', '631', '6'): 120.0,
 ('632', '633', '6'): 60.0,
 ('633', '634', '6'): 75.0,
 ('636', '637', '6'): 105.0,
 ('633', '634', '6X'): 78.0,
 ('636', '637', '6X'): 108.0,
 ('630', '631', '6X'): 120.0,
 ('632', '633', '6X'): 60.0,
 ('604', '606', '6X'): 78.0,
 ('606', '607', '6X'): 73.0,
 ('625', '626', '6X'): 120.0,
 ('628', '629', '6X'): 108.0,
 ('629', '630', '6X'): 90.0,
 ('635', '636', '6X'): 90.0,
 ('626', '627', '6X'): 108.0,
 ('637', '638', '6X'): 60.0,
 ('639', '640', '6X'): 224.0,
 ('608', '613', '6X'): 369.0,
 ('631', '632', '6X'): 120.0,
 ('624', '625', '6X'): 90.0,
 ('621', '622', '6X'): 108.0,
 ('607', '608', '6X'): 190.0,
 ('602', '603', '6X'): 73.0,
 ('627', '628', '6X'): 103.0,
 ('622', '623', '6X'): 73.0,
 ('613', '619', '6X'): 403.0,
 ('634', '635', '6X'): 103.0,
 ('619', '621', '6X'): 215.0,
 ('623', '624', '6X'): 78.0,
 ('601', '602', '6X'): 149.0,
 ('638', '639', '6X'): 90.0,
 ('603', '604', '6X'): 120.0,
 ('709', '710', '7'): 90.0,
 ('714', '715', '7'): 60.0,
 ('710', '711', '7'): 61.0,
 ('721', '723', '7'): 287.0,
 ('711', '712', '7'): 90.0,
 ('715', '716', '7'): 90.0,
 ('710', '712', '7'): 150.0,
 ('707', '708', '7'): 75.0,
 ('724', '725', '7'): 90.0,
 ('716', '718', '7'): 150.0,
 ('708', '709', '7'): 90.0,
 ('712', '714', '7'): 180.0,
 ('713', '714', '7'): 60.0,
 ('720', '721', '7'): 60.0,
 ('723', '724', '7'): 90.0,
 ('706', '707', '7'): 90.0,
 ('712', '713', '7'): 120.0,
 ('701', '702', '7'): 297.0,
 ('718', '719', '7'): 225.0,
 ('705', '706', '7'): 90.0,
 ('725', '726', '7'): 166.0,
 ('719', '720', '7'): 120.0,
 ('702', '705', '7'): 121.0,
 ('718', '719', '7X'): 180.0,
 ('720', '721', '7X'): 60.0,
 ('716', '718', '7X'): 150.0,
 ('711', '712', '7X'): 90.0,
 ('715', '716', '7X'): 90.0,
 ('714', '715', '7X'): 60.0,
 ('701', '702', '7X'): 165.0,
 ('721', '723', '7X'): 300.0,
 ('710', '711', '7X'): 90.0,
 ('713', '714', '7X'): 60.0,
 ('723', '724', '7X'): 90.0,
 ('712', '714', '7X'): 270.0,
 ('724', '725', '7X'): 90.0,
 ('719', '720', '7X'): 120.0,
 ('712', '713', '7X'): 120.0,
 ('707', '710', '7X'): 180.0,
 ('707', '712', '7X'): 270.0,
 ('725', '726', '7X'): 195.0,
 ('702', '707', '7X'): 233.0,
 ('A57', 'A59', 'A'): 90.0,
 ('A40', 'A41', 'A'): 122.0,
 ('A02', 'A03', 'A'): 176.0,
 ('A24', 'A27', 'A'): 195.0,
 ('H03', 'H04', 'A'): 448.0,
 ('A07', 'A09', 'A'): 183.0,
 ('A51', 'A55', 'A'): 326.0,
 ('H06', 'H07', 'A'): 183.0,
 ('H02', 'H03', 'A'): 124.0,
 ('A38', 'A40', 'A'): 180.0,
 ('A64', 'A65', 'A'): 75.0,
 ('H01', 'H02', 'A'): 60.0,
 ('H07', 'H08', 'A'): 194.0,
 ('A61', 'A63', 'A'): 105.0,
 ('A42', 'A46', 'A'): 286.0,
 ('A03', 'A05', 'A'): 159.0,
 ('A60', 'A61', 'A'): 90.0,
 ('A48', 'A51', 'A'): 217.0,
 ('A63', 'A64', 'A'): 220.0,
 ('A55', 'A57', 'A'): 110.0,
 ('A12', 'A15', 'A'): 228.0,
 ('H10', 'H11', 'A'): 91.0,
 ('A06', 'A07', 'A'): 76.0,
 ('A28', 'A31', 'A'): 180.0,
 ('A34', 'A36', 'A'): 117.0,
 ('A05', 'A06', 'A'): 120.0,
 ('A31', 'A32', 'A'): 139.0,
 ('A32', 'A34', 'A'): 150.0,
 ('A15', 'A24', 'A'): 466.0,
 ('H09', 'H10', 'A'): 105.0,
 ('A09', 'A12', 'A'): 224.0,
 ('A59', 'A60', 'A'): 105.0,
 ('A61', 'H02', 'A'): 210.0,
 ('A46', 'A48', 'A'): 150.0,
 ('A27', 'A28', 'A'): 91.0,
 ('A36', 'A38', 'A'): 120.0,
 ('A61', 'H01', 'A'): 180.0,
 ('A41', 'A42', 'A'): 92.0,
 ('H04', 'H06', 'A'): 305.0,
 ('H08', 'H09', 'A'): 76.0,
 ('D26', 'D28', 'B'): 120.0,
 ('D05', 'D06', 'B'): 90.0,
 ('D15', 'D16', 'B'): 90.0,
 ('A14', 'D13', 'B'): 124.0,
 ('D04', 'D05', 'B'): 120.0,
 ('A24', 'D14', 'B'): 127.0,
 ('D25', 'D26', 'B'): 185.0,
 ('D28', 'D31', 'B'): 165.0,
 ('D20', 'D21', 'B'): 150.0,
 ('D16', 'D17', 'B'): 90.0,
 ('A21', 'A22', 'B'): 90.0,
 ('A18', 'A19', 'B'): 90.0,
 ('D22', 'R30', 'B'): 491.0,
 ('A16', 'A17', 'B'): 90.0,
 ('D10', 'D11', 'B'): 120.0,
 ('D21', 'D22', 'B'): 120.0,
 ('D31', 'D35', 'B'): 330.0,
 ('D11', 'D12', 'B'): 120.0,
 ('D24', 'D25', 'B'): 150.0,
 ('D35', 'D39', 'B'): 315.0,
 ('D24', 'R30', 'B'): 150.0,
 ('A14', 'A15', 'B'): 105.0,
 ('D07', 'D08', 'B'): 90.0,
 ('D03', 'D04', 'B'): 120.0,
 ('A20', 'A21', 'B'): 90.0,
 ('D08', 'D09', 'B'): 90.0,
 ('D06', 'D07', 'B'): 105.0,
 ('A22', 'A24', 'B'): 98.0,
 ('D09', 'D10', 'B'): 120.0,
 ('A15', 'A16', 'B'): 90.0,
 ('A19', 'A20', 'B'): 90.0,
 ('D14', 'D15', 'B'): 90.0,
 ('D12', 'D13', 'B'): 122.0,
 ('A17', 'A18', 'B'): 60.0,
 ('D17', 'D20', 'B'): 195.0,
 ('D39', 'D40', 'B'): 261.0,
 ('A45', 'A46', 'C'): 60.0,
 ('A48', 'A49', 'C'): 106.0,
 ('A43', 'A44', 'C'): 90.0,
 ('A46', 'A47', 'C'): 120.0,
 ('A17', 'A18', 'C'): 60.0,
 ('A18', 'A19', 'C'): 90.0,
 ('A22', 'A24', 'C'): 90.0,
 ('A49', 'A50', 'C'): 105.0,
 ('A32', 'A33', 'C'): 107.0,
 ('A10', 'A11', 'C'): 75.0,
 ('A50', 'A51', 'C'): 89.0,
 ('A16', 'A17', 'C'): 90.0,
 ('A28', 'A30', 'C'): 120.0,
 ('A14', 'A15', 'C'): 105.0,
 ('A19', 'A20', 'C'): 90.0,
 ('A40', 'A41', 'C'): 120.0,
 ('A20', 'A21', 'C'): 90.0,
 ('A15', 'A16', 'C'): 90.0,
 ('A53', 'A54', 'C'): 105.0,
 ('A25', 'A27', 'C'): 127.0,
 ('A44', 'A45', 'C'): 90.0,
 ('A12', 'A14', 'C'): 108.0,
 ('A52', 'A53', 'C'): 90.0,
 ('A21', 'A22', 'C'): 90.0,
 ('A09', 'A10', 'C'): 75.0,
 ('A34', 'A36', 'C'): 120.0,
 ('A31', 'A32', 'C'): 135.0,
 ('A36', 'A38', 'C'): 120.0,
 ('A24', 'A25', 'C'): 116.0,
 ('A11', 'A12', 'C'): 155.0,
 ('A47', 'A48', 'C'): 90.0,
 ('A33', 'A34', 'C'): 90.0,
 ('A41', 'A42', 'C'): 90.0,
 ('A54', 'A55', 'C'): 90.0,
 ('A38', 'A40', 'C'): 181.0,
 ('A30', 'A31', 'C'): 90.0,
 ('A51', 'A52', 'C'): 212.0,
 ('A27', 'A28', 'C'): 77.0,
 ('A42', 'A43', 'C'): 120.0,
 ('D06', 'D07', 'D'): 106.0,
 ('D09', 'D10', 'D'): 120.0,
 ('A24', 'D14', 'D'): 138.0,
 ('B18', 'B19', 'D'): 90.0,
 ('D15', 'D16', 'D'): 90.0,
 ('B16', 'B17', 'D'): 120.0,
 ('D22', 'R31', 'D'): 732.0,
 ('D12', 'D13', 'D'): 120.0,
 ('B19', 'B20', 'D'): 90.0,
 ('D08', 'D09', 'D'): 90.0,
 ('A15', 'D13', 'D'): 253.0,
 ('D03', 'D04', 'D'): 179.0,
 ('B12', 'R36', 'D'): 297.0,
 ('D10', 'D11', 'D'): 120.0,
 ('R31', 'R36', 'D'): 346.0,
 ('D14', 'D15', 'D'): 90.0,
 ('B12', 'B13', 'D'): 179.0,
 ('B15', 'B16', 'D'): 90.0,
 ('B14', 'B15', 'D'): 90.0,
 ('D07', 'D08', 'D'): 90.0,
 ('B20', 'B21', 'D'): 75.0,
 ('A15', 'A24', 'D'): 465.0,
 ('B13', 'B14', 'D'): 76.0,
 ('D17', 'D20', 'D'): 198.0,
 ('D11', 'D12', 'D'): 120.0,
 ('D16', 'D17', 'D'): 90.0,
 ('D21', 'D22', 'D'): 120.0,
 ('B23', 'D43', 'D'): 321.0,
 ('D05', 'D06', 'D'): 90.0,
 ('B17', 'B18', 'D'): 90.0,
 ('B21', 'B22', 'D'): 123.0,
 ('D01', 'D03', 'D'): 254.0,
 ('B22', 'B23', 'D'): 150.0,
 ('D04', 'D05', 'D'): 120.0,
 ('D20', 'D21', 'D'): 150.0,
 ('F09', 'F11', 'E'): 180.0,
 ('D14', 'F12', 'E'): 116.0,
 ('G14', 'G21', 'E'): 330.0,
 ('F09', 'G21', 'E'): 119.0,
 ('F06', 'G08', 'E'): 167.0,
 ('G06', 'G07', 'E'): 150.0,
 ('G08', 'G14', 'E'): 345.0,
 ('A34', 'E01', 'E'): 135.0,
 ('A30', 'A31', 'E'): 90.0,
 ('A25', 'D14', 'E'): 90.0,
 ('A27', 'A28', 'E'): 75.0,
 ('F06', 'G07', 'E'): 186.0,
 ('F11', 'F12', 'E'): 90.0,
 ('A25', 'A27', 'E'): 162.0,
 ('A33', 'A34', 'E'): 92.0,
 ('G05', 'G06', 'E'): 177.0,
 ('A32', 'A33', 'E'): 105.0,
 ('A28', 'A30', 'E'): 121.0,
 ('A31', 'A32', 'E'): 136.0,
 ('D20', 'D21', 'F'): 165.0,
 ('D42', 'D43', 'F'): 90.0,
 ('F01', 'F02', 'F'): 153.0,
 ('F35', 'F36', 'F'): 245.0,
 ('F34', 'F35', 'F'): 90.0,
 ('F22', 'F23', 'F'): 106.0,
 ('D15', 'D16', 'F'): 90.0,
 ('D19', 'D20', 'F'): 106.0,
 ('F14', 'F15', 'F'): 90.0,
 ('D17', 'D18', 'F'): 120.0,
 ('F29', 'F30', 'F'): 201.0,
 ('A41', 'F20', 'F'): 199.0,
 ('F31', 'F32', 'F'): 90.0,
 ('F38', 'F39', 'F'): 215.0,
 ('B06', 'B08', 'F'): 136.0,
 ('D21', 'F14', 'F'): 90.0,
 ('F30', 'F31', 'F'): 130.0,
 ('F20', 'F21', 'F'): 105.0,
 ('F26', 'F27', 'F'): 120.0,
 ('F04', 'F05', 'F'): 136.0,
 ('F15', 'F16', 'F'): 90.0,
 ('B08', 'B10', 'F'): 150.0,
 ('F07', 'G08', 'F'): 120.0,
 ('B04', 'G14', 'F'): 382.0,
 ('G08', 'G14', 'F'): 345.0,
 ('F21', 'F22', 'F'): 120.0,
 ('F23', 'F24', 'F'): 141.0,
 ('F33', 'F34', 'F'): 90.0,
 ('F06', 'F07', 'F'): 120.0,
 ('B10', 'D15', 'F'): 120.0,
 ('F03', 'F04', 'F'): 90.0,
 ('F16', 'F18', 'F'): 150.0,
 ('F36', 'F38', 'F'): 120.0,
 ('F32', 'F33', 'F'): 90.0,
 ('F02', 'F03', 'F'): 244.0,
 ('B04', 'B06', 'F'): 127.0,
 ('F25', 'F26', 'F'): 150.0,
 ('F24', 'F25', 'F'): 90.0,
 ('D42', 'F39', 'F'): 106.0,
 ('F27', 'F29', 'F'): 120.0,
 ('D16', 'D17', 'F'): 90.0,
 ('F05', 'F06', 'F'): 120.0,
 ('D18', 'D19', 'F'): 90.0,
 ('A41', 'F18', 'F'): 120.0,
 ('A42', 'G36', 'G'): 98.0,
 ('G29', 'G30', 'G'): 75.0,
 ('F26', 'F27', 'G'): 120.0,
 ('F20', 'F21', 'G'): 105.0,
 ('F24', 'F25', 'G'): 90.0,
 ('F23', 'F24', 'G'): 140.0,
 ('G33', 'G34', 'G'): 60.0,
 ('F22', 'F23', 'G'): 105.0,
 ('G22', 'G24', 'G'): 60.0,
 ('G31', 'G32', 'G'): 90.0,
 ('A42', 'F20', 'G'): 118.0,
 ('F21', 'F22', 'G'): 120.0,
 ('F25', 'F26', 'G'): 150.0,
 ('G32', 'G33', 'G'): 90.0,
 ('G30', 'G31', 'G'): 75.0,
 ('G26', 'G28', 'G'): 90.0,
 ('G28', 'G29', 'G'): 180.0,
 ('G24', 'G26', 'G'): 150.0,
 ('G34', 'G35', 'G'): 90.0,
 ('G35', 'G36', 'G'): 90.0,
 ('H14', 'H15', 'H'): 105.0,
 ('H04', 'H12', 'H'): 226.0,
 ('H13', 'H14', 'H'): 90.0,
 ('H12', 'H13', 'H'): 117.0,
 ('M14', 'M16', 'J'): 60.0,
 ('J20', 'J21', 'J'): 120.0,
 ('G05', 'G06', 'J'): 60.0,
 ('G06', 'J12', 'J'): 329.0,
 ('J27', 'J28', 'J'): 166.0,
 ('M20', 'M21', 'J'): 105.0,
 ('M11', 'M12', 'J'): 72.0,
 ('J22', 'J23', 'J'): 90.0,
 ('M18', 'M19', 'J'): 128.0,
 ('M21', 'M22', 'J'): 78.0,
 ('J17', 'J19', 'J'): 60.0,
 ('M16', 'M18', 'J'): 450.0,
 ('J13', 'J14', 'J'): 120.0,
 ('J23', 'J24', 'J'): 90.0,
 ('J24', 'J27', 'J'): 156.0,
 ('J31', 'M11', 'J'): 90.0,
 ('M22', 'M23', 'J'): 90.0,
 ('J30', 'J31', 'J'): 90.0,
 ('J29', 'J30', 'J'): 90.0,
 ('J21', 'J22', 'J'): 60.0,
 ('J14', 'J15', 'J'): 90.0,
 ('J16', 'J17', 'J'): 90.0,
 ('J12', 'J13', 'J'): 90.0,
 ('J19', 'J20', 'J'): 120.0,
 ('M19', 'M20', 'J'): 105.0,
 ('M12', 'M13', 'J'): 90.0,
 ('J28', 'J29', 'J'): 90.0,
 ('M11', 'M16', 'J'): 240.0,
 ('J15', 'J16', 'J'): 120.0,
 ('M13', 'M14', 'J'): 79.0,
 ('L20', 'L21', 'L'): 90.0,
 ('L25', 'L26', 'L'): 90.0,
 ('L08', 'L10', 'L'): 90.0,
 ('L06', 'L08', 'L'): 210.0,
 ('L03', 'L05', 'L'): 60.0,
 ('L01', 'L02', 'L'): 76.0,
 ('L24', 'L25', 'L'): 90.0,
 ('L21', 'L22', 'L'): 65.0,
 ('L16', 'L17', 'L'): 90.0,
 ('L17', 'L19', 'L'): 91.0,
 ('L12', 'L13', 'L'): 60.0,
 ('L02', 'L03', 'L'): 90.0,
 ('L15', 'L16', 'L'): 90.0,
 ('L14', 'L15', 'L'): 120.0,
 ('L10', 'L11', 'L'): 60.0,
 ('L26', 'L27', 'L'): 90.0,
 ('L13', 'L14', 'L'): 91.0,
 ('L28', 'L29', 'L'): 131.0,
 ('L19', 'L20', 'L'): 150.0,
 ('L05', 'L06', 'L'): 60.0,
 ('L11', 'L12', 'L'): 90.0,
 ('L22', 'L24', 'L'): 112.0,
 ('L27', 'L28', 'L'): 134.0,
 ('D15', 'F12', 'M'): 150.0,
 ('D21', 'M18', 'M'): 238.0,
 ('G12', 'G13', 'M'): 90.0,
 ('M11', 'M12', 'M'): 100.0,
 ('G13', 'G14', 'M'): 138.0,
 ('M06', 'M08', 'M'): 116.0,
 ('M14', 'M16', 'M'): 60.0,
 ('G10', 'G11', 'M'): 90.0,
 ('G09', 'G10', 'M'): 90.0,
 ('G11', 'G12', 'M'): 105.0,
 ('F09', 'G21', 'M'): 128.0,
 ('G15', 'G16', 'M'): 90.0,
 ('M13', 'M14', 'M'): 76.0,
 ('D19', 'D20', 'M'): 106.0,
 ('M01', 'M04', 'M'): 150.0,
 ('G14', 'G15', 'M'): 90.0,
 ('F09', 'F11', 'M'): 181.0,
 ('D15', 'D16', 'M'): 101.0,
 ('D17', 'D18', 'M'): 120.0,
 ('G18', 'G19', 'M'): 105.0,
 ('G20', 'G21', 'M'): 123.0,
 ('G16', 'G18', 'M'): 90.0,
 ('M08', 'M09', 'M'): 121.0,
 ('M09', 'M10', 'M'): 120.0,
 ('M04', 'M05', 'M'): 90.0,
 ('F11', 'F12', 'M'): 112.0,
 ('M05', 'M06', 'M'): 90.0,
 ('G19', 'G20', 'M'): 120.0,
 ('D18', 'D19', 'M'): 90.0,
 ('D16', 'D17', 'M'): 90.0,
 ('M10', 'M11', 'M'): 120.0,
 ('M12', 'M13', 'M'): 90.0,
 ('G08', 'G09', 'M'): 120.0,
 ('M16', 'M18', 'M'): 507.0,
 ('D20', 'D21', 'M'): 165.0,
 ('N02', 'N03', 'N'): 90.0,
 ('R01', 'R03', 'N'): 120.0,
 ('R04', 'R05', 'N'): 120.0,
 ('N02', 'R41', 'N'): 180.0,
 ('N03', 'N04', 'N'): 136.0,
 ('N09', 'N10', 'N'): 102.0,
 ('D43', 'N10', 'N'): 384.0,
 ('R09', 'R11', 'N'): 288.0,
 ('R14', 'R15', 'N'): 120.0,
 ('N05', 'N06', 'N'): 90.0,
 ('R06', 'R08', 'N'): 90.0,
 ('R08', 'R09', 'N'): 172.0,
 ('R11', 'R13', 'N'): 90.0,
 ('N07', 'N08', 'N'): 120.0,
 ('R16', 'R17', 'N'): 121.0,
 ('R17', 'R20', 'N'): 169.0,
 ('Q01', 'R31', 'N'): 732.0,
 ('R31', 'R36', 'N'): 345.0,
 ('N08', 'N09', 'N'): 179.0,
 ('Q01', 'R20', 'N'): 256.0,
 ('R05', 'R06', 'N'): 90.0,
 ('R13', 'R14', 'N'): 150.0,
 ('N04', 'N05', 'N'): 90.0,
 ('R15', 'R16', 'N'): 106.0,
 ('N06', 'N07', 'N'): 90.0,
 ('R03', 'R04', 'N'): 60.0,
 ('R36', 'R41', 'N'): 241.0,
 ('D40', 'D41', 'Q'): 181.0,
 ('Q03', 'Q04', 'Q'): 120.0,
 ('D33', 'D34', 'Q'): 120.0,
 ('D42', 'D43', 'Q'): 90.0,
 ('Q04', 'Q05', 'Q'): 121.0,
 ('B08', 'R14', 'Q'): 183.0,
 ('B08', 'Q03', 'Q'): 120.0,
 ('D26', 'D27', 'Q'): 105.0,
 ('D28', 'D29', 'Q'): 105.0,
 ('D29', 'D30', 'Q'): 46.0,
 ('D32', 'D33', 'Q'): 60.0,
 ('Q01', 'R20', 'Q'): 240.0,
 ('D34', 'D35', 'Q'): 210.0,
 ('D38', 'D39', 'Q'): 120.0,
 ('D27', 'D28', 'Q'): 76.0,
 ('Q01', 'R30', 'Q'): 514.0,
 ('R16', 'R17', 'Q'): 105.0,
 ('R17', 'R20', 'Q'): 168.0,
 ('D30', 'D31', 'Q'): 105.0,
 ('D35', 'D37', 'Q'): 120.0,
 ('D24', 'R30', 'Q'): 150.0,
 ('D24', 'D25', 'Q'): 150.0,
 ('D41', 'D42', 'Q'): 105.0,
 ('R14', 'R16', 'Q'): 199.0,
 ('D37', 'D38', 'Q'): 60.0,
 ('D25', 'D26', 'Q'): 187.0,
 ('D31', 'D32', 'Q'): 90.0,
 ('D39', 'D40', 'Q'): 165.0,
 ('R16', 'R17', 'R'): 120.0,
 ('G19', 'G20', 'R'): 120.0,
 ('R17', 'R18', 'R'): 60.0,
 ('R42', 'R43', 'R'): 90.0,
 ('G16', 'G18', 'R'): 90.0,
 ('G15', 'G16', 'R'): 90.0,
 ('R31', 'R32', 'R'): 120.0,
 ('R14', 'R15', 'R'): 120.0,
 ('R35', 'R36', 'R'): 120.0,
 ('R24', 'R25', 'R'): 120.0,
 ('G13', 'G14', 'R'): 136.0,
 ('G09', 'G10', 'R'): 90.0,
 ('R18', 'R19', 'R'): 90.0,
 ('R36', 'R39', 'R'): 150.0,
 ('G20', 'G21', 'R'): 129.0,
 ('G14', 'G15', 'R'): 90.0,
 ('R11', 'R13', 'R'): 90.0,
 ('R41', 'R42', 'R'): 120.0,
 ('R33', 'R34', 'R'): 90.0,
 ('G18', 'G19', 'R'): 105.0,
 ('R13', 'R14', 'R'): 150.0,
 ('R34', 'R35', 'R'): 90.0,
 ('R40', 'R41', 'R'): 92.0,
 ('R15', 'R16', 'R'): 105.0,
 ('R19', 'R20', 'R'): 91.0,
 ('R22', 'R23', 'R'): 118.0,
 ('G11', 'G12', 'R'): 105.0,
 ('R23', 'R24', 'R'): 160.0,

In [302]:
G_adjusted = G.copy()
G_adjusted.clear_edges()
for u,v,k in edge_dict.keys():
	G_adjusted.add_edge(u,v,key=k, travel_time=edge_dict[(u,v,k)])

In [303]:
G_adjusted.get_edge_data('226','227')

{'2': {'travel_time': 60.0}, '3': {'travel_time': 60.0}}

In [304]:
G_adjusted.edges(data=True, keys=True)

MultiEdgeDataView([('127', '126', '1', {'travel_time': 106.0}), ('127', '128', '1', {'travel_time': 90.0}), ('127', '128', '2', {'travel_time': 60.0}), ('127', '128', '3', {'travel_time': 60.0}), ('127', '123', '2', {'travel_time': 240.0}), ('127', '123', '3', {'travel_time': 241.0}), ('127', '725', 'Transfer', {'travel_time': 180.0}), ('127', '902', 'Transfer', {'travel_time': 180.0}), ('127', 'A27', 'Transfer', {'travel_time': 300.0}), ('127', 'R16', 'Transfer', {'travel_time': 180.0}), ('S01', 'S03', 'FS', {'travel_time': 120.0}), ('S01', 'A45', 'Transfer', {'travel_time': 180.0}), ('254', '253', '3', {'travel_time': 75.0}), ('254', '255', '3', {'travel_time': 90.0}), ('254', 'L26', 'Transfer', {'travel_time': 300.0}), ('M01', 'M04', 'M', {'travel_time': 150.0}), ('726', '725', '7', {'travel_time': 166.0}), ('726', '725', '7X', {'travel_time': 195.0}), ('713', '714', '7', {'travel_time': 60.0}), ('713', '714', '7X', {'travel_time': 60.0}), ('713', '712', '7', {'travel_time': 120.0}), ('713', '712', '7X', {'travel_time': 120.0}), ('615', '614', '6', {'travel_time': 105.0}), ('615', '616', '6', {'travel_time': 76.0}), ('M11', 'M12', 'J', {'travel_time': 72.0}), ('M11', 'M12', 'M', {'travel_time': 100.0}), ('M11', 'J31', 'J', {'travel_time': 90.0}), ('M11', 'M16', 'J', {'travel_time': 240.0}), ('M11', 'M10', 'M', {'travel_time': 120.0}), ('F16', 'F15', 'F', {'travel_time': 90.0}), ('F16', 'F18', 'F', {'travel_time': 150.0}), ('F33', 'F34', 'F', {'travel_time': 90.0}), ('F33', 'F32', 'F', {'travel_time': 90.0}), ('233', '234', '2', {'travel_time': 75.0}), ('233', '234', '3', {'travel_time': 75.0}), ('233', '232', '2', {'travel_time': 90.0}), ('233', '232', '3', {'travel_time': 90.0}), ('M05', 'M04', 'M', {'travel_time': 90.0}), ('M05', 'M06', 'M', {'travel_time': 90.0}), ('R43', 'R42', 'R', {'travel_time': 90.0}), ('R43', 'R44', 'R', {'travel_time': 120.0}), ('A36', 'A34', 'A', {'travel_time': 117.0}), ('A36', 'A34', 'C', {'travel_time': 120.0}), ('A36', 'A38', 'A', {'travel_time': 120.0}), ('A36', 'A38', 'C', {'travel_time': 120.0}), ('A36', 'E01', 'Transfer', {'travel_time': 300.0}), ('A36', '228', 'Transfer', {'travel_time': 180.0}), ('A36', 'R25', 'Transfer', {'travel_time': 420.0}), ('604', '603', '6', {'travel_time': 103.0}), ('604', '603', '6X', {'travel_time': 120.0}), ('604', '606', '6', {'travel_time': 60.0}), ('604', '606', '6X', {'travel_time': 78.0}), ('D09', 'D08', 'B', {'travel_time': 90.0}), ('D09', 'D08', 'D', {'travel_time': 90.0}), ('D09', 'D10', 'B', {'travel_time': 120.0}), ('D09', 'D10', 'D', {'travel_time': 120.0}), ('629', '631', '4', {'travel_time': 150.0}), ('629', '631', '5', {'travel_time': 150.0}), ('629', '626', '4', {'travel_time': 225.0}), ('629', '626', '5', {'travel_time': 225.0}), ('629', '628', '6', {'travel_time': 105.0}), ('629', '628', '6X', {'travel_time': 108.0}), ('629', '630', '6', {'travel_time': 90.0}), ('629', '630', '6X', {'travel_time': 90.0}), ('629', 'R11', 'Transfer', {'travel_time': 180.0}), ('629', 'B08', 'Transfer', {'travel_time': 300.0}), ('219', '218', '2', {'travel_time': 90.0}), ('219', '218', '5', {'travel_time': 90.0}), ('219', '220', '2', {'travel_time': 110.0}), ('219', '220', '5', {'travel_time': 111.0}), ('F39', 'F38', 'F', {'travel_time': 215.0}), ('F39', 'D42', 'F', {'travel_time': 106.0}), ('N09', 'N10', 'N', {'travel_time': 102.0}), ('N09', 'N08', 'N', {'travel_time': 179.0}), ('610', '611', '6', {'travel_time': 60.0}), ('610', '609', '6', {'travel_time': 75.0}), ('F32', 'F31', 'F', {'travel_time': 90.0}), ('R13', 'R11', 'N', {'travel_time': 90.0}), ('R13', 'R11', 'R', {'travel_time': 90.0}), ('R13', 'R11', 'W', {'travel_time': 90.0}), ('R13', 'R14', 'N', {'travel_time': 150.0}), ('R13', 'R14', 'R', {'travel_time': 150.0}), ('R13', 'R14', 'W', {'travel_time': 150.0}), ('B22', 'B21', 'D', {'travel_time': 123.0}), ('B22', 'B23', 'D', {'travel_time': 150.0}), ('622', '621', '6', {'travel_time': 105.0}), ('622', '621', '6X', {'travel_time': 108.0}), ('622', '623', '6', {'travel_time': 76.0}), ('622', '623', '6X', {'travel_time': 73.0}), ('H14', 'H15', 'H', {'travel_time': 105.0}), ('H14', 'H13', 'H', {'travel_time': 90.0}), ('F05', 'F04', 'F', {'travel_time': 136.0}), ('F05', 'F06', 'F', {'travel_time': 120.0}), ('R19', 'R18', 'R', {'travel_time': 90.0}), ('R19', 'R18', 'W', {'travel_time': 90.0}), ('R19', 'R20', 'R', {'travel_time': 91.0}), ('R19', 'R20', 'W', {'travel_time': 92.0}), ('R18', 'R17', 'R', {'travel_time': 60.0}), ('R18', 'R17', 'W', {'travel_time': 62.0}), ('114', '115', '1', {'travel_time': 90.0}), ('114', '113', '1', {'travel_time': 120.0}), ('A03', 'A02', 'A', {'travel_time': 176.0}), ('A03', 'A05', 'A', {'travel_time': 159.0}), ('M16', 'M14', 'J', {'travel_time': 60.0}), ('M16', 'M14', 'M', {'travel_time': 60.0}), ('M16', 'M18', 'J', {'travel_time': 450.0}), ('M16', 'M18', 'M', {'travel_time': 507.0}), ('720', '721', '7', {'travel_time': 60.0}), ('720', '721', '7X', {'travel_time': 60.0}), ('720', '719', '7', {'travel_time': 120.0}), ('720', '719', '7X', {'travel_time': 120.0}), ('A16', 'A17', 'B', {'travel_time': 90.0}), ('A16', 'A17', 'C', {'travel_time': 90.0}), ('A16', 'A15', 'B', {'travel_time': 90.0}), ('A16', 'A15', 'C', {'travel_time': 90.0}), ('A41', 'A40', 'A', {'travel_time': 122.0}), ('A41', 'A40', 'C', {'travel_time': 120.0}), ('A41', 'A42', 'A', {'travel_time': 92.0}), ('A41', 'A42', 'C', {'travel_time': 90.0}), ('A41', 'F20', 'F', {'travel_time': 199.0}), ('A41', 'F18', 'F', {'travel_time': 120.0}), ('A41', 'R29', 'Transfer', {'travel_time': 90.0}), ('R39', 'R36', 'R', {'travel_time': 150.0}), ('R39', 'R40', 'R', {'travel_time': 90.0}), ('A52', 'A53', 'C', {'travel_time': 90.0}), ('A52', 'A51', 'C', {'travel_time': 212.0}), ('G34', 'G33', 'G', {'travel_time': 60.0}), ('G34', 'G35', 'G', {'travel_time': 90.0}), ('D30', 'D29', 'Q', {'travel_time': 46.0}), ('D30', 'D31', 'Q', {'travel_time': 105.0}), ('G20', 'G21', 'M', {'travel_time': 123.0}), ('G20', 'G21', 'R', {'travel_time': 129.0}), ('G20', 'G19', 'M', {'travel_time': 120.0}), ('G20', 'G19', 'R', {'travel_time': 120.0}), ('418', '419', '4', {'travel_time': 75.0}), ('418', '419', '5', {'travel_time': 75.0}), ('418', '640', '4', {'travel_time': 120.0}), ('418', '640', '5', {'travel_time': 120.0}), ('418', 'A38', 'Transfer', {'travel_time': 180.0}), ('418', 'M22', 'Transfer', {'travel_time': 300.0}), ('418', '229', 'Transfer', {'travel_time': 300.0}), ('212', '211', '2', {'travel_time': 150.0}), ('212', '213', '2', {'travel_time': 120.0}), ('503', '502', '5', {'travel_time': 133.0}), ('503', '504', '5', {'travel_time': 164.0}), ('B18', 'B19', 'D', {'travel_time': 90.0}), ('B18', 'B17', 'D', {'travel_time': 90.0}), ('G29', 'G30', 'G', {'travel_time': 75.0}), ('G29', 'G28', 'G', {'travel_time': 180.0}), ('G29', 'L10', 'Transfer', {'travel_time': 180.0}), ('G21', 'G14', 'E', {'travel_time': 330.0}), ('G21', 'F09', 'E', {'travel_time': 119.0}), ('G21', 'F09', 'M', {'travel_time': 128.0}), ('G21', 'R11', 'R', {'travel_time': 360.0}), ('406', '405', '4', {'travel_time': 131.0}), ('406', '407', '4', {'travel_time': 90.0}), ('R23', 'R22', 'R', {'travel_time': 118.0}), ('R23', 'R22', 'W', {'travel_time': 100.0}), ('R23', 'R24', 'R', {'travel_time': 160.0}), ('R23', 'R24', 'W', {'travel_time': 177.0}), ('R23', 'M20', 'Transfer', {'travel_time': 300.0}), ('R23', '639', 'Transfer', {'travel_time': 180.0}), ('R23', 'Q01', 'Transfer', {'travel_time': 180.0}), ('110', '109', '1', {'travel_time': 112.0}), ('110', '111', '1', {'travel_time': 90.0}), ('G09', 'G10', 'M', {'travel_time': 90.0}), ('G09', 'G10', 'R', {'travel_time': 90.0}), ('G09', 'G08', 'M', {'travel_time': 120.0}), ('G09', 'G08', 'R', {'travel_time': 120.0}), ('A51', 'A55', 'A', {'travel_time': 326.0}), ('A51', 'A48', 'A', {'travel_time': 217.0}), ('A51', 'A50', 'C', {'travel_time': 89.0}), ('A51', 'J27', 'Transfer', {'travel_time': 180.0}), ('A51', 'L22', 'Transfer', {'travel_time': 180.0}), ('R01', 'R03', 'N', {'travel_time': 120.0}), ('R01', 'R03', 'W', {'travel_time': 120.0}), ('246', '247', '2', {'travel_time': 120.0}), ('246', '247', '5', {'travel_time': 120.0}), ('246', '245', '2', {'travel_time': 84.0}), ('246', '245', '5', {'travel_time': 84.0}), ('L15', 'L16', 'L', {'travel_time': 90.0}), ('L15', 'L14', 'L', {'travel_time': 120.0}), ('725', '724', '7', {'travel_time': 90.0}), ('725', '724', '7X', {'travel_time': 90.0}), ('725', 'R16', 'Transfer', {'travel_time': 180.0}), ('725', 'A27', 'Transfer', {'travel_time': 180.0}), ('725', '902', 'Transfer', {'travel_time': 300.0}), ('H01', 'H02', 'A', {'travel_time': 60.0}), ('H01', 'A61', 'A', {'travel_time': 180.0}), ('J22', 'J23', 'J', {'travel_time': 90.0}), ('J22', 'J21', 'J', {'travel_time': 60.0}), ('A20', 'A21', 'B', {'travel_time': 90.0}), ('A20', 'A21', 'C', {'travel_time': 90.0}), ('A20', 'A19', 'B', {'travel_time': 90.0}), ('A20', 'A19', 'C', {'travel_time': 90.0}), ('A57', 'A59', 'A', {'travel_time': 90.0}), ('A57', 'A55', 'A', {'travel_time': 110.0}), ('G15', 'G16', 'M', {'travel_time': 90.0}), ('G15', 'G16', 'R', {'travel_time': 90.0}), ('G15', 'G14', 'M', {'travel_time': 90.0}), ('G15', 'G14', 'R', {'travel_time': 90.0}), ('D34', 'D33', 'Q', {'travel_time': 120.0}), ('D34', 'D35', 'Q', {'travel_time': 210.0}), ('103', '101', '1', {'travel_time': 206.0}), ('103', '104', '1', {'travel_time': 90.0}), ('238', '237', '2', {'travel_time': 90.0}), ('238', '237', '3', {'travel_time': 90.0}), ('238', '239', '2', {'travel_time': 122.0}), ('238', '239', '3', {'travel_time': 125.0}), ('637', '638', '6', {'travel_time': 60.0}), ('637', '638', '6X', {'travel_time': 60.0}), ('637', '636', '6', {'travel_time': 105.0}), ('637', '636', '6X', {'travel_time': 108.0}), ('637', 'D21', 'Transfer', {'travel_time': 180.0}), ('D29', 'D28', 'Q', {'travel_time': 105.0}), ('705', '706', '7', {'travel_time': 90.0}), ('705', '702', '7', {'travel_time': 121.0}), ('A15', 'A12', 'A', {'travel_time': 228.0}), ('A15', 'A24', 'A', {'travel_time': 466.0}), ('A15', 'A24', 'D', {'travel_time': 465.0}), ('A15', 'A14', 'B', {'travel_time': 105.0}), ('A15', 'A14', 'C', {'travel_time': 105.0}), ('A15', 'D13', 'D', {'travel_time': 253.0}), ('D18', 'D17', 'F', {'travel_time': 120.0}), ('D18', 'D17', 'M', {'travel_time': 120.0}), ('D18', 'D19', 'F', {'travel_time': 90.0}), ('D18', 'D19', 'M', {'travel_time': 90.0}), ('419', '420', '4', {'travel_time': 90.0}), ('419', '420', '5', {'travel_time': 90.0}), ('N08', 'N07', 'N', {'travel_time': 120.0}), ('115', '116', '1', {'travel_time': 111.0}), ('226', '227', '2', {'travel_time': 60.0}), ('226', '227', '3', {'travel_time': 60.0}), ('226', '225', '2', {'travel_time': 90.0}), ('226', '225', '3', {'travel_time': 90.0}), ('136', '137', '1', {'travel_time': 94.0}), ('136', '135', '1', {'travel_time': 60.0}), ('410', '409', '4', {'travel_time': 90.0}), ('410', '411', '4', {'travel_time': 89.0}), ('D14', 'A24', 'B', {'travel_time': 127.0}), ('D14', 'A24', 'D', {'travel_time': 138.0}), ('D14', 'D15', 'B', {'travel_time': 90.0}), ('D14', 'D15', 'D', {'travel_time': 90.0}), ('D14', 'F12', 'E', {'travel_time': 116.0}), ('D14', 'A25', 'E', {'travel_time': 90.0}), ('D08', 'D07', 'B', {'travel_time': 90.0}), ('D08', 'D07', 'D', {'travel_time': 90.0}), ('M20', 'M21', 'J', {'travel_time': 105.0}), ('M20', 'M19', 'J', {'travel_time': 105.0}), ('M20', 'Q01', 'Transfer', {'travel_time': 180.0}), ('M20', '639', 'Transfer', {'travel_time': 180.0}), ('L10', 'L08', 'L', {'travel_time': 90.0}), ('L10', 'L11', 'L', {'travel_time': 60.0}), ('A30', 'A28', 'C', {'travel_time': 120.0}), ('A30', 'A28', 'E', {'travel_time': 121.0}), ('A30', 'A31', 'C', {'travel_time': 90.0}), ('A30', 'A31', 'E', {'travel_time': 90.0}), ('A46', 'A42', 'A', {'travel_time': 286.0}), ('A46', 'A48', 'A', {'travel_time': 150.0}), ('A46', 'A45', 'C', {'travel_time': 60.0}), ('A46', 'A47', 'C', {'travel_time': 120.0}), ('N03', 'N02', 'N', {'travel_time': 90.0}), ('N03', 'N04', 'N', {'travel_time': 136.0}), ('504', '505', '5', {'travel_time': 89.0}), ('R06', 'R08', 'N', {'travel_time': 90.0}), ('R06', 'R08', 'W', {'travel_time': 90.0}), ('R06', 'R05', 'N', {'travel_time': 90.0}), ('R06', 'R05', 'W', {'travel_time': 90.0}), ('D03', 'D04', 'B', {'travel_time': 120.0}), ('D03', 'D04', 'D', {'travel_time': 179.0}), ('D03', 'D01', 'D', {'travel_time': 254.0}), ('619', '621', '6', {'travel_time': 195.0}), ('619', '621', '6X', {'travel_time': 215.0}), ('619', '618', '6', {'travel_time': 90.0}), ('619', '613', '6X', {'travel_time': 403.0}), ('M10', 'M09', 'M', {'travel_time': 120.0}), ('242', '243', '2', {'travel_time': 92.0}), ('242', '243', '5', {'travel_time': 91.0}), ('242', '241', '2', {'travel_time': 90.0}), ('242', '241', '5', {'travel_time': 90.0}), ('F22', 'F23', 'F', {'travel_time': 106.0}), ('F22', 'F23', 'G', {'travel_time': 105.0}), ('F22', 'F21', 'F', {'travel_time': 120.0}), ('F22', 'F21', 'G', {'travel_time': 120.0}), ('611', '612', '6', {'travel_time': 106.0}), ('Q05', 'Q04', 'Q', {'travel_time': 121.0}), ('229', '230', '2', {'travel_time': 75.0}), ('229', '230', '3', {'travel_time': 75.0}), ('229', '228', '2', {'travel_time': 135.0}), ('229', '228', '3', {'travel_time': 135.0}), ('229', 'A38', 'Transfer', {'travel_time': 180.0}), ('229', 'M22', 'Transfer', {'travel_time': 300.0}), ('A10', 'A11', 'C', {'travel_time': 75.0}), ('A10', 'A09', 'C', {'travel_time': 75.0}), ('R30', 'D22', 'B', {'travel_time': 491.0}), ('R30', 'D24', 'B', {'travel_time': 150.0}), ('R30', 'D24', 'Q', {'travel_time': 150.0}), ('R30', 'Q01', 'Q', {'travel_time': 514.0}), ('R30', 'R31', 'R', {'travel_time': 187.0}), ('R30', 'R29', 'R', {'travel_time': 105.0}), ('633', '632', '6', {'travel_time': 60.0}), ('633', '632', '6X', {'travel_time': 60.0}), ('633', '634', '6', {'travel_time': 75.0}), ('633', '634', '6X', {'travel_time': 78.0}), ('119', '120', '1', {'travel_time': 105.0}), ('119', '118', '1', {'travel_time': 60.0}), ('B04', 'G14', 'F', {'travel_time': 382.0}), ('B04', 'B06', 'F', {'travel_time': 127.0}), ('204', '201', '2', {'travel_time': 181.0}), ('204', '205', '2', {'travel_time': 90.0}), ('J14', 'J13', 'J', {'travel_time': 120.0}), ('J14', 'J15', 'J', {'travel_time': 90.0}), ('L24', 'L25', 'L', {'travel_time': 90.0}), ('L24', 'L22', 'L', {'travel_time': 112.0}), ('R29', 'R28', 'R', {'travel_time': 120.0}), ('234', '235', '2', {'travel_time': 90.0}), ('234', '235', '3', {'travel_time': 90.0}), ('234', '235', '4', {'travel_time': 90.0}), ('234', '235', '5', {'travel_time': 90.0}), ('234', '423', '4', {'travel_time': 110.0}), ('234', '423', '5', {'travel_time': 109.0}), ('L25', 'L26', 'L', {'travel_time': 90.0}), ('D24', 'D25', 'B', {'travel_time': 150.0}), ('D24', 'D25', 'Q', {'travel_time': 150.0}), ('D24', 'R31', 'Transfer', {'travel_time': 300.0}), ('D24', '235', 'Transfer', {'travel_time': 180.0}), ('606', '607', '6', {'travel_time': 73.0}), ('606', '607', '6X', {'travel_time': 73.0}), ('F27', 'F26', 'F', {'travel_time': 120.0}), ('F27', 'F26', 'G', {'travel_time': 120.0}), ('F27', 'F29', 'F', {'travel_time': 120.0}), ('D42', 'D43', 'F', {'travel_time': 90.0}), ('D42', 'D43', 'Q', {'travel_time': 90.0}), ('D42', 'D41', 'Q', {'travel_time': 105.0}), ('F34', 'F35', 'F', {'travel_time': 90.0}), ('414', '415', '4', {'travel_time': 175.0}), ('414', '413', '4', {'travel_time': 119.0}), ('414', 'D11', 'Transfer', {'travel_time': 180.0}), ('301', '302', '3', {'travel_time': 158.0}), ('132', '133', '1', {'travel_time': 90.0}), ('132', '131', '1', {'travel_time': 60.0}), ('132', '137', '2', {'travel_time': 270.0}), ('132', '137', '3', {'travel_time': 271.0}), ('132', '128', '2', {'travel_time': 165.0}), ('132', '128', '3', {'travel_time': 165.0}), ('132', 'D19', 'Transfer', {'travel_time': 300.0}), ('132', 'L02', 'Transfer', {'travel_time': 180.0}), ('H08', 'H07', 'A', {'travel_time': 194.0}), ('H08', 'H09', 'A', {'travel_time': 76.0}), ('218', '217', '2', {'travel_time': 70.0}), ('218', '217', '5', {'travel_time': 70.0}), ('F15', 'F14', 'F', {'travel_time': 90.0}), ('F15', 'M18', 'Transfer', {'travel_time': 180.0}), ('J13', 'J12', 'J', {'travel_time': 90.0}), ('F01', 'F02', 'F', {'travel_time': 153.0}), ('614', '613', '6', {'travel_time': 106.0}), ('118', '117', '1', {'travel_time': 60.0}), ('R14', 'R15', 'N', {'travel_time': 120.0}), ('R14', 'R15', 'R', {'travel_time': 120.0}), ('R14', 'R15', 'W', {'travel_time': 120.0}), ('R14', 'B08', 'Q', {'travel_time': 183.0}), ('R14', 'R16', 'Q', {'travel_time': 199.0}), ('607', '608', '6', {'travel_time': 170.0}), ('607', '608', '6X', {'travel_time': 190.0}), ('B21', 'B20', 'D', {'travel_time': 75.0}), ('623', '624', '6', {'travel_time': 75.0}), ('623', '624', '6X', {'travel_time': 78.0}), ('230', '231', '2', {'travel_time': 240.0}), ('230', '231', '3', {'travel_time': 240.0}), ('H13', 'H12', 'H', {'travel_time': 117.0}), ('R15', 'R16', 'N', {'travel_time': 106.0}), ('R15', 'R16', 'R', {'travel_time': 105.0}), ('R15', 'R16', 'W', {'travel_time': 105.0}), ('D12', 'D11', 'B', {'travel_time': 120.0}), ('D12', 'D11', 'D', {'travel_time': 120.0}), ('D12', 'D13', 'B', {'travel_time': 122.0}), ('D12', 'D13', 'D', {'travel_time': 120.0}), ('255', '256', '3', {'travel_time': 60.0}), ('714', '715', '7', {'travel_time': 60.0}), ('714', '715', '7X', {'travel_time': 60.0}), ('714', '712', '7', {'travel_time': 180.0}), ('714', '712', '7X', {'travel_time': 270.0}), ('213', '214', '2', {'travel_time': 116.0}), ('213', '214', '5', {'travel_time': 116.0}), ('213', '505', '5', {'travel_time': 195.0}), ('213', '221', '5', {'travel_time': 600.0}), ('213', '208', '5', {'travel_time': 510.0}), ('409', '413', '4', {'travel_time': 300.0}), ('409', '408', '4', {'travel_time': 205.0}), ('Q04', 'Q03', 'Q', {'travel_time': 120.0}), ('F12', 'F11', 'E', {'travel_time': 90.0}), ('F12', 'F11', 'M', {'travel_time': 112.0}), ('F12', 'D15', 'M', {'travel_time': 150.0}), ('G30', 'G31', 'G', {'travel_time': 75.0}), ('A24', 'A27', 'A', {'travel_time': 195.0}), ('A24', 'A22', 'B', {'travel_time': 98.0}), ('A24', 'A22', 'C', {'travel_time': 90.0}), ('A24', 'A25', 'C', {'travel_time': 116.0}), ('A24', '125', 'Transfer', {'travel_time': 180.0}), ('R25', 'R24', 'R', {'travel_time': 120.0}), ('R25', 'R24', 'W', {'travel_time': 120.0}), ('R25', 'R26', 'R', {'travel_time': 75.0}), ('R25', 'R26', 'W', {'travel_time': 75.0}), ('R25', 'E01', 'Transfer', {'travel_time': 240.0}), ('R25', '228', 'Transfer', {'travel_time': 420.0}), ('208', '209', '2', {'travel_time': 96.0}), ('208', '207', '2', {'travel_time': 115.0}), ('128', '129', '1', {'travel_time': 90.0}), ('D38', 'D39', 'Q', {'travel_time': 120.0}), ('D38', 'D37', 'Q', {'travel_time': 60.0}), ('A61', 'A63', 'A', {'travel_time': 105.0}), ('A61', 'A60', 'A', {'travel_time': 90.0}), ('A61', 'H02', 'A', {'travel_time': 210.0}), ('R42', 'R41', 'R', {'travel_time': 120.0}), ('D43', 'B23', 'D', {'travel_time': 321.0}), ('D43', 'N10', 'N', {'travel_time': 384.0}), ('628', '627', '6', {'travel_time': 106.0}), ('628', '627', '6X', {'travel_time': 103.0}), ('G16', 'G18', 'M', {'travel_time': 90.0}), ('G16', 'G18', 'R', {'travel_time': 90.0}), ('L29', 'L28', 'L', {'travel_time': 131.0}), ('A31', 'A28', 'A', {'travel_time': 180.0}), ('A31', 'A32', 'A', {'travel_time': 139.0}), ('A31', 'A32', 'C', {'travel_time': 135.0}), ('A31', 'A32', 'E', {'travel_time': 136.0}), ('A31', 'L01', 'Transfer', {'travel_time': 90.0}), ('G22', 'G24', 'G', {'travel_time': 60.0}), ('G22', 'F09', 'Transfer', {'travel_time': 180.0}), ('G22', '719', 'Transfer', {'travel_time': 180.0}), ('237', '236', '2', {'travel_time': 120.0}), ('237', '236', '3', {'travel_time': 120.0}), ('J31', 'J30', 'J', {'travel_time': 90.0}), ('D19', 'D20', 'F', {'travel_time': 106.0}), ('D19', 'D20', 'M', {'travel_time': 106.0}), ('D19', 'L02', 'Transfer', {'travel_time': 180.0}), ('M09', 'M08', 'M', {'travel_time': 121.0}), ('618', '617', '6', {'travel_time': 60.0}), ('H02', 'H03', 'A', {'travel_time': 124.0}), ('123', '124', '1', {'travel_time': 90.0}), ('123', '122', '1', {'travel_time': 90.0}), ('123', '120', '2', {'travel_time': 180.0}

In [305]:
# fix edge to gun hill road
G_adjusted.remove_edge('208', '213')

In [306]:
G_adjusted['710']

AdjacencyView({'709': {'7': {'travel_time': 90.0}}, '711': {'7': {'travel_time': 61.0}, '7X': {'travel_time': 90.0}}, '712': {'7': {'travel_time': 150.0}}, '707': {'7X': {'travel_time': 180.0}}, 'G14': {'Transfer': {'travel_time': 180.0}}})

In [307]:
ndfa = pd.DataFrame(dict(G_adjusted.nodes.data())).T
ndfa.drop('lines', axis=1, inplace=True)
ndfa['wait_time'] = [[[k,v] for k,v in q.items()] for q in ndfa['wait_time']]
ndfa = ndfa.explode('wait_time').reset_index(drop=True)
ndfa = pd.concat([ndfa, pd.DataFrame(list(ndfa['wait_time']), columns=['line', 'time'])], axis=1).drop('wait_time', axis=1)
ndfa = ndfa.sort_values('time')
ndfa

    GTFS Stop ID Complex ID                 Stop Name line      time
585          L13        124               Montrose Av    L   265.068
498          L06        119                      1 Av    L   265.068
508          L02        601                      6 Av    L   265.068
441          L12        123                  Grand St    L   265.068
297          L05        118                      3 Av    L   265.068
..           ...        ...                       ...  ...       ...
324          H07        205               Beach 60 St    A  1004.000
539          H04        199             Broad Channel    A  1008.285
458          H03        198  Howard Beach-JFK Airport    A  1008.285
246          H02        197     Aqueduct-N Conduit Av    A  1008.285
374          H06        204               Beach 67 St    A  1008.285

[757 rows x 5 columns]

## export

In [308]:
import json

def serialize(obj):
    if isinstance(obj, np.int64):
         return int(obj)
    if not isinstance(obj, (str, int, float, bool)):
        return list(obj)
    else: return obj

G_adjusted.name = "NYC Subway_multi-edge"
try: del G_adjusted.graph['crs']
except KeyError:
	pass
data1 = nx.node_link_data(G_adjusted, edges="edges")
with open('subwaygraph_midday.json', 'w') as f:
    json.dump(data1,f, default=serialize)