In [268]:
import pandas as pd
from pandas import DataFrame
import numpy as np
import networkx as nx
import peartree as pear
import partridge as ptg
import matplotlib.pyplot as plt
import itertools
import warnings
import json
warnings.filterwarnings('ignore')

In [269]:
feed_all = pear.get_representative_feed("gtfs_subway/")
feed = feed_all

In [270]:
def iterator(L):
	a, b = itertools.tee(L)
	next(b, None)
	return list(zip(a,b))

In [271]:
def enum(x):
	i = range(len(x))
	l = [list(k) for k in zip(x, i)]
	return l

def enumone(x):
	i = range(1, len(x)+1)
	l = [list(k) for k in zip(x, i)]
	return l

def intersect(x,y):
	return(set(x) & set(y))

def set_diff(x,y): return(set(x) - set(y))

In [272]:
station_data = pd.read_csv("data/MTA_Subway_Stations.csv")
station_data = station_data[['GTFS Stop ID', 'Complex ID', 'Stop Name', 'Daytime Routes']]

rl = [str(r).split() for r in station_data['Daytime Routes']]
station_data['Daytime Routes'] = rl

# remove Staten Island Railroad

station_data = station_data[station_data['Daytime Routes'].apply(lambda x: "SIR" not in x)]
station_data.set_index('GTFS Stop ID', drop=False, inplace=True)
nodes_list = [(k, v) for k,v in station_data.to_dict('index').items()]

In [273]:
line_names = [str(s) for s in [1,2,3,4,5,6,'6X',7,'7X','A','B','C','D','E','F','FX','G','H','J','L','M','N','Q','R','W','Z','FS','GS','Transfer']]

In [274]:
line_order = sorted(line_names)
line_order

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '6X',
 '7',
 '7X',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'FS',
 'FX',
 'G',
 'GS',
 'H',
 'J',
 'L',
 'M',
 'N',
 'Q',
 'R',
 'Transfer',
 'W',
 'Z']

In [275]:
## transfers in complex
transfers = pd.read_csv('gtfs_subway/transfers.txt')
	
transfers.drop("transfer_type", inplace=True, axis=1)

transfers = transfers[transfers['from_stop_id'] != transfers['to_stop_id']]
transfers.reset_index(inplace=True,drop=True)
transfers

    from_stop_id to_stop_id  min_transfer_time
0            112        A09                180
1            125        A24                180
2            127        725                180
3            127        902                180
4            127        A27                300
..           ...        ...                ...
147          R31        235                180
148          R31        D24                300
149          R33        F23                180
150          S01        A45                180
151          S04        239                180

[152 rows x 3 columns]

In [276]:
complexes = pd.read_csv("data/MTA_Subway_Stations_and_Complexes_20250918.csv")
complexes = complexes[complexes['Number Of Stations In Complex'] > 1]
complexes = complexes[['Complex ID','Number Of Stations In Complex', 'GTFS Stop IDs']]
gtfs_ids = [ids.split("; ") for ids in complexes['GTFS Stop IDs']]
complex_pairs = [list(itertools.combinations(sts, 2)) for sts in gtfs_ids]
complexes['complex_transfers'] = complex_pairs
complexes = complexes.explode('complex_transfers', ignore_index=True).drop(['Number Of Stations In Complex','GTFS Stop IDs'], axis= 1)
transfer_edges = list(zip(transfers['from_stop_id'], transfers['to_stop_id']))
transfer_edge_set = set()
for k in transfer_edges:
	transfer_edge_set.add(tuple(sorted(k)))

##print(transfer_edge_set ^ set(complexes['complex_transfers']))
##('254', 'L26'), ('629', 'B08'), ('B08', 'R11')##

## Out of station transfers specified on the official map
## Walk Junius to Livonia
## Walk Lexington-59 NRW to Lexington-63 -- 300s
## walk Lexington-59 456 to Lexington-63 -- 300s
transfers['edges'] = [tuple(sorted(k)) for k in transfer_edges]
unique_transfers = transfers.sort_values('edges').iloc[::2,:]
unique_transfers.reset_index(drop=True,inplace=True)
unique_transfers.drop(['from_stop_id', 'to_stop_id'], axis=1, inplace=True)

In [277]:
unique_transfers.edges.to_csv('transfer_edges.csv')

In [278]:
fstop = [unique_transfers['edges'][k][0] for k in unique_transfers.index]
tstop = [unique_transfers['edges'][k][1] for k in unique_transfers.index]
ttime = unique_transfers['min_transfer_time']
transfer_edge_weights = {(a, b): {"Transfer": t} for a,b,t in list(zip(fstop, tstop, ttime))}

### Fix edge weights so that boarding cost varies by line

In [279]:
start_time_am = int(6.5 * 60 * 60)
end_time_am = int(9.5 * 60 * 60)

In [280]:
start_time_pm = int(15.5 * 60 * 60)
end_time_pm = int(20 * 60 * 60)
tripline = list(feed.stop_times['trip_id'])
inseq = feed.stop_times.copy()
tripdict = {k: v for k,v in zip(feed.trips['trip_id'], feed.trips['route_id'])}
feed.stop_times['lines'] = [tripdict[s] for s in feed.stop_times['trip_id']]
feed.stop_times['dir'] = [s[-4] if s[-4] != 'X' else s[-7] for s in feed.stop_times['trip_id']]
stoptime_a = pd.DataFrame(feed.stop_times).copy()
stoptime_morning = stoptime_a[stoptime_a['arrival_time'].between(start_time_am, end_time_am, inclusive='both')]
stoptime_evening = stoptime_a[stoptime_a['arrival_time'].between(start_time_pm, end_time_pm, inclusive='both')]

In [281]:
def graphify(stoptime: DataFrame, debug=False):
	stoptime = stoptime[stoptime['lines'] != 'SI']
	stoptime.sort_values(['stop_id','lines', 'dir', 'arrival_time'], inplace=True)
	seq_dict = {}
	for n, g in inseq.groupby('trip_id'):
		seq_dict[n] = len(g['stop_sequence'])
	stoptime.sort_values('trip_id', inplace=True)
	stoptime['trip_len'] = [seq_dict[n] for n in stoptime['trip_id']]
	stops_in_time = dict(stoptime.trip_id.value_counts())
	stoptime['count_in_timespan'] = [stops_in_time[n] for n in stoptime.trip_id]
	stoptime = stoptime[stoptime['count_in_timespan'] == stoptime['trip_len']]
	stgroups = stoptime.groupby(['stop_id', 'lines','dir'], group_keys=True)
	st_weights = pd.DataFrame(list(stgroups.groups.keys()),index=list(stgroups.groups.keys()), columns=['stop', 'line', 'dir']).reset_index(drop=False)
	st_weights['weight'] = 0
	i = 0
	for name, group in stgroups:
		waittime = iterator(list(group['arrival_time']))
		dirw = round(np.mean([b-a for a,b in waittime]), 3)
		st_weights.at[i, 'weight'] = dirw
		i += 1


	st_weights = st_weights.groupby(['stop','line'], as_index=False).mean('weight')
	st_weights.sort_values('stop', inplace=True)

	node_weight_dict = {}
	for name, group in st_weights.groupby(['stop'],group_keys=True):
		float_w = dict(zip(group['line'], group['weight']))
		float_w = {k: round(v,3) for k,v in float_w.items()}
		node_weight_dict[name[0]] = float_w
	
	stops_per_line = stoptime.sort_values(['lines','trip_len'])
	stops_per_line = stops_per_line.groupby('trip_id', group_keys=False).apply(lambda x: x.sort_values('stop_sequence'))
	edge_set = set()
	for name, group in stops_per_line.groupby('trip_id'):
		edges = iterator(group.stop_id.to_list())
		for k in edges:
			edge_set.add(tuple(sorted(k)))
	
	w = {e: {} for e in edge_set}
	direction = {e: '' for e in edge_set}
	stoptime = stoptime.groupby('trip_id', as_index=False, group_keys=False).apply(lambda x: x.sort_values('stop_sequence', ascending=True))
	for name, group in stoptime.groupby('trip_id'):
		line = group.lines.values[0]
		delta = group['arrival_time'].diff()
		stop = list(zip(list(zip(group['stop_id'], group['stop_id'].shift())), delta))[1:]
		for e,t in stop:
			e = tuple(sorted(list(e)))
			try:
				w[e][line]
			except KeyError:
				w[e][line] = []
			finally:
				w[e][line].append(t)

	def roundlist(x):
		if type(x) == list: return int(np.ceil(np.mean(x)))
		else: return x

	all_edge_times = pd.DataFrame.from_dict(w).T
	avg_times = all_edge_times.copy()
	meandf = avg_times.map(lambda x: roundlist(x))
	edge_weights = meandf.apply(lambda x: x.dropna().to_dict(),axis=1).to_dict()
	edge_weights = edge_weights | transfer_edge_weights
	exp = pd.DataFrame(edge_weights.items(), columns=['stops', 'time'])
	exp.set_index("stops", inplace=True)
	exp['time'] = [list(k.items()) for k in exp['time']]
	exp = exp.explode('time').reset_index()
	exp['line'] = [t[0] for t in exp.time]
	exp['time'] = [t[1] for t in exp.time]
	exp = exp[['stops', 'line', 'time']]
	exp['order'] = [line_order.index(x) for x in exp['line']]
	exp = exp.sort_values('order').drop('order', axis=1)
	exp['edge_direction'] = [direction.get(w, 'T') for w in exp['stops']]	
	zipkey = zip(exp.stops, exp.line)
	keyed = [(i[0],i[1],j) for i,j in zipkey]
	edge_dict = dict({k: v for k,v in zip(keyed, exp.time)})
	return node_weight_dict, edge_dict

In [282]:
am_nodes, am_edges = graphify(stoptime_morning)
pm_nodes, pm_edges = graphify(stoptime_evening)

In [283]:
def get_nans(nodes: dict):
	nanlist = []
	for k,v in nodes.items():
		for k2,v2 in v.items():
			if np.isnan(v2):
				nanlist.append([k,k2])

	return nanlist

In [284]:
for k1,k2 in get_nans(pm_nodes):
	try:
		del pm_nodes[k1][k2]
	except KeyError:
		continue

In [285]:
for k1,k2 in get_nans(am_nodes):
	try:
		del am_nodes[k1][k2]
	except KeyError:
		continue

In [286]:
ndfam, ndfpm = pd.DataFrame.from_dict(am_nodes).T,pd.DataFrame.from_dict(pm_nodes).T

In [287]:
ndfpm

,1,2,3,5,4,6,6X,7,7X,GS,...,N,Q,M,FS,J,Z,R,H,L,W
101,268.157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,251.843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,251.536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,251.536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,251.536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,428.15,NaN,NaN,NaN
R45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,428.15,NaN,NaN,NaN
S01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,600.0,NaN,NaN,NaN,NaN,NaN,NaN
S03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,600.0,NaN,NaN,NaN,NaN,NaN,NaN
S04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,600.0,NaN,NaN,NaN,NaN,NaN,NaN

In [288]:
ndnp = np.nanmean(np.stack([ndfam.to_numpy(), ndfpm.to_numpy()]),axis=0)
ndfr = pd.DataFrame(ndnp, index = pd.DataFrame.from_dict(am_nodes).T.index.values, columns=ndfam.columns)

In [289]:
ndfr

,1,2,3,5,4,6X,6,7,7X,GS,...,N,Q,M,FS,J,Z,R,H,L,W
101,334.9365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,295.8560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,295.7025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,295.7025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,295.7025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
R44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,435.666,NaN,NaN,NaN
R45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,434.984,NaN,NaN,NaN
S01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,601.3235,NaN,NaN,NaN,NaN,NaN,NaN
S03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,601.3235,NaN,NaN,NaN,NaN,NaN,NaN
S04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,601.3235,NaN,NaN,NaN,NaN,NaN,NaN

In [290]:
nodedict = ndfr.to_dict('index')
for k1,k2 in get_nans(nodedict):
	try:
		del nodedict[k1][k2]
	except KeyError:
		continue

In [291]:
edfpm = pd.DataFrame.from_dict(pm_edges, 'index', columns=['time']).reset_index(names='edge')
edfam = pd.DataFrame.from_dict(am_edges, 'index', columns=['time']).reset_index(names='edge')
edf = pd.concat([edfam, edfpm])
edf['line'] = edf.edge.map(lambda w: w[2])
edf['parent_edge'] = edf.edge.map(lambda w: w[:2])

In [292]:
edf = edf.sort_values('edge').groupby('edge').agg({'parent_edge':'first', 'line':'first','time':'mean'})

In [293]:
expdf = edf.reset_index()
expdf = expdf[expdf.line != 'Transfer']
expdf['stop1'] = expdf.edge.map(lambda w: (w[0],w[2]))
expdf['stop2'] = expdf.edge.map(lambda w: (w[1],w[2]))
edge_key = expdf.copy()[['stop1','stop2','time']]

In [294]:
edge_transfer =  edf.reset_index()
edge_transfer = edge_transfer[edge_transfer.line == 'Transfer']
edge_transfer['stop1'] = edge_transfer.edge.map(lambda w: w[0])
edge_transfer['stop2'] = edge_transfer.edge.map(lambda w: w[1])
edge_transfer.drop(['edge','parent_edge','line'],axis=1,inplace=True)
edge_transfer

      time stop1 stop2
10   180.0   112   A09
30   180.0   125   A24
35   180.0   127   725
36   180.0   127   902
37   300.0   127   A27
..     ...   ...   ...
793  180.0   L03   R20
805  180.0   L17   M08
841  180.0   M20   Q01
842  300.0   M20   R23
867  180.0   Q01   R23

[76 rows x 3 columns]

In [295]:
nodedict

{'101': {'1': 334.9365},
 '103': {'1': 295.856},
 '104': {'1': 295.7025},
 '106': {'1': 295.7025},
 '107': {'1': 295.7025},
 '108': {'1': 295.7025},
 '109': {'1': 295.7025},
 '110': {'1': 295.7025},
 '111': {'1': 295.7025},
 '112': {'1': 295.7025},
 '113': {'1': 295.9805},
 '114': {'1': 295.9805},
 '115': {'1': 268.9465},
 '116': {'1': 268.5895},
 '117': {'1': 269.1965},
 '118': {'1': 269.1965},
 '119': {'1': 268.8395},
 '120': {'1': 268.8395, '2': 403.82349999999997, '3': 452.91650000000004},
 '121': {'1': 268.48199999999997},
 '122': {'1': 268.993},
 '123': {'1': 268.48199999999997, '2': 404.3595, '3': 453.3855},
 '124': {'1': 268.6355},
 '125': {'1': 268.6355},
 '126': {'1': 268.6355},
 '127': {'1': 269.0385, '2': 405.142, '3': 454.01},
 '128': {'1': 269.0385, '2': 405.142, '3': 454.01},
 '129': {'1': 268.9315},
 '130': {'1': 268.9315},
 '131': {'1': 268.9315},
 '132': {'1': 268.9315, '2': 404.3085, '3': 453.385},
 '133': {'1': 268.9315},
 '134': {'1': 268.9315},
 '135': {'1': 269.0385},
 '136': {'1': 269.0385},
 '137': {'1': 268.2175, '2': 404.8445, '3': 453.85400000000004},
 '138': {'1': 268.9675},
 '139': {'1': 268.9675},
 '142': {'1': 269.2175},
 '201': {'2': 419.773},
 '204': {'2': 401.5245, '5': 610.1295},
 '205': {'2': 402.1015, '5': 610.1295},
 '206': {'2': 402.1015, '5': 610.1295},
 '207': {'2': 401.5245, '5': 610.1295},
 '208': {'2': 401.813, '5': 612.2725},
 '209': {'2': 401.5245, '5': 610.1295},
 '210': {'2': 401.5245, '5': 610.1295},
 '211': {'2': 401.5245, '5': 612.2725},
 '212': {'2': 401.236, '5': 612.2725},
 '213': {'2': 401.236, '5': 374.543},
 '214': {'2': 402.019, '5': 439.3345},
 '215': {'2': 402.555, '5': 439.3345},
 '216': {'2': 403.0905, '5': 439.3345},
 '217': {'2': 403.626, '5': 439.3345},
 '218': {'2': 403.04949999999997, '5': 437.43499999999995},
 '219': {'2': 403.04949999999997, '5': 437.43499999999995},
 '220': {'2': 403.874, '5': 437.43499999999995},
 '221': {'2': 404.121, '5': 383.787},
 '222': {'2': 403.8325, '5': 382.8375},
 '224': {'2': 403.288, '3': 452.3265},
 '225': {'2': 403.288, '3': 452.795},
 '226': {'2': 403.288, '3': 452.795},
 '227': {'2': 403.288, '3': 452.795},
 '228': {'2': 405.133, '3': 454.132},
 '229': {'2': 404.8445, '3': 453.85400000000004},
 '230': {'2': 405.133, '3': 454.132},
 '231': {'2': 404.29949999999997, '3': 453.507},
 '232': {'2': 403.4665, '3': 452.882},
 '233': {'2': 403.4665, '3': 452.882},
 '234': {'2': 403.4665, '3': 452.882, '5': 390.6735, '4': 324.9905},
 '235': {'2': 403.4665, '3': 452.882, '5': 390.6735, '4': 324.9905},
 '236': {'2': 404.002, '3': 453.351},
 '237': {'2': 404.002, '3': 453.351},
 '238': {'2': 402.633, '3': 452.882},
 '239': {'2': 403.1685, '3': 450.851, '5': 386.4205, '4': 323.8},
 '241': {'2': 453.0325, '5': 478.38649999999996},
 '242': {'2': 453.0325, '5': 478.38649999999996},
 '243': {'2': 452.095, '5': 477.962},
 '244': {'2': 443.74649999999997, '5': 477.212},
 '245': {'2': 442.20799999999997, '5': 479.225},
 '246': {'2': 441.851, '5': 478.899},
 '247': {'2': 441.851, '5': 478.899},
 '248': {'2': 1800.0, '3': 451.163},
 '249': {'2': 1792.5, '3': 450.538},
 '250': {'2': 1803.75, '3': 450.382, '5': 1204.286, '4': 323.0615},
 '251': {'2': 1777.5, '3': 452.53499999999997, '4': 810.0},
 '252': {'2': 1788.75, '3': 453.004, '4': 810.0},
 '253': {'2': 1777.5, '3': 453.004, '4': 810.0},
 '254': {'2': 1788.75, '3': 453.47249999999997, '4': 810.0},
 '255': {'2': 1792.5, '3': 453.75, '4': 810.0},
 '256': {'2': 1792.5, '3': 453.2815, '4': 810.0},
 '257': {'2': 1792.5, '3': 453.75, '4': 810.0},
 '301': {'3': 494.476},
 '302': {'3': 453.9235},
 '401': {'4': 361.0485},
 '402': {'4': 361.0485},
 '405': {'4': 323.19100000000003},
 '406': {'4': 320.025},
 '407': {'4': 320.025},
 '408': {'4': 320.025},
 '409': {'4': 301.77250000000004},
 '410': {'4': 320.3665},
 '411': {'4': 320.2395},
 '412': {'4': 320.53700000000003},
 '413': {'4': 302.5085},
 '414': {'4': 303.05150000000003},
 '415': {'4': 303.265},
 '416': {'5': 383.0435, '4': 415.53999999999996},
 '418': {'5': 384.663, '4': 306.59749999999997},
 '419': {'5': 383.714, '4': 306.0},
 '420': {'5': 383.714, '4': 306.0},
 '423': {'5': 391.3555, '4': 325.40700000000004},
 '501': {'5': 536.1285},
 '502': {'5': 536.1285},
 '503': {'5': 536.1285},
 '504': {'5': 535.788},
 '505': {'5': 536.1285},
 '601': {'6X': 493.421, '6': 436.0},
 '602': {'6X': 493.179, '6': 436.0},
 '603': {'6X': 493.179, '6': 436.0},
 '604': {'6X': 494.389, '6': 436.0},
 '606': {'6X': 494.389, '6': 436.0},
 '607': {'6X': 494.389, '6': 436.0},
 '608': {'6X': 347.5125, '6': 383.6},
 '609': {'6X': 338.183, '6': 367.2},
 '610': {'6X': 338.183, '6': 367.2},
 '611': {'6X': 338.183, '6': 367.2},
 '612': {'6X': 338.183, '6': 367.2},
 '613': {'6X': 347.245, '6': 383.1},
 '614': {'6X': 337.648, '6': 367.2},
 '615': {'6X': 337.648, '6': 367.2},
 '616': {'6X': 337.648, '6': 367.2},
 '617': {'6X': 337.112, '6': 367.2},
 '618': {'6X': 337.112, '6': 367.2},
 '619': {'6X': 347.7665, '6': 370.192},
 '621': {'5': 382.1135, '4': 304.0315, '6X': 347.637, '6': 370.661},
 '622': {'6X': 348.6945, '6': 370.661},
 '623': {'6X': 348.42650000000003, '6': 370.661},
 '624': {'6X': 348.6945, '6': 370.661},
 '625': {'6X': 349.48400000000004, '6': 371.1295},
 '626': {'5': 382.26750000000004,
  '4': 304.3835,
  '6X': 349.48400000000004,
  '6': 371.1295},
 '627': {'6X': 350.144, '6': 371.33050000000003},
 '628': {'6X': 350.2735, '6': 371.33050000000003},
 '629': {'5': 383.4515,
  '4': 305.74699999999996,
  '6X': 350.144,
  '6': 371.33050000000003},
 '630': {'6X': 350.9335, '6': 371.799},
 '631': {'5': 383.9735, '4': 306.4285, '6X': 350.9335, '6': 370.4595},
 '632': {'6X': 350.9335, '6': 370.4595},
 '633': {'6X': 351.85249999999996, '6': 370.9285},
 '634': {'6X': 350.9335, '6': 370.661},
 '635': {'5': 384.696,
  '4': 306.71500000000003,
  '6X': 351.85249999999996,
  '6': 370.9285},
 '636': {'6X': 351.85249999999996, '6': 370.9285},
 '637': {'6X': 350.9335, '6': 370.9285},
 '638': {'6X': 351.85249999999996, '6': 371.1295},
 '639': {'6X': 351.85249999999996, '6': 371.1295},
 '640': {'5': 384.663, '4': 306.59749999999997, '6X': 354.221, '6': 371.1295},
 '701': {'7': 343.971, '7X': 312.48},
 '702': {'7': 260.80600000000004, '7X': 312.48},
 '705': {'7': 232.4795},
 '706': {'7': 232.4795},
 '707': {'7': 232.4795, '7X': 312.997},
 '708': {'7': 232.578},
 '709': {'7': 232.578},
 '710': {'7': 232.578, '7X': 344.615},
 '711': {'7': 243.9615, '7X': 345.385},
 '712': {'7': 232.7705, '7X': 313.8995},
 '713': {'7': 243.9615, '7X': 345.385},
 '714': {'7': 232.7705, '7X': 313.8995},
 '715': {'7': 232.7705, '7X': 313.8995},
 '716': {'7': 232.677, '7X': 313.8995},
 '718': {'7': 232.677, '7X': 313.8995},
 '719': {'7': 232.677, '7X': 313.8995},
 '720': {'7': 232.677, '7X': 313.8995},
 '721': {'7': 232.552, '7X': 313.8995},
 '723': {'7': 233.03449999999998, '7X': 314.801},
 '724': {'7': 232.90949999999998, '7X': 314.801},
 '725': {'7': 232.90949999999998, '7X': 314.801},
 '726': {'7': 233.091, '7X': 315.3185},
 '901': {'GS': 224.888},
 '902': {'GS': 224.888},
 'A02': {'A': 401.332},
 'A03': {'A': 369.9285},
 'A05': {'A': 369.534},
 'A06': {'A': 369.534},
 'A07': {'A': 369.764},
 'A09': {'A': 355.78, 'C': 576.903},
 'A10': {'C': 576.903},
 'A11': {'C': 576.903},
 'A12': {'A': 355.10450000000003, 'C': 576.903},
 'A14': {'A': 1215.0, 'C': 576.153, 'B': 512.3935},
 'A15': {'A': 354.902, 'C': 576.5095, 'B': 512.751, 'D': 453.0045},
 'A16': {'C': 576.5095, 'B': 512.751},
 'A17': {'C': 576.5095, 'B': 512.751},
 'A18': {'C': 577.2595, 'B': 513.5844999999999},
 'A19': {'C': 576.5095, 'B': 512.751},
 'A20': {'C': 577.2595, 'B': 513.5844999999999},
 'A21': {'C': 577.2595, 'B': 513.5844999999999},
 'A22': {'C': 577.2595, 'B': 513.5844999999999},
 'A24': {'A': 355.527, 'C': 577.2595, 'B': 515.7275, 'D': 453.83799999999997},
 'A25': {'C': 577.617, 'E': 283.8125},
 'A27': {'A': 353.277, 'C': 578.742, 'E': 283.9855},
 'A28': {'A': 353.527, 'C': 578.742, 'E': 283.822},
 'A30': {'C': 578.7919999999999, 'E': 283.772},
 'A31': {'A': 354.152, 'C': 578.7919999999999, 'E': 283.772},
 'A32': {'A': 353.777, 'C': 578.4675, 'E': 283.29650000000004},
 'A33': {'C': 578.4675, 'E': 283.29650000000004},
 'A34': {'A': 353.777, 'C': 578.4675, 'E': 283.96299999999997},
 'A36': {'A': 353.777, 'C': 578.4675},
 'A38': {'A': 353.777, 'C': 578.4675},
 'A40': {'A': 353.477, 'C': 577.4110000000001},
 'A41': {'A': 353.477, 'C': 577.4110000000001, 'FX': 1605.0, 'F': 295.2075},
 'A42': {'A': 353.102, 'C': 576.7294999999999, 'G': 468.4505},
 'A43': {'C': 576.7294999999999},
 'A44': {'C': 576.7975},
 'A45': {'C': 576.7294999999999},
 'A46': {'A': 352.149, 'C': 576.7975},
 'A47': {'C': 576.7975},
 'A48': {'A': 351.774, 'C': 576.7975},
 'A49': {'C': 576.7975},
 'A50': {'C': 576.7975},
 'A51': {'A': 352.8855, 'C': 576.7975},
 'A52': {'C': 575.3655},
 'A53': {'C': 575.3655},
 'A54': {'C': 575.3655},
 'A55': {'A': 335.68, 'C': 574.6835},
 'A57': {'A': 338.022},
 'A59': {'A': 338.022},
 'A60': {'A': 337.81399999999996},
 'A61': {'A': 337.81399999999996},
 'A63': {'A': 743.2370000000001},
 'A64': {'A': 742.9014999999999},
 'A65': {'A': 742.9014999999999},
 'B04': {'FX': 1590.0, 'F': 297.25},
 'B06': {'FX': 1590.0, 'F': 296.7665},
 'B08': {'FX': 1590.0, 'F': 296.7665, 'N': 2645.0, 'Q': 428.973},
 'B10': {'FX': 1590.0, 'F': 296.7665},
 'B12': {'D': 453.685},
 'B13': {'D': 454.0105},
 'B14': {'D': 454.0105},
 'B15': {'D': 454.0105},
 'B16': {'D': 454.0105},
 'B17': {'D': 455.315},
 'B18': {'D': 454.63300000000004},
 'B19': {'D': 454.63300000000004},
 'B20': {'D': 455.315},
 'B21': {'D': 454.63300000000004},
 'B22': {'D': 455.63300000000004},
 'B23': {'D': 520.016},
 'D01': {'D': 455.4175},
 'D03': {'B': 534.053, 'D': 458.63149999999996},
 'D04': {'B': 514.6475, 'D': 458.63149999999996},
 'D05': {'B': 515.481, 'D': 458.63149999999996},
 'D06': {'B': 534.8865000000001, 'D': 409.135},
 'D07': {'B': 518.6949999999999, 'D': 456.846},
 'D08': {'B': 518.6949999999999, 'D': 404.135},
 'D09': {'B': 517.2845, 'D': 402.7715},
 'D10': {'B': 516.451, 'D': 404.135},
 'D11': {'B': 515.874, 'D': 402.7715},
 'D12': {'B': 515.3385, 'D': 404.0215},
 'D13': {'B': 511.7415, 'D': 453.6645},
 'D14': {'B': 515.7584999999999, 'D': 453.83799999999997, 'E': 283.8125},
 'D15': {'B': 515.432,
  'D': 453.83799999999997,
  'FX': 1590.0,
  'F': 297.1415,
  'M': 482.006},
 'D16': {'B': 515.432,
  'D': 453.83799999999997,
  'FX': 1590.0,
  'F': 297.1415,
  'M': 482.006},
 'D17': {'B': 515.432,
  'D': 453.83799999999997,
  'FX': 1590.0,
  'F': 297.1415,
  'M': 482.006},
 'D18': {'FX': 1590.0, 'F': 297.1415, 'M': 482.006},
 'D19': {'FX': 1590.0, 'F': 297.1415, 'M': 482.006},
 'D20': {'B': 514.1825,
  'D': 453.4805,
  'FX': 1590.0,
  'F': 296.606,
  'M': 481.381},
 'D21': {'B': 514.1825,
  'D': 453.4805,
  'FX': 1590.0,
  'F': 296.606,
  'M': 481.381},
 'D22': {'B': 513.6775, 'D': 452.83000000000004},
 'D24': {'B': 509.57050000000004, 'Q': 427.5},
 'D25': {'B': 509.2135, 'Q': 427.23199999999997},
 'D26': {'B': 509.2135, 'Q': 427.23199999999997, 'FS': 601.3235},
 'D27': {'Q': 427.23199999999997},
 'D28': {'B': 509.2135, 'Q': 427.23199999999997},
 'D29': {'Q': 427.23199999999997},
 'D30': {'Q': 427.23199999999997},
 'D31': {'B': 508.6775, 'Q': 427.23199999999997},
 'D32': {'Q': 427.031},
 'D33': {'Q': 427.23199999999997},
 'D34': {'Q': 427.031},
 'D35': {'B': 509.5705, 'Q': 428.10249999999996},
 'D37': {'Q': 427.634},
 'D38': {'Q': 427.634},
 'D39': {'B': 509.5705, 'Q': 427.634},
 'D40': {'B': 509.2445, 'Q': 427.16549999999995},
 'D41': {'Q': 427.433},
 'D42': {'FX': 1605.0, 'F': 552.753, 'Q': 426.96450000000004},
 'D43': {'D': 522.3485000000001,
  'FX': 1605.0,
  'F': 552.753,
  'N': 532.1395,
  'Q': 426.96450000000004},
 'E01': {'E': 283.96299999999997},
 'F01': {'E': 1121.25, 'FX': 1530.0, 'F': 297.875},
 'F02': {'FX': 1530.0, 'F': 297.45849999999996},
 'F03': {'E': 1128.75, 'FX': 1530.0, 'F': 297.04200000000003},
 'F04': {'FX': 1530.0, 'F': 297.04200000000003},
 'F05': {'E': 351.923, 'FX': 1530.0, 'F': 297.04200000000003},
 'F06': {'E': 283.24649999999997, 'FX': 1530.0, 'F': 297.04200000000003},
 'F07': {'E': 351.923, 'FX': 1530.0, 'F': 297.04200000000003},
 'F09': {'E': 284.8035, 'M': 481.4355},
 'F11': {'E': 284.8035, 'M': 481.4355},
 'F12': {'E': 284.8035, 'M': 482.006},
 'F14': {'FX': 1590.0, 'F': 296.606},
 'F15': {'FX': 1590.0, 'F': 296.8145},
 'F16': {'FX': 1590.0, 'F': 296.8145},
 'F18': {'FX': 1590.0, 'F': 296.8145},
 'F20': {'F': 296.441, 'G': 468.1915},
 'F21': {'F': 296.441, 'G': 468.1915},
 'F22': {'F': 296.11400000000003, 'G': 468.1915},
 'F23': {'F': 296.11400000000003, 'G': 468.1915},
 'F24': {'FX': 1605.0, 'F': 296.11400000000003, 'G': 468.1915},
 'F25': {'F': 296.356, 'G': 468.4505},
 'F26': {'F': 296.356, 'G': 468.4505},
 'F27': {'FX': 1605.0, 'F': 296.356, 'G': 468.4505},
 'F29': {'FX': 1605.0, 'F': 313.1275},
 'F30': {'FX': 1605.0, 'F': 313.1275},
 'F31': {'FX': 1605.0, 'F': 314.978},
 'F32': {'FX': 1605.0, 'F': 314.978},
 'F33': {'FX': 1605.0, 'F': 314.978},
 'F34': {'FX': 1605.0, 'F': 314.978},
 'F35': {'FX': 1605.0, 'F': 314.978},
 'F36': {'FX': 1605.0, 'F': 484.3075},
 'F38': {'FX': 1605.0, 'F': 484.724},
 'F39': {'FX': 1605.0, 'F': 552.753},
 'G05': {'E': 302.9645, 'J': 502.188, 'Z': 606.0},
 'G06': {'E': 304.375, 'J': 502.188, 'Z': 606.0},
 'G07': {'E': 304.375},
 'G08': {'E': 284.01,
  'FX': 1530.0,
  'F': 297.04200000000003,
  'M': 479.682,
  'R': 431.59799999999996},
 'G09': {'M': 479.682, 'R': 431.59799999999996},
 'G10': {'M': 479.682, 'R': 431.59799999999996},
 'G11': {'M': 479.682, 'R': 431.59799999999996},
 'G12': {'M': 480.259, 'R': 432.22299999999996},
 'G13': {'M': 480.259, 'R': 432.22299999999996},
 'G14': {'E': 284.1225,
  'FX': 1530.0,
  'F': 297.25,
  'M': 480.259,
  'R': 432.22299999999996},
 'G15': {'M': 480.259, 'R': 432.22299999999996},
 'G16': {'M': 480.259, 'R': 432.22299999999996},
 'G18': {'M': 480.259, 'R': 432.22299999999996},
 'G19': {'M': 480.836, 'R': 432.84799999999996},
 'G20': {'M': 480.836, 'R': 432.84799999999996},
 'G21': {'E': 284.545, 'M': 480.836, 'R': 431.484},
 'G22': {'G': 468.283},
 'G24': {'G': 468.283},
 'G26': {'G': 467.608},
 'G28': {'G': 467.608},
 'G29': {'G': 467.608},
 'G30': {'G': 467.608},
 'G31': {'G': 467.1915},
 'G32': {'G': 467.608},
 'G33': {'G': 467.1915},
 'G34': {'G': 467.1915},
 'G35': {'G': 467.1915},
 'G36': {'G': 467.1915},
 'H01': {'A': 604.432},
 'H02': {'A': 588.729},
 'H03': {'A': 588.729},
 'H04': {'A': 590.6605, 'H': 960.441},
 'H06': {'A': 679.1075000000001},
 'H07': {'A': 680.3575000000001},
 'H08': {'A': 683.0355},
 'H09': {'A': 681.25},
 'H10': {'A': 684.1075000000001},
 'H11': {'A': 683.0355},
 'H12': {'A': 1197.5, 'H': 960.441},
 'H13': {'A': 1192.5, 'H': 961.434},
 'H14': {'A': 1197.5, 'H': 960.4965},
 'H15': {'A': 1196.25, 'H': 961.434},
 'J12': {'J': 671.027, 'Z': 606.0},
 'J13': {'J': 502.188},
 'J14': {'J': 671.027, 'Z': 606.0},
 'J15': {'J': 502.188, 'Z': 606.0},
 'J16': {'J': 502.188},
 'J17': {'J': 671.027, 'Z': 606.0},
 'J19': {'J': 501.65250000000003},
 'J20': {'J': 501.65250000000003, 'Z': 606.0},
 'J21': {'J': 671.027, 'Z': 606.0},
 'J22': {'J': 501.65250000000003},
 'J23': {'J': 669.956, 'Z': 606.0},
 'J24': {'J': 501.65250000000003, 'Z': 606.0},
 'J27': {'J': 484.4925, 'Z': 606.0},
 'J28': {'J': 671.384, 'Z': 606.0},
 'J29': {'J': 503.08},
 'J30': {'J': 671.384, 'Z': 606.0},
 'J31': {'J': 503.08},
 'L01': {'L': 236.824},
 'L02': {'L': 236.824},
 'L03': {'L': 236.695},
 'L05': {'L': 236.5655},
 'L06': {'L': 236.5655},
 'L08': {'L': 236.5655},
 'L10': {'L': 236.5655},
 'L11': {'L': 236.5655},
 'L12': {'L': 236.5655},
 'L13': {'L': 236.5655},
 'L14': {'L': 236.378},
 'L15': {'L': 236.378},
 'L16': {'L': 236.378},
 'L17': {'L': 236.378},
 'L19': {'L': 258.577},
 'L20': {'L': 258.3565},
 'L21': {'L': 258.3565},
 'L22': {'L': 257.91499999999996},
 'L24': {'L': 258.94},
 'L25': {'L': 258.94},
 'L26': {'L': 258.59000000000003},
 'L27': {'L': 258.59000000000003},
 'L28': {'L': 258.59000000000003},
 'L29': {'L': 290.8755},
 'M01': {'M': 479.45},
 'M04': {'M': 479.45},
 'M05': {'M': 479.776},
 'M06': {'M': 479.776},
 'M08': {'M': 479.776},
 'M09': {'M': 479.776},
 'M10': {'M': 479.776},
 'M11': {'M': 479.776, 'J': 502.2315, 'Z': 612.0},
 'M12': {'M': 481.325, 'J': 477.0535},
 'M13': {'M': 481.325, 'J': 477.0535},
 'M14': {'M': 481.325, 'J': 477.0535},
 'M16': {'M': 481.325, 'J': 502.2315, 'Z': 612.0},
 'M18': {'M': 480.702, 'J': 502.2315, 'Z': 612.0},
 'M19': {'J': 501.76300000000003, 'Z': 612.0},
 'M20': {'J': 501.76300000000003, 'Z': 618.0},
 'M21': {'J': 501.76300000000003, 'Z': 618.0},
 'M22': {'J': 501.4955, 'Z': 618.0},
 'M23': {'J': 501.3395, 'Z': 618.0},
 'N02': {'N': 476.2925},
 'N03': {'N': 476.619},
 'N04': {'N': 476.119},
 'N05': {'N': 476.119},
 'N06': {'N': 476.4445},
 'N07': {'N': 476.4445},
 'N08': {'N': 476.4445},
 'N09': {'N': 476.4445},
 'N10': {'N': 476.4445},
 'Q01': {'N': 482.897, 'Q': 430.64750000000004},
 'Q03': {'N': 2645.0, 'Q': 428.973},
 'Q04': {'N': 2642.5, 'Q': 428.4375},
 'Q05': {'N': 2642.5, 'Q': 428.16999999999996},
 'R01': {'N': 509.6755, 'W': 528.7825},
 'R03': {'N': 510.168, 'W': 529.0185},
 'R04': {'N': 510.509, 'W': 529.0185},
 'R05': {'N': 511.001, 'W': 529.254},
 'R06': {'N': 510.509, 'W': 529.0185},
 'R08': {'N': 511.001, 'W': 529.254},
 'R09': {'N': 512.4114999999999, 'W': 530.581},
 'R11': {'N': 509.0565, 'R': 431.484, 'W': 530.581},
 'R13': {'N': 509.0565, 'R': 431.484, 'W': 530.581},
 'R14': {'N': 478.4045, 'Q': 428.973, 'R': 421.825, 'W': 530.581},
 'R15': {'N': 509.66949999999997, 'R': 422.125, 'W': 531.158},
 'R16': {'N': 480.5635, 'Q': 430.58000000000004, 'R': 422.125, 'W': 531.158},
 'R17': {'N': 483.897, 'Q': 431.116, 'R': 421.5, 'W': 531.158},
 'R18': {'R': 421.5, 'W': 531.158},
 'R19': {'R': 421.5, 'W': 531.158},
 'R20': {'N': 483.397, 'Q': 431.116, 'R': 421.8, 'W': 531.735},
 'R21': {'R': 421.175, 'W': 530.985},
 'R22': {'R': 421.8, 'W': 531.735},
 'R23': {'R': 423.05, 'W': 530.985},
 'R24': {'R': 420.55, 'W': 530.985},
 'R25': {'R': 420.55, 'W': 530.985},
 'R26': {'R': 419.925, 'W': 530.985},
 'R27': {'R': 418.725, 'W': 530.985},
 'R28': {'R': 420.6},
 'R29': {'R': 420.6},
 'R30': {'B': 509.8965, 'Q': 427.76800000000003, 'R': 420.6},
 'R31': {'D': 455.9145, 'N': 480.227, 'R': 422.475},
 'R32': {'R': 422.475},
 'R33': {'R': 422.475},
 'R34': {'R': 422.475},
 'R35': {'R': 422.475},
 'R36': {'D': 455.2325, 'N': 478.27099999999996, 'R': 422.475},
 'R39': {'R': 436.6035},
 'R40': {'R': 436.6035},
 'R41': {'N': 476.2925, 'R': 435.666},
 'R42': {'R': 435.666},
 'R43': {'R': 435.666},
 'R44': {'R': 435.666},
 'R45': {'R': 434.984},
 'S01': {'FS': 601.3235},
 'S03': {'FS': 601.3235},
 'S04': {'FS': 601.3235}}

In [296]:
node_parts = pd.DataFrame.from_dict({k: [list(v.keys())] for k,v in nodedict.items()}, 'index')
node_parts.reset_index(inplace=True)
node_parts.columns = ['stop','lines']
node_parts['same_stop'] = np.arange(len(node_parts))
nodes=node_parts.copy()
node_parts = node_parts.explode('lines')

In [297]:
node_parts['time'] = [nodedict[a][b] for a,b in zip(node_parts.stop, node_parts.lines)]

In [298]:
transfers = pd.concat([edge_transfer['stop1'],edge_transfer['stop2']]).unique()
node_transfer_edges = nodes[[k in transfers for k in nodes['stop']]].reset_index()
line_dict = dict(zip(node_transfer_edges['stop'], node_transfer_edges['lines']))
edge_transfer['key1'] = [line_dict[n] for n in edge_transfer['stop1']]
edge_transfer['key2'] = [line_dict[n] for n in edge_transfer['stop2']]
edge_transfer = edge_transfer[['stop1', 'stop2', 'key1', 'key2','time']]
node_transfer_edges['same_stop'] = np.arange(len(node_transfer_edges))
stop_dict = dict(zip(node_transfer_edges['stop'], node_transfer_edges['same_stop']))
te1 = edge_transfer.copy()
edge_transfer = edge_transfer.explode('key1').explode('key2')

In [299]:
gn = nx.DiGraph(name='dimensional')
gn.add_weighted_edges_from(zip(edge_key['stop1'], edge_key['stop2'], edge_key['time']), weight='travel_time', transfer=0,same_stop=0)
gn.add_weighted_edges_from(zip(edge_key['stop2'], edge_key['stop1'], edge_key['time']), weight='travel_time', transfer=0,same_stop=0)

In [300]:
te1 = te1.explode('key1').explode('key2')

In [301]:
te = zip(zip(te1['stop1'], te1['key1']), zip(te1['stop2'], te1['key2']), te1['time'])
te = pd.DataFrame(te, columns=['stop1','stop2','time'])
te2 = te[['stop2','stop1','time']]
te = pd.concat([te,te2]).reset_index(drop=True)
te['transfer'] = 1
te['in_complex'] = 0
te.rename(columns={'time':'travel_time'}, inplace=True)
te

        stop1     stop2  travel_time  transfer  in_complex
0    (112, 1)  (A09, A)        180.0         1           0
1    (112, 1)  (A09, C)        180.0         1           0
2    (125, 1)  (A24, A)        180.0         1           0
3    (125, 1)  (A24, C)        180.0         1           0
4    (125, 1)  (A24, B)        180.0         1           0
..        ...       ...          ...       ...         ...
789  (M20, Z)  (R23, W)        300.0         1           0
790  (Q01, N)  (R23, R)        180.0         1           0
791  (Q01, N)  (R23, W)        180.0         1           0
792  (Q01, Q)  (R23, R)        180.0         1           0
793  (Q01, Q)  (R23, W)        180.0         1           0

[794 rows x 5 columns]

In [302]:
gn.add_weighted_edges_from(zip(te['stop1'], te['stop2'], te['travel_time']), weight='travel_time', transfer=1,same_stop=0)
gn.add_weighted_edges_from(zip(te['stop2'], te['stop1'], te['travel_time']), weight='travel_time', transfer=1,same_stop=0)

In [303]:
node_parts['node'] = list(zip(node_parts.stop, node_parts.lines))
node_parts.set_index('node',inplace=True)

In [304]:
for name, group in node_parts.groupby('same_stop'):
	if len(group) == 1: continue
	else:
		for u,v in list(itertools.permutations(group.index.to_list(),2)):
			gn.add_weighted_edges_from([(u,v,group['time'][v])], weight='travel_time', transfer=1, same_stop=1)
			gn.add_weighted_edges_from([(v,u,group['time'][u])], weight='travel_time', transfer=1, same_stop=1)

In [305]:
edgedict = edf['time'].to_dict()

In [306]:
f = open("subwaygraph_midday_dir.json",'r')
gd = nx.node_link_graph(json.load(f), directed=False, multigraph=True, edges='edges')

In [307]:
gn.edges.data()

OutEdgeDataView([(('101', '1'), ('103', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 119.0}), (('103', '1'), ('104', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 94.0}), (('103', '1'), ('101', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 119.0}), (('104', '1'), ('106', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('104', '1'), ('103', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 94.0}), (('106', '1'), ('107', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('106', '1'), ('104', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('107', '1'), ('108', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 73.5}), (('107', '1'), ('106', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('108', '1'), ('109', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('108', '1'), ('107', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 73.5}), (('109', '1'), ('110', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('109', '1'), ('108', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('110', '1'), ('111', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('110', '1'), ('109', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('111', '1'), ('112', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 124.0}), (('111', '1'), ('110', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('112', '1'), ('113', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 107.0}), (('112', '1'), ('111', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 124.0}), (('112', '1'), ('A09', 'A'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('112', '1'), ('A09', 'C'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('113', '1'), ('114', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 120.0}), (('113', '1'), ('112', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 107.0}), (('114', '1'), ('115', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('114', '1'), ('113', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 120.0}), (('115', '1'), ('116', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 110.0}), (('115', '1'), ('114', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('116', '1'), ('117', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 136.5}), (('116', '1'), ('115', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 110.0}), (('117', '1'), ('118', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('117', '1'), ('116', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 136.5}), (('118', '1'), ('119', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 73.0}), (('118', '1'), ('117', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('119', '1'), ('120', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 107.5}), (('119', '1'), ('118', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 73.0}), (('120', '1'), ('121', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 120.0}), (('120', '1'), ('119', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 107.5}), (('120', '1'), ('120', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(403.82349999999997)}), (('120', '1'), ('120', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(452.91650000000004)}), (('121', '1'), ('122', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 62.0}), (('121', '1'), ('120', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 120.0}), (('120', '2'), ('123', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 179.0}), (('120', '2'), ('227', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 288.5}), (('120', '2'), ('120', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(268.8395)}), (('120', '2'), ('120', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(452.91650000000004)}), (('123', '2'), ('127', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 256.5}), (('123', '2'), ('120', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 179.0}), (('123', '2'), ('123', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(268.48199999999997)}), (('123', '2'), ('123', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(453.3855)}), (('120', '3'), ('123', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 177.0}), (('120', '3'), ('227', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 288.0}), (('120', '3'), ('120', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(268.8395)}), (('120', '3'), ('120', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(403.82349999999997)}), (('123', '3'), ('127', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 253.5}), (('123', '3'), ('120', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 177.0}), (('123', '3'), ('123', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(268.48199999999997)}), (('123', '3'), ('123', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(404.3595)}), (('227', '2'), ('120', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 288.5}), (('227', '2'), ('226', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('227', '2'), ('227', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(452.795)}), (('227', '3'), ('120', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 288.0}), (('227', '3'), ('226', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('227', '3'), ('227', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(403.288)}), (('122', '1'), ('123', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 103.0}), (('122', '1'), ('121', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 62.0}), (('123', '1'), ('124', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 77.0}), (('123', '1'), ('122', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 103.0}), (('123', '1'), ('123', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(404.3595)}), (('123', '1'), ('123', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(453.3855)}), (('124', '1'), ('125', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('124', '1'), ('123', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 77.0}), (('127', '2'), ('128', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('127', '2'), ('123', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 256.5}), (('127', '2'), ('725', '7'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '2'), ('725', '7X'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '2'), ('902', 'GS'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '2'), ('A27', 'A'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '2'), ('A27', 'C'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '2'), ('A27', 'E'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '2'), ('R16', 'N'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '2'), ('R16', 'Q'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '2'), ('R16', 'R'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '2'), ('R16', 'W'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '2'), ('127', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(269.0385)}), (('127', '2'), ('127', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(454.01)}), (('127', '3'), ('128', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('127', '3'), ('123', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 253.5}), (('127', '3'), ('725', '7'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '3'), ('725', '7X'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '3'), ('902', 'GS'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '3'), ('A27', 'A'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '3'), ('A27', 'C'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '3'), ('A27', 'E'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '3'), ('R16', 'N'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '3'), ('R16', 'Q'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '3'), ('R16', 'R'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '3'), ('R16', 'W'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '3'), ('127', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(269.0385)}), (('127', '3'), ('127', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(405.142)}), (('125', '1'), ('126', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 120.0}), (('125', '1'), ('124', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('125', '1'), ('A24', 'A'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('125', '1'), ('A24', 'C'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('125', '1'), ('A24', 'B'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('125', '1'), ('A24', 'D'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('126', '1'), ('127', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 97.0}), (('126', '1'), ('125', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 120.0}), (('127', '1'), ('128', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 92.0}), (('127', '1'), ('126', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 97.0}), (('127', '1'), ('725', '7'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '1'), ('725', '7X'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '1'), ('902', 'GS'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '1'), ('A27', 'A'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '1'), ('A27', 'C'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '1'), ('A27', 'E'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('127', '1'), ('R16', 'N'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '1'), ('R16', 'Q'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '1'), ('R16', 'R'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '1'), ('R16', 'W'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('127', '1'), ('127', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(405.142)}), (('127', '1'), ('127', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(454.01)}), (('128', '1'), ('129', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 77.5}), (('128', '1'), ('127', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 92.0}), (('128', '1'), ('128', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(405.142)}), (('128', '1'), ('128', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(454.01)}), (('128', '2'), ('132', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 178.5}), (('128', '2'), ('127', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('128', '2'), ('128', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(269.0385)}), (('128', '2'), ('128', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(454.01)}), (('128', '3'), ('132', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 179.0}), (('128', '3'), ('127', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('128', '3'), ('128', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(269.0385)}), (('128', '3'), ('128', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(405.142)}), (('129', '1'), ('130', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('129', '1'), ('128', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 77.5}), (('132', '2'), ('137', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 282.5}), (('132', '2'), ('128', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 178.5}), (('132', '2'), ('D19', 'FX'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '2'), ('D19', 'F'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '2'), ('D19', 'M'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '2'), ('L02', 'L'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('132', '2'), ('132', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(268.9315)}), (('132', '2'), ('132', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(453.385)}), (('132', '3'), ('137', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 281.0}), (('132', '3'), ('128', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 179.0}), (('132', '3'), ('D19', 'FX'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '3'), ('D19', 'F'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '3'), ('D19', 'M'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '3'), ('L02', 'L'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('132', '3'), ('132', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(268.9315)}), (('132', '3'), ('132', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(404.3085)}), (('130', '1'), ('131', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('130', '1'), ('129', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('131', '1'), ('132', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 62.0}), (('131', '1'), ('130', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('132', '1'), ('133', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('132', '1'), ('131', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 62.0}), (('132', '1'), ('D19', 'FX'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '1'), ('D19', 'F'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '1'), ('D19', 'M'), {'transfer': 1, 'same_stop': 0, 'travel_time': 300.0}), (('132', '1'), ('L02', 'L'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('132', '1'), ('132', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(404.3085)}), (('132', '1'), ('132', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(453.385)}), (('133', '1'), ('134', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 94.5}), (('133', '1'), ('132', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('137', '2'), ('228', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 83.5}), (('137', '2'), ('132', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 282.5}), (('137', '2'), ('137', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(268.2175)}), (('137', '2'), ('137', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(453.85400000000004)}), (('137', '3'), ('228', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 82.0}), (('137', '3'), ('132', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 281.0}), (('137', '3'), ('137', '1'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(268.2175)}), (('137', '3'), ('137', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(404.8445)}), (('134', '1'), ('135', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 103.5}), (('134', '1'), ('133', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 94.5}), (('135', '1'), ('136', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('135', '1'), ('134', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 103.5}), (('136', '1'), ('137', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 81.0}), (('136', '1'), ('135', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 60.0}), (('137', '1'), ('138', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 124.0}), (('137', '1'), ('136', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 81.0}), (('137', '1'), ('137', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(404.8445)}), (('137', '1'), ('137', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(453.85400000000004)}), (('138', '1'), ('139', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 92.0}), (('138', '1'), ('137', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 124.0}), (('228', '2'), ('229', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 130.0}), (('228', '2'), ('137', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 83.5}), (('228', '2'), ('A36', 'A'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('228', '2'), ('A36', 'C'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('228', '2'), ('E01', 'E'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('228', '2'), ('R25', 'R'), {'transfer': 1, 'same_stop': 0, 'travel_time': 420.0}), (('228', '2'), ('R25', 'W'), {'transfer': 1, 'same_stop': 0, 'travel_time': 420.0}), (('228', '2'), ('228', '3'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(454.132)}), (('228', '3'), ('229', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 131.0}), (('228', '3'), ('137', '3'), {'transfer': 0, 'same_stop': 0, 'travel_time': 82.0}), (('228', '3'), ('A36', 'A'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('228', '3'), ('A36', 'C'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('228', '3'), ('E01', 'E'), {'transfer': 1, 'same_stop': 0, 'travel_time': 180.0}), (('228', '3'), ('R25', 'R'), {'transfer': 1, 'same_stop': 0, 'travel_time': 420.0}), (('228', '3'), ('R25', 'W'), {'transfer': 1, 'same_stop': 0, 'travel_time': 420.0}), (('228', '3'), ('228', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(405.133)}), (('139', '1'), ('142', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 108.5}), (('139', '1'), ('138', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 92.0}), (('142', '1'), ('139', '1'), {'transfer': 0, 'same_stop': 0, 'travel_time': 108.5}), (('142', '1'), ('R27', 'R'), {'transfer': 1, 'same_stop': 0, 'travel_time': 120.0}), (('142', '1'), ('R27', 'W'), {'transfer': 1, 'same_stop': 0, 'travel_time': 120.0}), (('201', '2'), ('204', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 106.5}), (('204', '2'), ('205', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 93.0}), (('204', '2'), ('201', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 106.5}), (('204', '2'), ('204', '5'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(610.1295)}), (('205', '2'), ('206', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('205', '2'), ('204', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 93.0}), (('205', '2'), ('205', '5'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(610.1295)}), (('204', '5'), ('205', '5'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('204', '5'), ('204', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(401.5245)}), (('205', '5'), ('206', '5'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('205', '5'), ('204', '5'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('205', '5'), ('205', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(402.1015)}), (('206', '2'), ('207', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 72.5}), (('206', '2'), ('205', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('206', '2'), ('206', '5'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(610.1295)}), (('206', '5'), ('207', '5'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('206', '5'), ('205', '5'), {'transfer': 0, 'same_stop': 0, 'travel_time': 90.0}), (('206', '5'), ('206', '2'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.float64(402.1015)}), (('207', '2'), ('208', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 98.5}), (('207', '2'), ('206', '2'), {'transfer': 0, 'same_stop': 0, 'travel_time': 72.5}), (('207', '2'), ('207', '5'), {'transfer': 1, 'same_stop': 1, 'travel_time': np.flo

In [309]:
colors = ['#0062CF','#EB6800','#799534','#8E5C33','#7C858C','#F6BC26','#7C858C','#D82233','#009952','#9A38A1']
lines_color = [n.split(",") for n in ["A,C,E","B,D,F,FX,M","G","J,Z","L","N,Q,R,W","FS,GS,H","1,2,3","4,5,6,6X","7,7X",]]
colorcode = pd.DataFrame([lines_color,colors]).T
colorcode.columns=['line', 'color']
colorcode = colorcode.explode('line').set_index('line')
cold = {k: list(v.values())[0] for k,v in colorcode.to_dict('index').items()}

In [326]:
ndata = pd.DataFrame.from_dict(nodedict.items())
ndata.columns=['stop','wait_time']
ndata['lines'] = ndata.wait_time.map(lambda d: list(d.keys()))
ndata.wait_time = ndata.wait_time.map(lambda d: list(d.values()))
ndata['same_stop'] = np.arange(len(ndata))
ndata = ndata.explode(['lines', 'wait_time'])
ndata.reset_index(drop=True, inplace=True)
ndata.sort_values(['same_stop','lines'], inplace=True)
xy = pd.read_csv('gtfs_subway/stops.txt')
xy = xy[[len(k) == 3 for k in xy['stop_id']]]
xy = xy.rename({'stop_lat': 'y', 'stop_lon':'x'}, axis=1)[['stop_id','x','y']].set_index('stop_id')
xyd = xy.to_dict('index')
ndata['x'] = [xyd[n]['x'] for n in ndata['stop']]
ndata['y'] = [xyd[n]['y'] for n in ndata['stop']]
ndata['color'] = [cold[s] for s in ndata['lines']]

In [331]:
ndata.index = list(zip(ndata.stop,ndata.lines))

In [334]:
nx.set_node_attributes(gn, ndata.to_dict('index'))

In [335]:
gn.nodes.data()

NodeDataView({('101', '1'): {'stop': '101', 'wait_time': 334.9365, 'lines': '1', 'same_stop': 0, 'x': -73.898583, 'y': 40.889248, 'color': '#D82233'}, ('103', '1'): {'stop': '103', 'wait_time': 295.856, 'lines': '1', 'same_stop': 1, 'x': -73.90087, 'y': 40.884667, 'color': '#D82233'}, ('104', '1'): {'stop': '104', 'wait_time': 295.7025, 'lines': '1', 'same_stop': 2, 'x': -73.904834, 'y': 40.878856, 'color': '#D82233'}, ('106', '1'): {'stop': '106', 'wait_time': 295.7025, 'lines': '1', 'same_stop': 3, 'x': -73.909831, 'y': 40.874561, 'color': '#D82233'}, ('107', '1'): {'stop': '107', 'wait_time': 295.7025, 'lines': '1', 'same_stop': 4, 'x': -73.915279, 'y': 40.869444, 'color': '#D82233'}, ('108', '1'): {'stop': '108', 'wait_time': 295.7025, 'lines': '1', 'same_stop': 5, 'x': -73.918822, 'y': 40.864621, 'color': '#D82233'}, ('109', '1'): {'stop': '109', 'wait_time': 295.7025, 'lines': '1', 'same_stop': 6, 'x': -73.925536, 'y': 40.860531, 'color': '#D82233'}, ('110', '1'): {'stop': '110', 'wait_time': 295.7025, 'lines': '1', 'same_stop': 7, 'x': -73.929412, 'y': 40.855225, 'color': '#D82233'}, ('111', '1'): {'stop': '111', 'wait_time': 295.7025, 'lines': '1', 'same_stop': 8, 'x': -73.933596, 'y': 40.849505, 'color': '#D82233'}, ('112', '1'): {'stop': '112', 'wait_time': 295.7025, 'lines': '1', 'same_stop': 9, 'x': -73.940133, 'y': 40.840556, 'color': '#D82233'}, ('113', '1'): {'stop': '113', 'wait_time': 295.9805, 'lines': '1', 'same_stop': 10, 'x': -73.94489, 'y': 40.834041, 'color': '#D82233'}, ('114', '1'): {'stop': '114', 'wait_time': 295.9805, 'lines': '1', 'same_stop': 11, 'x': -73.95036, 'y': 40.826551, 'color': '#D82233'}, ('115', '1'): {'stop': '115', 'wait_time': 268.9465, 'lines': '1', 'same_stop': 12, 'x': -73.953676, 'y': 40.822008, 'color': '#D82233'}, ('116', '1'): {'stop': '116', 'wait_time': 268.5895, 'lines': '1', 'same_stop': 13, 'x': -73.958372, 'y': 40.815581, 'color': '#D82233'}, ('117', '1'): {'stop': '117', 'wait_time': 269.1965, 'lines': '1', 'same_stop': 14, 'x': -73.96411, 'y': 40.807722, 'color': '#D82233'}, ('118', '1'): {'stop': '118', 'wait_time': 269.1965, 'lines': '1', 'same_stop': 15, 'x': -73.966847, 'y': 40.803967, 'color': '#D82233'}, ('119', '1'): {'stop': '119', 'wait_time': 268.8395, 'lines': '1', 'same_stop': 16, 'x': -73.968379, 'y': 40.799446, 'color': '#D82233'}, ('120', '1'): {'stop': '120', 'wait_time': 268.8395, 'lines': '1', 'same_stop': 17, 'x': -73.972323, 'y': 40.793919, 'color': '#D82233'}, ('121', '1'): {'stop': '121', 'wait_time': 268.48199999999997, 'lines': '1', 'same_stop': 18, 'x': -73.976218, 'y': 40.788644, 'color': '#D82233'}, ('120', '2'): {'stop': '120', 'wait_time': 403.82349999999997, 'lines': '2', 'same_stop': 17, 'x': -73.972323, 'y': 40.793919, 'color': '#D82233'}, ('123', '2'): {'stop': '123', 'wait_time': 404.3595, 'lines': '2', 'same_stop': 20, 'x': -73.98197, 'y': 40.778453, 'color': '#D82233'}, ('120', '3'): {'stop': '120', 'wait_time': 452.91650000000004, 'lines': '3', 'same_stop': 17, 'x': -73.972323, 'y': 40.793919, 'color': '#D82233'}, ('123', '3'): {'stop': '123', 'wait_time': 453.3855, 'lines': '3', 'same_stop': 20, 'x': -73.98197, 'y': 40.778453, 'color': '#D82233'}, ('227', '2'): {'stop': '227', 'wait_time': 403.288, 'lines': '2', 'same_stop': 61, 'x': -73.951822, 'y': 40.799075, 'color': '#D82233'}, ('227', '3'): {'stop': '227', 'wait_time': 452.795, 'lines': '3', 'same_stop': 61, 'x': -73.951822, 'y': 40.799075, 'color': '#D82233'}, ('122', '1'): {'stop': '122', 'wait_time': 268.993, 'lines': '1', 'same_stop': 19, 'x': -73.979917, 'y': 40.783934, 'color': '#D82233'}, ('123', '1'): {'stop': '123', 'wait_time': 268.48199999999997, 'lines': '1', 'same_stop': 20, 'x': -73.98197, 'y': 40.778453, 'color': '#D82233'}, ('124', '1'): {'stop': '124', 'wait_time': 268.6355, 'lines': '1', 'same_stop': 21, 'x': -73.982209, 'y': 40.77344, 'color': '#D82233'}, ('127', '2'): {'stop': '127', 'wait_time': 405.142, 'lines': '2', 'same_stop': 24, 'x': -73.987495, 'y': 40.75529, 'color': '#D82233'}, ('127', '3'): {'stop': '127', 'wait_time': 454.01, 'lines': '3', 'same_stop': 24, 'x': -73.987495, 'y': 40.75529, 'color': '#D82233'}, ('125', '1'): {'stop': '125', 'wait_time': 268.6355, 'lines': '1', 'same_stop': 22, 'x': -73.981929, 'y': 40.768247, 'color': '#D82233'}, ('126', '1'): {'stop': '126', 'wait_time': 268.6355, 'lines': '1', 'same_stop': 23, 'x': -73.983849, 'y': 40.761728, 'color': '#D82233'}, ('127', '1'): {'stop': '127', 'wait_time': 269.0385, 'lines': '1', 'same_stop': 24, 'x': -73.987495, 'y': 40.75529, 'color': '#D82233'}, ('128', '1'): {'stop': '128', 'wait_time': 269.0385, 'lines': '1', 'same_stop': 25, 'x': -73.991057, 'y': 40.750373, 'color': '#D82233'}, ('128', '2'): {'stop': '128', 'wait_time': 405.142, 'lines': '2', 'same_stop': 25, 'x': -73.991057, 'y': 40.750373, 'color': '#D82233'}, ('128', '3'): {'stop': '128', 'wait_time': 454.01, 'lines': '3', 'same_stop': 25, 'x': -73.991057, 'y': 40.750373, 'color': '#D82233'}, ('129', '1'): {'stop': '129', 'wait_time': 268.9315, 'lines': '1', 'same_stop': 26, 'x': -73.993365, 'y': 40.747215, 'color': '#D82233'}, ('132', '2'): {'stop': '132', 'wait_time': 404.3085, 'lines': '2', 'same_stop': 29, 'x': -74.000201, 'y': 40.737826, 'color': '#D82233'}, ('132', '3'): {'stop': '132', 'wait_time': 453.385, 'lines': '3', 'same_stop': 29, 'x': -74.000201, 'y': 40.737826, 'color': '#D82233'}, ('130', '1'): {'stop': '130', 'wait_time': 268.9315, 'lines': '1', 'same_stop': 27, 'x': -73.995657, 'y': 40.744081, 'color': '#D82233'}, ('131', '1'): {'stop': '131', 'wait_time': 268.9315, 'lines': '1', 'same_stop': 28, 'x': -73.997871, 'y': 40.74104, 'color': '#D82233'}, ('132', '1'): {'stop': '132', 'wait_time': 268.9315, 'lines': '1', 'same_stop': 29, 'x': -74.000201, 'y': 40.737826, 'color': '#D82233'}, ('133', '1'): {'stop': '133', 'wait_time': 268.9315, 'lines': '1', 'same_stop': 30, 'x': -74.002906, 'y': 40.733422, 'color': '#D82233'}, ('137', '2'): {'stop': '137', 'wait_time': 404.8445, 'lines': '2', 'same_stop': 34, 'x': -74.009266, 'y': 40.715478, 'color': '#D82233'}, ('137', '3'): {'stop': '137', 'wait_time': 453.85400000000004, 'lines': '3', 'same_stop': 34, 'x': -74.009266, 'y': 40.715478, 'color': '#D82233'}, ('134', '1'): {'stop': '134', 'wait_time': 268.9315, 'lines': '1', 'same_stop': 31, 'x': -74.005367, 'y': 40.728251, 'color': '#D82233'}, ('135', '1'): {'stop': '135', 'wait_time': 269.0385, 'lines': '1', 'same_stop': 32, 'x': -74.006277, 'y': 40.722854, 'color': '#D82233'}, ('136', '1'): {'stop': '136', 'wait_time': 269.0385, 'lines': '1', 'same_stop': 33, 'x': -74.006886, 'y': 40.719318, 'color': '#D82233'}, ('137', '1'): {'stop': '137', 'wait_time': 268.2175, 'lines': '1', 'same_stop': 34, 'x': -74.009266, 'y': 40.715478, 'color': '#D82233'}, ('138', '1'): {'stop': '138', 'wait_time': 268.9675, 'lines': '1', 'same_stop': 35, 'x': -74.012188, 'y': 40.711835, 'color': '#D82233'}, ('228', '2'): {'stop': '228', 'wait_time': 405.133, 'lines': '2', 'same_stop': 62, 'x': -74.008811, 'y': 40.713051, 'color': '#D82233'}, ('228', '3'): {'stop': '228', 'wait_time': 454.132, 'lines': '3', 'same_stop': 62, 'x': -74.008811, 'y': 40.713051, 'color': '#D82233'}, ('139', '1'): {'stop': '139', 'wait_time': 268.9675, 'lines': '1', 'same_stop': 36, 'x': -74.013783, 'y': 40.707513, 'color': '#D82233'}, ('142', '1'): {'stop': '142', 'wait_time': 269.2175, 'lines': '1', 'same_stop': 37, 'x': -74.013664, 'y': 40.702068, 'color': '#D82233'}, ('201', '2'): {'stop': '201', 'wait_time': 419.773, 'lines': '2', 'same_stop': 38, 'x': -73.85062, 'y': 40.903125, 'color': '#D82233'}, ('204', '2'): {'stop': '204', 'wait_time': 401.5245, 'lines': '2', 'same_stop': 39, 'x': -73.854376, 'y': 40.898379, 'color': '#D82233'}, ('205', '2'): {'stop': '205', 'wait_time': 402.1015, 'lines': '2', 'same_stop': 40, 'x': -73.857473, 'y': 40.893193, 'color': '#D82233'}, ('204', '5'): {'stop': '204', 'wait_time': 610.1295, 'lines': '5', 'same_stop': 39, 'x': -73.854376, 'y': 40.898379, 'color': '#009952'}, ('205', '5'): {'stop': '205', 'wait_time': 610.1295, 'lines': '5', 'same_stop': 40, 'x': -73.857473, 'y': 40.893193, 'color': '#009952'}, ('206', '2'): {'stop': '206', 'wait_time': 402.1015, 'lines': '2', 'same_stop': 41, 'x': -73.860341, 'y': 40.888022, 'color': '#D82233'}, ('206', '5'): {'stop': '206', 'wait_time': 610.1295, 'lines': '5', 'same_stop': 41, 'x': -73.860341, 'y': 40.888022, 'color': '#009952'}, ('207', '2'): {'stop': '207', 'wait_time': 401.5245, 'lines': '2', 'same_stop': 42, 'x': -73.862633, 'y': 40.883895, 'color': '#D82233'}, ('207', '5'): {'stop': '207', 'wait_time': 610.1295, 'lines': '5', 'same_stop': 42, 'x': -73.862633, 'y': 40.883895, 'color': '#009952'}, ('208', '2'): {'stop': '208', 'wait_time': 401.813, 'lines': '2', 'same_stop': 43, 'x': -73.866256, 'y': 40.87785, 'color': '#D82233'}, ('208', '5'): {'stop': '208', 'wait_time': 612.2725, 'lines': '5', 'same_stop': 43, 'x': -73.866256, 'y': 40.87785, 'color': '#009952'}, ('209', '2'): {'stop': '209', 'wait_time': 401.5245, 'lines': '2', 'same_stop': 44, 'x': -73.867164, 'y': 40.871356, 'color': '#D82233'}, ('209', '5'): {'stop': '209', 'wait_time': 610.1295, 'lines': '5', 'same_stop': 44, 'x': -73.867164, 'y': 40.871356, 'color': '#009952'}, ('210', '2'): {'stop': '210', 'wait_time': 401.5245, 'lines': '2', 'same_stop': 45, 'x': -73.867352, 'y': 40.865462, 'color': '#D82233'}, ('210', '5'): {'stop': '210', 'wait_time': 610.1295, 'lines': '5', 'same_stop': 45, 'x': -73.867352, 'y': 40.865462, 'color': '#009952'}, ('211', '2'): {'stop': '211', 'wait_time': 401.5245, 'lines': '2', 'same_stop': 46, 'x': -73.867615, 'y': 40.857192, 'color': '#D82233'}, ('211', '5'): {'stop': '211', 'wait_time': 612.2725, 'lines': '5', 'same_stop': 46, 'x': -73.867615, 'y': 40.857192, 'color': '#009952'}, ('212', '2'): {'stop': '212', 'wait_time': 401.236, 'lines': '2', 'same_stop': 47, 'x': -73.868457, 'y': 40.848828, 'color': '#D82233'}, ('212', '5'): {'stop': '212', 'wait_time': 612.2725, 'lines': '5', 'same_stop': 47, 'x': -73.868457, 'y': 40.848828, 'color': '#009952'}, ('213', '2'): {'stop': '213', 'wait_time': 401.236, 'lines': '2', 'same_stop': 48, 'x': -73.873488, 'y': 40.841894, 'color': '#D82233'}, ('213', '5'): {'stop': '213', 'wait_time': 374.543, 'lines': '5', 'same_stop': 48, 'x': -73.873488, 'y': 40.841894, 'color': '#009952'}, ('214', '2'): {'stop': '214', 'wait_time': 402.019, 'lines': '2', 'same_stop': 49, 'x': -73.880049, 'y': 40.840295, 'color': '#D82233'}, ('214', '5'): {'stop': '214', 'wait_time': 439.3345, 'lines': '5', 'same_stop': 49, 'x': -73.880049, 'y': 40.840295, 'color': '#009952'}, ('221', '5'): {'stop': '221', 'wait_time': 383.787, 'lines': '5', 'same_stop': 56, 'x': -73.917757, 'y': 40.816109, 'color': '#009952'}, ('505', '5'): {'stop': '505', 'wait_time': 536.1285, 'lines': '5', 'same_stop': 115, 'x': -73.860495, 'y': 40.854364, 'color': '#009952'}, ('215', '2'): {'stop': '215', 'wait_time': 402.555, 'lines': '2', 'same_stop': 50, 'x': -73.887734, 'y': 40.837288, 'color': '#D82233'}, ('215', '5'): {'stop': '215', 'wait_time': 439.3345, 'lines': '5', 'same_stop': 50, 'x': -73.887734, 'y': 40.837288, 'color': '#009952'}, ('216', '2'): {'stop': '216', 'wait_time': 403.0905, 'lines': '2', 'same_stop': 51, 'x': -73.891865, 'y': 40.829993, 'color': '#D82233'}, ('216', '5'): {'stop': '216', 'wait_time': 439.3345, 'lines': '5', 'same_stop': 51, 'x': -73.891865, 'y': 40.829993, 'color': '#009952'}, ('217', '2'): {'stop': '217', 'wait_time': 403.626, 'lines': '2', 'same_stop': 52, 'x': -73.893064, 'y': 40.824073, 'color': '#D82233'}, ('217', '5'): {'stop': '217', 'wait_time': 439.3345, 'lines': '5', 'same_stop': 52, 'x': -73.893064, 'y': 40.824073, 'color': '#009952'}, ('218', '2'): {'stop': '218', 'wait_time': 403.04949999999997, 'lines': '2', 'same_stop': 53, 'x': -73.896736, 'y': 40.822181, 'color': '#D82233'}, ('218', '5'): {'stop': '218', 'wait_time': 437.43499999999995, 'lines': '5', 'same_stop': 53, 'x': -73.896736, 'y': 40.822181, 'color': '#009952'}, ('219', '2'): {'stop': '219', 'wait_time': 403.04949999999997, 'lines': '2', 'same_stop': 54, 'x': -73.90177, 'y': 40.819585, 'color': '#D82233'}, ('219', '5'): {'stop': '219', 'wait_time': 437.43499999999995, 'lines': '5', 'same_stop': 54, 'x': -73.90177, 'y': 40.819585, 'color': '#009952'}, ('220', '2'): {'stop': '220', 'wait_time': 403.874, 'lines': '2', 'same_stop': 55, 'x': -73.907807, 'y': 40.81649, 'color': '#D82233'}, ('220', '5'): {'stop': '220', 'wait_time': 437.43499999999995, 'lines': '5', 'same_stop': 55, 'x': -73.907807, 'y': 40.81649, 'color': '#009952'}, ('221', '2'): {'stop': '221', 'wait_time': 404.121, 'lines': '2', 'same_stop': 56, 'x': -73.917757, 'y': 40.816109, 'color': '#D82233'}, ('222', '2'): {'stop': '222', 'wait_time': 403.8325, 'lines': '2', 'same_stop': 57, 'x': -73.926718, 'y': 40.81841, 'color': '#D82233'}, ('222', '5'): {'stop': '222', 'wait_time': 382.8375, 'lines': '5', 'same_stop': 57, 'x': -73.926718, 'y': 40.81841, 'color': '#009952'}, ('224', '2'): {'stop': '224', 'wait_time': 403.288, 'lines': '2', 'same_stop': 58, 'x': -73.94077, 'y': 40.814229, 'color': '#D82233'}, ('416', '5'): {'stop': '416', 'wait_time': 383.0435, 'lines': '5', 'same_stop': 106, 'x': -73.929849, 'y': 40.813224, 'color': '#009952'}, ('225', '2'): {'stop': '225', 'wait_time': 403.288, 'lines': '2', 'same_stop': 59, 'x': -73.945495, 'y': 40.807754, 'color': '#D82233'}, ('224', '3'): {'stop': '224', 'wait_time': 452.3265, 'lines': '3', 'same_stop': 58, 'x': -73.94077, 'y': 40.814229, 'color': '#D82233'}, ('225', '3'): {'stop': '225', 'wait_time': 452.795, 'lines': '3', 'same_stop': 59, 'x': -73.945495, 'y': 40.807754, 'color': '#D82233'}, ('302', '3'): {'stop': '302', 'wait_time': 453.9235, 'lines': '3', 'same_stop': 92, 'x': -73.936245, 'y': 40.820421, 'color': '#D82233'}, ('226', '2'): {'stop': '226', 'wait_time': 403.288, 'lines': '2', 'same_stop': 60, 'x': -73.949625, 'y': 40.802098, 'color': '#D82233'}, ('226', '3'): {'stop': '226', 'wait_time': 452.795, 'lines': '3', 'same_stop': 60, 'x': -73.949625, 'y': 40.802098, 'color': '#D82233'}, ('229', '2'): {'stop': '229', 'wait_time': 404.8445, 'lines': '2', 'same_stop': 63, 'x': -74.006571, 'y': 40.709416, 'color': '#D82233'}, ('229', '3'): {'stop': '229', 'wait_time': 453.85400000000004, 'lines': '3', 'same_stop': 63, 'x': -74.006571, 'y': 40.709416, 'color': '#D82233'}, ('230', '2'): {'stop': '230', 'wait_time': 405.133, 'lines': '2', 'same_stop': 64, 'x': -74.0091, 'y': 40.706821, 'color': '#D82233'}, ('230', '3'): {'stop': '230', 'wait_time': 454.132, 'lines': '3', 'same_stop': 64, 'x': -74.0091, 'y': 40.706821, 'color': '#D82233'}, ('231', '2'): {'stop': '231', 'wait_time': 404.29949999999997, 'lines': '2', 'same_stop': 65, 'x': -73.993086, 'y': 40.697466, 'color': '#D82233'}, ('231', '3'): {'stop': '231', 'wait_time': 453.507, 'lines': '3', 'same_stop': 65, 'x': -73.993086, 'y': 40.697466, 'color': '#D82233'}, ('232', '2'): {'stop': '232', 'wait_time': 403.4665, 'lines': '2', 'same_stop': 66, 'x': -73.989998, 'y': 40.693219, 'color': '#D82233'}, ('232', '3'): {'stop': '232', 'wait_time': 452.882, 'lines': '3', 'same_stop': 66, 'x': -73.989998, 'y': 40.693219, 'color': '#D82233'}, ('233', '2'): {'stop': '233', 'wait_time': 403.4665, 'lines': '2', 'same_stop': 67, 'x': -73.985065, 'y': 40.690545, 'color': '#D82233'}, ('233', '3'): {'stop': '233', 'wait_time': 452.882, 'lines': '3', 'same_stop': 67, 'x': -73.985065, 'y': 40.690545, 'color': '#D82233'}, ('234', '2'): {'stop': '234', 'wait_time': 403.4665, 'lines': '2', 'same_stop': 68, 'x': -73.980492, 'y': 40.688246, 'color': '#D82233'}, ('234', '3'): {'stop': '234', 'wait_time': 452.882, 'lines': '3', 'same_stop': 68, 'x': -73.980492, 'y': 40.688246, 'color': '#D82233'}, ('235', '2'): {'stop': '235', 'wait_time': 403.4665, 'lines': '2', 'same_stop': 69, 'x': -73.977666, 'y': 40.684359, 'color': '#D82233'}, ('235', '3'): {'stop': '235', 'wait_time': 452.882, 'lines': '3', 'same_stop': 69, 'x': -73.977666, 'y': 40.684359, 'color': '#D82233'}, ('234', '4'): {'stop': '234', 'wait_time': 324.9905, 'lines': '4', 'same_stop': 68, 'x': -73.980492, 'y': 40.688246, 'color': '#009952'}, ('235', '4'): {'stop': '235', 'wait_time': 324.9905, 'lines': '4', 'same_stop': 69, 'x': -73.977666, 'y': 40.684359, 'color': '#009952'}, ('234', '5'): {'stop': '234', 'wait_time': 390.6735, 'lines': '5', 'same_stop': 68, 'x': -73.980492, 'y': 40.688246, 'color': '#009952'}, ('235', '5'): {'stop': '235', 'wait_time': 390.6735, 'lines': '5', 'same_stop': 69, 'x': -73.977666, 'y': 40.684359, 'color': '#009952'}, ('423', '4'): {'stop': '423', 'wait_time': 325.40700000000004, 'lines': '4', 'same_stop': 110, 'x': -73.990151, 'y': 40.692404, 'color': '#009952'}, ('423', '5'): {'stop': '423', 'wait_time': 391.3555, 'lines': '5', 'same_stop': 110, 'x': -73.990151, 'y': 40.692404, 'color': '#009952'}, ('236', '2'): {'stop': '236', 'wait_time': 404.002, 'lines': '2', 'same_stop': 70, 'x': -73.975098, 'y': 40.680829, 'color': '#D82233'}, ('236', '3'): {'stop': '236', 'wait_time': 453.351, 'lines': '3', 'same_stop': 70, 'x': -73.975098, 'y': 40.680829, 'color': '#D82233'}, ('239', '4'): {'stop': '239', 'wait_time': 323.8, 'lines': '4', 'same_stop': 73, 'x': -73.958131, 'y': 40.670682, 'color': '#009952'}, ('239', '5'): {'stop': '239', 'wait_time': 386.4205, 'lines': '5', 'same_stop': 73, 'x': -73.958131, 'y': 40.670682, 'color': '#009952'}, ('237', '2'): {'stop': '237', 'wait_time': 404.002, 'lines': '2', 'same_stop': 71, 'x': -73.971046, 'y': 40.675235, 'color': '#D82233'}, ('237', '3'): {'stop': '237', 'wait_time': 453.351, 'lines': '3', 'same_stop': 71, 'x': -73.971046, 'y': 40.675235, 'color': '#D82233'}, ('238', '2'): {'stop': '238', 'wait_time': 402.633, 'lines': '2', 'same_stop': 72, 'x': -73.964375, 'y': 40.671987, 'color': '#D82233'}, ('238', '3'): {'stop': '238', 'wait_time': 452.882, 'lines': '3', 'same_stop': 72, 'x': -73.964375, 'y': 40.671987, 'color': '#D82233'}, ('239', '2'): {'stop': '239', 'wait_time': 403.1685, 'lines': '2', 'same_stop': 73, 'x': -73.958131, 'y': 40.670682, 'color': '#D82233'}, ('239', '3'): {'stop': '239', 'wait_time': 450.851, 'lines': '3', 'same_stop': 73, 'x': -73.958131, 'y': 40.670682, 'color': '#D82233'}, ('241', '2'): {'stop': '241', 'wait_time': 453.0325, 'lines': '2', 'same_stop': 74, 'x': -73.950683, 'y': 40.667883, 'color': '#D82233'}, ('241', '5'): {'stop': '241', 'wait_time': 478.38649999999996, 'lines': '5', 'same_stop': 74, 'x': -73.950683, 'y': 40.667883, 'color': '#009952'}, ('248', '2'): {'stop': '248', 'wait_time': 1800.0, 'lines': '2', 'same_stop': 81, 'x': -73.950466, 'y': 40.669847, 'color': '#D82233'}, ('248', '3'): {'stop': '248', 'wait_time': 451.163, 'lines': '3', 'same_stop': 81, 'x': -73.950466, 'y': 40.669847, 'color': '#D82233'}, ('250', '4'): {'stop': '250', 'wait_time': 323.0615, 'lines': '4', 'same_stop': 83, 'x': -73.932942, 'y': 40.668897, 'color': '#009952'}, ('250', '5'): {'stop': '250', 'wait_time': 1204.286, 'lines': '5', 'same_stop': 83, 'x': -73.932942, 'y': 40.668897, 'color': '#009952'}, ('242', '2'): {'stop': '242', 'wait_time': 453.0325, 'lines': '2', 'same_stop': 75, 'x': -73.95085, 'y': 40.662742, 'color': '#D82233'}, ('242', '5'): {'stop': '242', 'wait_time': 478.38649999999996, 'lines': '5', 'same_stop': 75, 'x': -73.95085, 'y': 40.662742, 'color': '#009952'}, ('243', '2'): {'stop': '243', 'wait_time': 452.095, 'lines': '2', 'same_stop': 76, 'x': -73.9502, 'y': 40.656652, 'color': '#D82233'}, ('243', '5'): {'stop': '243', 'wait_time': 477.962, 'lines': '5', 'same_stop': 76, 'x': -73.9502, 'y': 40.656652, 'color': '#009952'}, ('244', '2'): {'stop': '244', 'wait_time': 443.74649999999997, 'lines': '2', 'same_stop': 77, 'x': -73.949575, 'y': 40.650843, 'color': '#D82233'}, ('244', '5'): {'stop': '244', 'wait_time': 477.212, 'lines': '5', 'same_stop': 77, 'x': -73.949575, 'y': 40.650843, 'color': '#009952'}, ('245', '2'): {'stop': '245', 'wait_time': 44

## export

In [336]:
def serialize(obj):
    if isinstance(obj, np.int64):
         return int(obj)
    if not isinstance(obj, (str, int, float, bool)):
        return list(obj)
    else: return obj

data1 = nx.node_link_data(gn, edges="edges")
with open('subwaygraph_rush_dir.json', 'w') as f:
    json.dump(data1,f, default=serialize)